{
  "alerts": [
    {
      "id": "111fd666-9666-4e66-a066-d66fd966ad11",
      "severity": "HIGH",
      "description": "Malware detected on page one endpoint",
      "type": "Event::Endpoint::Threat::Detected",
      "when": "2020-08-02T21:30:55.487Z"
    },
    {
      "id": "222fd666-9666-4e66-a066-d66fd966ad22",
      "severity": "MEDIUM",
      "description": "Malware detected on page two endpoint",
      "type": "Event::Endpoint::Threat::Detected",
      "when": "2020-08-02T22:30:55.487Z"
    }
  ]
}
