# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Component:
    DESCRIPTION = "Update an existing ServiceNow CI record"


class Input:
    SYSTEM_ID = "system_id"
    TABLE = "table"
    UPDATE_DATA = "update_data"
    

class Output:
    SUCCESS = "success"
    

class UpdateCiInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "system_id": {
      "type": "string",
      "title": "System ID",
      "description": "System ID of the CI record to update",
      "order": 2
    },
    "table": {
      "type": "string",
      "title": "Table",
      "description": "The ServiceNow table where the CI record will be updated",
      "order": 1
    },
    "update_data": {
      "type": "object",
      "title": "Update Data",
      "description": "JSON object containing the fields and values to perform a CI update",
      "order": 3
    }
  },
  "required": [
    "system_id",
    "table",
    "update_data"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class UpdateCiOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "success": {
      "type": "boolean",
      "title": "Success",
      "description": "True if the update was successful",
      "order": 1
    }
  },
  "required": [
    "success"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
