# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Retrieve a single task by ID"


class Input:
    EXPAND = "expand"
    ID = "id"
    SELECT = "select"


class Output:
    TASK = "task"


class GetTaskInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "expand": {
      "type": "string",
      "title": "Expand",
      "description": "Comma separated list of related collections to embed in the result",
      "order": 3
    },
    "id": {
      "type": "integer",
      "title": "ID",
      "description": "ID of the task to retrieve",
      "order": 1
    },
    "select": {
      "type": "string",
      "title": "Select",
      "description": "Comma separated list of fields to return. Leave empty to return every field",
      "order": 2
    }
  },
  "required": [
    "id"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetTaskOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "task": {
      "$ref": "#/definitions/task",
      "title": "Task",
      "description": "The requested task",
      "order": 1
    }
  },
  "required": [
    "task"
  ],
  "definitions": {
    "task": {
      "type": "object",
      "title": "task",
      "properties": {
        "vendors": {
          "type": "array",
          "title": "Vendors",
          "description": "Vendors",
          "items": {
            "$ref": "#/definitions/task_vendor_lookup"
          },
          "order": 1
        },
        "risks": {
          "type": "array",
          "title": "Risks",
          "description": "Risks",
          "items": {
            "$ref": "#/definitions/task_risk_lookup"
          },
          "order": 2
        },
        "controls": {
          "type": "array",
          "title": "Controls",
          "description": "Controls",
          "items": {
            "$ref": "#/definitions/task_control_lookup"
          },
          "order": 3
        },
        "itAssets": {
          "type": "array",
          "title": "IT Assets",
          "description": "IT Assets",
          "items": {
            "$ref": "#/definitions/task_it_asset_lookup"
          },
          "order": 4
        },
        "clients": {
          "type": "array",
          "title": "Clients",
          "description": "Clients",
          "items": {
            "$ref": "#/definitions/task_client_lookup"
          },
          "order": 5
        },
        "assessments": {
          "type": "array",
          "title": "Assessments",
          "description": "Assessments",
          "items": {
            "$ref": "#/definitions/task_assessment_lookup"
          },
          "order": 6
        },
        "contracts": {
          "type": "array",
          "title": "Contracts",
          "description": "Contracts",
          "items": {
            "$ref": "#/definitions/task_contract_lookup"
          },
          "order": 7
        },
        "audits": {
          "type": "array",
          "title": "Audits",
          "description": "Audits",
          "items": {
            "$ref": "#/definitions/task_audit_lookup"
          },
          "order": 8
        },
        "incidents": {
          "type": "array",
          "title": "Incidents",
          "description": "Incidents",
          "items": {
            "$ref": "#/definitions/task_incident_lookup"
          },
          "order": 9
        },
        "departments": {
          "type": "array",
          "title": "Departments",
          "description": "Departments",
          "items": {
            "$ref": "#/definitions/task_department_lookup"
          },
          "order": 10
        },
        "locations": {
          "type": "array",
          "title": "Locations",
          "description": "Locations",
          "items": {
            "$ref": "#/definitions/task_location_lookup"
          },
          "order": 11
        },
        "securityPolicies": {
          "type": "array",
          "title": "Security Policies",
          "description": "Security Policies",
          "items": {
            "$ref": "#/definitions/task_security_policy_lookup"
          },
          "order": 12
        },
        "queries": {
          "type": "array",
          "title": "Queries",
          "description": "Queries",
          "items": {
            "$ref": "#/definitions/task_query_lookup"
          },
          "order": 13
        },
        "integrations": {
          "type": "array",
          "title": "Integrations",
          "description": "Integrations",
          "items": {
            "$ref": "#/definitions/task_integration_lookup"
          },
          "order": 14
        },
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 15
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 16
        },
        "description": {
          "type": "string",
          "title": "Description",
          "description": "Description",
          "order": 17
        },
        "taskTypeID": {
          "type": "integer",
          "title": "Task Type ID",
          "description": "Task Type ID",
          "order": 18
        },
        "isArchived": {
          "type": "boolean",
          "title": "Is Archived",
          "description": "Is Archived",
          "order": 19
        },
        "trend": {
          "type": "string",
          "title": "Trend",
          "description": "Trend",
          "order": 20
        },
        "compliance": {
          "type": "integer",
          "title": "Compliance",
          "description": "Compliance",
          "order": 21
        },
        "instructions": {
          "type": "string",
          "title": "Instructions",
          "description": "Instructions",
          "order": 22
        },
        "requireAcknowledgement": {
          "type": "boolean",
          "title": "Require Acknowledgement",
          "description": "Require Acknowledgement",
          "order": 23
        },
        "approvalStatus": {
          "type": "boolean",
          "title": "Approval Status",
          "description": "Approval Status",
          "order": 24
        },
        "raiseServiceRequest": {
          "type": "boolean",
          "title": "Raise Service Request",
          "description": "Raise Service Request",
          "order": 25
        },
        "startDate": {
          "type": "string",
          "format": "date-time",
          "displayType": "date",
          "title": "Start Date",
          "description": "Start Date",
          "order": 26
        },
        "endDate": {
          "type": "string",
          "format": "date-time",
          "displayType": "date",
          "title": "End Date",
          "description": "End Date",
          "order": 27
        },
        "dueDate": {
          "type": "string",
          "format": "date-time",
          "displayType": "date",
          "title": "Due Date",
          "description": "Due Date",
          "order": 28
        },
        "isEnabled": {
          "type": "boolean",
          "title": "Is Enabled",
          "description": "Is Enabled",
          "order": 29
        },
        "shouldReset": {
          "type": "boolean",
          "title": "Should Reset",
          "description": "Should Reset",
          "order": 30
        },
        "shouldRepeat": {
          "type": "boolean",
          "title": "Should Repeat",
          "description": "Should Repeat",
          "order": 31
        },
        "isDynamicOwnership": {
          "type": "boolean",
          "title": "Is Dynamic Ownership",
          "description": "Is Dynamic Ownership",
          "order": 32
        },
        "frequency": {
          "type": "integer",
          "title": "Frequency",
          "description": "Frequency",
          "order": 33
        },
        "sendReminders": {
          "type": "boolean",
          "title": "Send Reminders",
          "description": "Send Reminders",
          "order": 34
        },
        "isQueryDriven": {
          "type": "boolean",
          "title": "Is Query Driven",
          "description": "Is Query Driven",
          "order": 35
        },
        "primaryDriver": {
          "type": "integer",
          "title": "Primary Driver",
          "description": "Primary Driver",
          "order": 36
        },
        "statusID": {
          "type": "integer",
          "title": "Status ID",
          "description": "Status ID",
          "order": 37
        },
        "discussionFieldID": {
          "type": "integer",
          "title": "Discussion Field ID",
          "description": "Discussion Field ID",
          "order": 38
        },
        "compylKey": {
          "type": "string",
          "title": "Compyl Key",
          "description": "Compyl Key",
          "order": 39
        },
        "isAuditorRequest": {
          "type": "boolean",
          "title": "Is Auditor Request",
          "description": "Is Auditor Request",
          "order": 40
        },
        "isGeneratedByAI": {
          "type": "boolean",
          "title": "Is Generated By AI",
          "description": "Is Generated By AI",
          "order": 41
        },
        "compylAIEventGuid": {
          "type": "string",
          "title": "Compyl AI Event GUID",
          "description": "Compyl AI Event GUID",
          "order": 42
        },
        "createdDate": {
          "type": "string",
          "format": "date-time",
          "displayType": "date",
          "title": "Created Date",
          "description": "Created Date",
          "order": 43
        },
        "modifiedDate": {
          "type": "string",
          "format": "date-time",
          "displayType": "date",
          "title": "Modified Date",
          "description": "Modified Date",
          "order": 44
        },
        "createdBy": {
          "type": "string",
          "title": "Created By",
          "description": "Created By",
          "order": 45
        },
        "modifiedBy": {
          "type": "string",
          "title": "Modified By",
          "description": "Modified By",
          "order": 46
        },
        "assignedTo": {
          "$ref": "#/definitions/entity_user",
          "title": "Assigned To",
          "description": "Assigned To",
          "order": 47
        },
        "extendedFields": {
          "type": "object",
          "title": "Extended Fields",
          "description": "Extended Fields",
          "order": 48
        }
      }
    },
    "task_vendor_lookup": {
      "type": "object",
      "title": "task_vendor_lookup",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 2
        }
      }
    },
    "task_risk_lookup": {
      "type": "object",
      "title": "task_risk_lookup",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 2
        }
      }
    },
    "task_control_lookup": {
      "type": "object",
      "title": "task_control_lookup",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 2
        }
      }
    },
    "task_it_asset_lookup": {
      "type": "object",
      "title": "task_it_asset_lookup",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 2
        }
      }
    },
    "task_client_lookup": {
      "type": "object",
      "title": "task_client_lookup",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 2
        }
      }
    },
    "task_assessment_lookup": {
      "type": "object",
      "title": "task_assessment_lookup",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 2
        }
      }
    },
    "task_contract_lookup": {
      "type": "object",
      "title": "task_contract_lookup",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 2
        }
      }
    },
    "task_audit_lookup": {
      "type": "object",
      "title": "task_audit_lookup",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 2
        }
      }
    },
    "task_incident_lookup": {
      "type": "object",
      "title": "task_incident_lookup",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 2
        }
      }
    },
    "task_department_lookup": {
      "type": "object",
      "title": "task_department_lookup",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 2
        }
      }
    },
    "task_location_lookup": {
      "type": "object",
      "title": "task_location_lookup",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 2
        }
      }
    },
    "task_security_policy_lookup": {
      "type": "object",
      "title": "task_security_policy_lookup",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 2
        }
      }
    },
    "task_query_lookup": {
      "type": "object",
      "title": "task_query_lookup",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 2
        }
      }
    },
    "task_integration_lookup": {
      "type": "object",
      "title": "task_integration_lookup",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 2
        }
      }
    },
    "entity_user": {
      "type": "object",
      "title": "entity_user",
      "properties": {
        "title": {
          "type": "string",
          "title": "Title",
          "description": "Title",
          "order": 1
        },
        "userEmail": {
          "type": "string",
          "title": "User Email",
          "description": "User Email",
          "order": 2
        },
        "userFirstName": {
          "type": "string",
          "title": "User First Name",
          "description": "User First Name",
          "order": 3
        },
        "userLastName": {
          "type": "string",
          "title": "User Last Name",
          "description": "User Last Name",
          "order": 4
        },
        "usersID": {
          "type": "integer",
          "title": "Users ID",
          "description": "Users ID",
          "order": 5
        },
        "associatedUserID": {
          "type": "integer",
          "title": "Associated User ID",
          "description": "Associated User ID",
          "order": 6
        },
        "active": {
          "type": "boolean",
          "title": "Active",
          "description": "Active",
          "order": 7
        },
        "raciOption": {
          "type": "integer",
          "title": "RACI Option",
          "description": "RACI Option",
          "order": 8
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
