{
  "state": {
    "last_user_update_collection_timestamp": "2023-07-20T16:21:15.341+00:00",
    "next_user_collection_timestamp": "2023-07-21 16:21:15.340262+00:00",
    "next_user_login_collection_timestamp": "2023-07-20 17:21:15.340262+00:00",
    "last_user_login_collection_timestamp": "2023-07-20 16:21:15.340262+00:00",
    "users_next_page_id": "/01gRO0000087654321-500"
  },
  "has_more_pages": true,
  "status_code": 200,
  "users": [
    {
      "attributes": {
        "type": "User",
        "url": "/services/data/v58.0/sobjects/User/005Hn00000HVWwxIAH"
      },
      "Id": "005Hn00000HVWwxIAH",
      "FirstName": "Security",
      "LastName": "User",
      "Email": "user@example.com",
      "Alias": "sec",
      "IsActive": true,
      "DataType": "User Update"
    },
    {
      "attributes": {
        "type": "User",
        "url": "/services/data/v58.0/sobjects/User/005Hn00000H35JtIAJ"
      },
      "Id": "005Hn00000H35JtIAJ",
      "FirstName": "Example",
      "LastName": "User",
      "Email": "user2@example.com",
      "Alias": "exam",
      "IsActive": true,
      "DataType": "User"
    },
    {
      "attributes": {
        "type": "User",
        "url": "/services/data/v58.0/sobjects/User/005Hn00000HVWwsIAH"
      },
      "Id": "005Hn00000HVWwsIAH",
      "FirstName": "Integration",
      "LastName": "User",
      "Email": "user3@example.com",
      "Alias": "integ",
      "IsActive": true,
      "DataType": "User"
    },
    {
      "attributes": {
        "type": "User",
        "url": "/services/data/v58.0/sobjects/User/005Hn00000HVWwxIAH"
      },
      "Id": "005Hn00000HVWwxIAH",
      "FirstName": "Security",
      "LastName": "User",
      "Email": "user@example.com",
      "Alias": "sec",
      "IsActive": true,
      "DataType": "User"
    },
    {
      "attributes": {
        "type": "LoginHistory",
        "url": "/services/data/v58.0/sobjects/LoginHistory/0YaHn0000EUyGdHKQV"
      },
      "LoginTime": "2023-07-23T16:18:23.000+0000",
      "UserId": "005Hn00000H35JtIAJ",
      "LoginType": "Remote Access 2.0",
      "LoginUrl": "login.salesforce.com",
      "SourceIp": "198.51.100.1",
      "Status": "Success",
      "Application": "New Connected App",
      "Browser": "Unknown",
      "DataType": "User Login"
    },
    {
      "attributes": {
        "type": "LoginHistory",
        "url": "/services/data/v58.0/sobjects/LoginHistory/0YaHn0000EUyGkcKQF"
      },
      "LoginTime": "2023-07-23T16:20:13.000+0000",
      "UserId": "005Hn00000H35JtIAJ",
      "LoginType": "Application",
      "LoginUrl": "example.salesforce.com",
      "SourceIp": "198.51.100.1",
      "Status": "Success",
      "Application": "Browser",
      "Browser": "Chrome 115",
      "DataType": "User Login"
    }
  ]
}
