{
  "state": {
    "last_user_update_collection_timestamp": "2023-07-20 16:21:15.340262+00:00",
    "next_user_collection_timestamp": "2023-07-20 16:21:15.340262+00:00",
    "next_user_login_collection_timestamp": "2023-07-20 16:21:15.340262+00:00",
    "last_user_login_collection_timestamp": "2023-07-20 15:21:15.340262+00:00"
  },
  "has_more_pages": false,
  "status_code": 400,
  "users": [],
  "error": "The server is unable to process the request. Verify your plugin input is correct and not malformed and try again. If the issue persists, please contact support."
}
