{
  "state": {
    "last_user_update_collection_timestamp": "2023-07-20T16:15:15.340+00:00",
    "next_user_collection_timestamp": "2023-07-20 16:21:15.340262+00:00",
    "next_user_login_collection_timestamp": "2023-07-20 16:21:15.340262+00:00",
    "last_user_login_collection_timestamp": "2023-07-20 15:21:15.340262+00:00"
  },
  "has_more_pages": false,
  "status_code": 200,
  "users": [
    {
      "attributes": {
        "type": "User",
        "url": "/services/data/v58.0/sobjects/User/005Hn00000H35JtIAJ"
      },
      "id": "005Hn00000H35JtIAJ",
      "firstName": "Example",
      "lastName": "User",
      "email": "user@example.com",
      "alias": "exam",
      "isActive": true,
      "dataType": "User"
    },
    {
      "attributes": {
        "type": "LoginHistory",
        "url": "/services/data/v58.0/sobjects/LoginHistory/0YaHn0000EUyGkcKQF"
      },
      "loginTime": "2023-07-23T16:20:13.000+0000",
      "userId": "005Hn00000H35JtIAJ",
      "loginType": "Application",
      "loginUrl": "example.salesforce.com",
      "sourceIp": "198.51.100.1",
      "status": "Success",
      "application": "Browser",
      "browser": "Chrome 115",
      "dataType": "User Login"
    }
  ]
}
