{
  "searchResults": [
    {
      "type": "Account",
      "url": "/services/data/v58.0/sobjects/Account/001Hn00001uAccount",
      "id": "001Hn00001uAccount"
    },
    {
      "type": "ExternalObject__c",
      "url": "/services/data/v58.0/sobjects/ExternalObject__c/a00Hn00000External",
      "id": "a00Hn00000External"
    },
    {
      "type": "Customer",
      "url": "/services/data/v58.0/sobjects/Customer/0o6Hn00000Customer",
      "id": "0o6Hn00000Customer"
    },
    {
      "type": "Topic",
      "url": "/services/data/v58.0/sobjects/Topic/0TOHn000000I1Topic",
      "id": "0TOHn000000I1Topic"
    },
    {
      "type": "CollaborationGroup",
      "url": "/services/data/v58.0/sobjects/CollaborationGroup/0F9Hn000000PCollab",
      "id": "0F9Hn000000PCollab"
    },
    {
      "type": "Note",
      "url": "/services/data/v58.0/sobjects/Note/002Hn00000n5KANote",
      "id": "002Hn00000n5KANote"
    }
  ]
}
