# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Input:
    API_TOKEN = "api_token"
    CUSTOMER_ID = "customer_id"
    

class ConnectionSchema(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "api_token": {
      "$ref": "#/definitions/credential_secret_key",
      "title": "API Token",
      "description": "Red Canary API authentication token",
      "order": 1
    },
    "customer_id": {
      "type": "string",
      "title": "Customer ID",
      "description": "Customer ID or name e.g. example from https://example.my.redcanary.co",
      "order": 2
    }
  },
  "required": [
    "api_token",
    "customer_id"
  ],
  "definitions": {
    "credential_secret_key": {
      "id": "credential_secret_key",
      "type": "object",
      "title": "Credential: Secret Key",
      "description": "A shared secret key",
      "properties": {
        "secretKey": {
          "type": "string",
          "title": "Secret Key",
          "displayType": "password",
          "description": "The shared secret key",
          "format": "password"
        }
      },
      "required": [
        "secretKey"
      ]
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
