class SearchParameters:
    PAGE_SIZE = "pageSize"
    PAGE = "page"
    CONDITIONS = "conditions"


class Ticket:
    SUMMARY = "summary"
    INITIAL_DESCRIPTION = "initialDescription"
    BOARD = "board"
    COMPANY = "company"
    DEPARTMENT = "department"
    LOCATION = "location"
    STATUS = "status"
    PRIORITY = "priority"
    SEVERITY = "severity"
    IMPACT = "impact"
    TEAM = "team"
    TYPE = "type"
    SUBTYPE = "subtype"
    CONTACT = "contact"
    SITE = "site"
    ADDRESS_LINE1 = "addressLine1"
    ADDRESS_LINE2 = "addressLine2"
    CITY = "city"
    ZIP = "zip"
    COUNTRY = "country"
    OWNER = "owner"
    ESTIMATED_START_DATE = "estimatedStartDate"
    REQUIRED_DATE = "requiredDate"
    AGREEMENT = "agreement"
    SERVICE_LOCATION = "serviceLocation"
    SOURCE = "source"
    BUDGET_HOURS = "budgetHours"
    AUTOMATIC_EMAIL_CONTACT_FLAG = "automaticEmailContactFlag"
    AUTOMATIC_EMAIL_RESOURCE_FLAG = "automaticEmailResourceFlag"
    AUTOMATIC_EMAIL_CC_FLAG = "automaticEmailCcFlag"
    AUTOMATIC_EMAIL_CC = "automaticEmailCc"
    PREDECESSOR_TYPE = "predecessorType"
    PREDECESSOR_ID = "predecessorId"
