plugin_spec_version: v2
extension: plugin
products: [insightconnect]
name: azure_ad_admin
title: Azure AD Admin
description: Perform administrative operations in Azure AD
version: 1.4.1
vendor: rapid7
support: community
status: []
resources:
  source_url: https://github.com/rapid7/insightconnect-plugins/tree/master/azure_ad_admin
  license_url: https://github.com/rapid7/insightconnect-plugins/blob/master/LICENSE
  vendor_url: https://www.microsoft.com/
tags:
  - Microsoft
  - Azure
  - Active Directory
  - Administration
hub_tags:
  use_cases: [threat_detection_and_response, user_management]
  keywords: [azure, microsoft, active directory, administration]
  features: []
types:
  user_information:
    accountEnabled:
      title: "Account Enabled"
      type: boolean
      description: "Account enabled"
      required: false
    displayName:
      title: "Display Name"
      type: string
      description: "Display name"
      required: false
    mobilePhone:
      title: "Mobile Phone"
      type: string
      description: "Mobile phone"
      required: false
    preferredLanguage:
      title: "Preferred Language"
      type: string
      description: "Preferred language"
      required: false
    jobTitle:
      title: "Job Title"
      type: string
      description: "Job title"
      required: false
    userPrincipalName:
      title: "User Principal Name"
      type: string
      description: "User principal name"
      required: false
    "@odata.context":
      title: "@odata.Context"
      type: string
      description: "@odata.context"
      required: false
    officeLocation:
      title: "Office Location"
      type: string
      description: "Office location"
      required: false
    businessPhones:
      title: "Business Phones"
      type: "[]string"
      description: "Business phones"
      required: false
    mail:
      title: "Mail"
      type: string
      description: "Mail"
      required: false
    surname:
      title: "Surname"
      type: string
      description: "Surname"
      required: false
    givenName:
      title: "Given Name"
      type: string
      description: "Given Name"
      required: false
    id:
      title: "ID"
      type: string
      description: "ID"
      required: false
  group:
    mailNickname:
      title: "Mail Nickname"
      type: string
      description: "Mail nickname"
      required: false
    groupTypes:
      title: "Group Types"
      type: "[]string"
      description: "Group types"
      required: false
    displayName:
      title: "Display Name"
      type: string
      description: "Display name"
      required: false
    description:
      title: "Description"
      type: string
      description: "Description"
      required: false
    createdDateTime:
      title: "Created Date Time"
      type: string
      description: "Created date time"
      required: false
    securityEnabled:
      title: "Security Enabled"
      type: boolean
      description: "Security enabled"
      required: false
    renewedDateTime:
      title: "Renewed Date Time"
      type: string
      description: "Renewed date time"
      required: false
    proxyAddresses:
      title: "Proxy Addresses"
      type: "[]string"
      description: "Proxy addresses"
      required: false
    visibility:
      title: "Visibility"
      type: string
      description: "Visibility"
      required: false
    mail:
      title: "Mail"
      type: string
      description: "Mail"
      required: false
    isAssignableToRole:
      title: "Is Assignable to Role"
      type: boolean
      description: "Is assignable to role"
      required: false
    id:
      title: "ID"
      type: string
      description: "ID"
      required: false
    mailEnabled:
      title: "Mail Enabled"
      type: boolean
      description: "Mail enabled"
      required: false
  geo_coordinates:
    altitude:
      title: Altitude
      description: The altitude (height), in feet, above sea level
      type: string
      required: false
    latitude:
      title: Latitude
      description: The latitude, in decimal
      type: string
      required: false
    longitude:
      title: Longitude
      description: The longitude, in decimal
      type: string
      required: false
  sign_in_location:
    city:
      title: City
      description: City where the sign-in originated. This is calculated using latitude/longitude information from the sign-in activity
      type: string
      required: false
    country_or_region:
      title: Country Or Region
      description: Country code info (2 letter code) where the sign-in originated. This is calculated using latitude/longitude information from the sign-in activity
      type: string
      required: false
    geo_coordinates:
      title: Geo Coordinates
      description: Geo coordinates
      type: geo_coordinates
      required: false
    state:
      title: State
      description: State where the sign-in originated. This is calculated using latitude/longitude information from the sign-in activity
      type: string
      required: false
  risk:
    id:
      title: ID
      description: Unique ID of the risk detection
      type: string
      required: true
    request_id:
      title: Request ID
      description: Request ID of the sign-in associated with the risk detection. This property is null if the risk detection is not associated with a sign-in
      type: string
      required: false
    correlation_id:
      title: Correlation ID
      description: Correlation ID of the sign-in associated with the risk detection. This property is null if the risk detection is not associated with a sign-in
      type: string
      required: false
    risk_type:
      title: Risk Type
      description: The type of risk event detected
      type: string
      required: false
    risk_state:
      title: Risk State
      description: The state of a detected risky user or sign-in
      type: string
      required: false
    risk_level:
      title: Risk Level
      description: Level of the detected risk
      type: string
      required: false
    risk_detail:
      title: Risk Detail
      description: Details of the detected risk. Details for this property are only available for Azure AD Premium P2 customers. P1 customers will be returned hidden
      type: string
      required: false
    source:
      title: Risk Level
      description: Source of the risk detection. For example, activeDirectory
      type: string
      required: false
    detection_timing_type:
      title: Detection Timimg Type
      description: Timing of the detected risk (real-time/offline). The possible values are notDefined, realtime, nearRealtime, offline, unknownFutureValue
      type: string
      required: false
    activity:
      title: Activity
      description: Indicates the activity type the detected risk is linked to. The possible values are signin, user, unknownFutureValue
      type: string
      required: false
    token_issuer_type:
      title: Token Issuer Type
      description: Indicates the type of token issuer for the detected sign-in risk. The possible values are AzureAD, ADFederationServices, and unknownFutureValue
      type: string
      required: false
    ip_address:
      title: IP Address
      description: IP address of the client from where the risk occurred
      type: string
      required: false
    location:
      title: Location
      description: Location of the client from where the risk occurred
      type: sign_in_location
      required: false
    activity_date_time:
      title: Activity Date Time
      description: Date and time that the risky activity occurred
      type: string
      required: false
    detected_date_time:
      title: Detected Date Time
      description: Date and time that the risk was detected
      type: string
      required: false
    last_updated_date_time:
      title: Last Updated Date Time
      description: Date and time that the risk detection was last updated
      type: string
      required: false
    user_id:
      title: User ID
      description: User ID
      type: string
      required: false
    user_display_name:
      title: User Display Name
      description: User display name
      type: string
      required: false
    user_principal_name:
      title: User Principal Name
      description: The user principal name (UPN) of the user
      type: string
      required: false
    additional_info:
      title: Additional Information
      description: Additional information associated with the risk detection
      type: string
      required: false

connection:
  tenant_id:
    title: Tenant ID
    description: The ID of the directory that identifies the tenant
    type: string
    required: true
  application_id:
    title: App ID
    description: The ID of the registered application that obtained the refresh token
    type: string
    required: true
  application_secret:
    title: App Secret
    description: The secret of the registered application that obtained the refresh token
    type: credential_secret_key
    required: true
actions:
  disable_user_account:
    title: Disable User Account
    description: Disable a user account. This action will not disable an administrative account
    input:
      user_id:
        title: User ID
        type: string
        description: User ID to disable e.g. user@example.com
        required: true
    output:
      success:
        title: Success
        description: Was operation successful
        type: boolean
        required: true
  enable_user_account:
    title: Enable User Account
    description: Enable a user account
    input:
      user_id:
        title: User ID
        type: string
        description: User ID to enable e.g. user@example.com
        required: true
    output:
      success:
        title: Success
        description: Was operation successful
        type: boolean
        required: true
  get_user_info:
    title: Get User Info
    description: Get user information
    input:
      user_id:
        title: User ID
        type: string
        description: User ID e.g. user@example.com
        required: true
    output:
      user_information:
        title: User Information
        description: Information about a user
        type: user_information
        required: true
  create_user:
    title: Create User and Notify
    description: Create a user with a randomly generated password and send out an email with the password
    input:
      display_name:
        title: Display Name
        description: The name to display in the address book for the user e.g. displayName-value
        type: string
        required: true
      mail_nickname:
        title: Mail Nickname
        description: The mail alias for the user e.g. mailNickname-value
        required: false
        type: string
      user_principal_name:
        title: User Principal Name
        description: The user principal name e.g. user@example.com
        required: true
        type: string
      account_enabled:
        title: Account Enabled
        description: True if the account is enabled; otherwise, false
        type: boolean
        default: true
        required: false
      notify_email_body:
        required: false
        title: Notify Email Body
        type: string
        description: Body of the email to be sent out. Use $password to place the generated password
      notify_recipient:
        required: true
        title: Recipient of creation email
        type: string
        description: Email address of the account to be notified of user creation
      notify_from:
          required: true
          title: Notify from
          description: User from which email notifcation will be sent
          type: string
    output:
      success:
        title: Success
        type: boolean
        required: true
        description: Did the step succeed
  force_user_to_change_password:
    title: Force User to Change Password
    description: Forces a user to change their password on their next successful login
    input:
      user_id:
        title: User ID
        type: string
        description: User ID
        required: true
    output:
      success:
        title: Success
        description: Was operation successful
        type: boolean
        required: true
  get_group_by_name:
    title: Get Group by Name
    description: Get a group by it's name
    input:
      name:
        title: Name
        description: Name
        type: string
        required: true
    output:
        group:
          title: Group
          description: Group
          type: group
          required: false
  add_user_to_group:
    title: Add User to Group
    description: Add a user to a group
    input:
      user_id:
        title: User ID
        description: User ID e.g. user@example.com
        type: string
        required: true
      group_name:
        title: Group Name
        description: Group Name e.g. My Azure Group
        type: string
        required: true
    output:
      success:
        title: Success
        description: Was operation successful
        type: boolean
        required: false
  remove_user_from_group:
    title: Remove User from Group
    description: Remove a user from a group
    input:
      user_id:
        title: User ID
        description: User ID e.g. user@example.com
        type: string
        required: true
      group_name:
        title: Group Name
        description: Group Name e.g. My Azure Group
        type: string
        required: true
    output:
      success:
        title: Success
        description: Was operation successful
        type: boolean
        required: false
triggers:
  risk_detection:
    title: Risk Detection
    description: Provides list of both user and sign-in linked risk detections and associated information about the detection
    input:
      frequency:
        type: integer
        description: Poll frequency in seconds
        default: 60
        required: false
      risk_level:
        title: Risk Level
        description: Risk level
        type: string
        required: true
        enum:
          - "low"
          - "medium"
          - "high"
          - "hidden"
          - "none"
          - "all"
    output:
      risk:
        title: Risk
        description: Risk
        type: risk
        required: true
