plugin_spec_version: v2
extension: plugin
product: ["insightconnect"]
name: timers
title: Timers
description: A variety of time-based triggers
version: 2.0.2
vendor: rapid7
support: community
status: []
resources:
  source_url: https://github.com/rapid7/insightconnect-plugins/
  license_url: https://github.com/rapid7/insightconnect-plugins/blob/master/LICENSE
tags:
- timer
- time
- cron
actions:
  delay:
    title: Delay
    description: Delays the workflow by a variable number of seconds
    input:
      delay:
        title: Delay
        type: float
        description: How long to delay the workflow (in seconds)
        required: true
    output: null
triggers:
  periodic:
    title: Every X Minutes
    description: Trigger an event periodically
    input:
      period:
        title: Period
        type: float
        description: Minutes between events
        default: 60
        required: true
      message:
        title: Message
        type: string
        description: A message to send with the event
        required: false
    output:
      message:
        type: string
        title: Message
        description: Message
        required: true
      time:
        type: date
        title: Time
        description: Time
        required: true
  hourly:
    title: Hourly
    description: Trigger events hourly
    input:
      minute:
        type: integer
        description: The minute after the hour to trigger the workflow
        title: Minute
        required: true
      message:
        type: string
        description: The message to send (optional)
        title: Message
        required: false
    output:
      message:
        type: string
        description: Message
        title: Message
        required: false
      time:
        type: string
        description: Time
        title: Time
        required: false
  daily:
    title: Daily
    description: Trigger events daily
    input:
      times_in_utc:
        type: string
        description: A comma-separated list of UTC times when you want the trigger
          to occur, e.g. 15:04,01:00,5:00
        title: Time in UTC
        required: true
      message:
        type: string
        description: The message to send (optional)
        required: false
        title: Message
    output:
      message:
        type: string
        description: Message
        required: false
        title: Message
      time:
        type: string
        description: Time
        required: false
        title: Time
  weekly:
    title: Weekly
    description: Trigger events weekly
    input:
      day:
        type: string
        description: Names of the day that you want the trigger to run
        title: Day
        required: true
      times_in_utc:
        type: string
        description: A comma-separated list of UTC times on those days when you want
          the trigger to occur
        required: true
        title: Time in UTC
      message:
        type: string
        description: The message to send (optional)
        required: false
        title: Message
    output:
      message:
        type: string
        description: Message
        required: false
        title: Message
      time:
        type: string
        description: Time
        required: false
        title: Time
  monthly:
    title: Monthly
    description: Trigger events monthly
    input:
      day_of_month:
        title: Day of Month
        type: integer
        description: Names of the days that you want the trigger
        required: true
      times_in_utc:
        type: string
        description: UTC times on the day you want the trigger to occur
        default: 00:00
        required: false
      message:
        title: Message
        type: string
        description: The message to send (optional)
        required: false
    output:
      message:
        type: string
        description: Message
        required: false
        title: Message
      time:
        type: string
        description: Time
        required: false
        title: Time
