plugin_spec_version: v2
extension: plugin
products: [insightconnect]
name: microsoft_teams
title: Microsoft Teams
description: The Microsoft Teams plugin allows you to send and trigger workflows on new messages. The plugin will also allow for teams management with the ability to add and remove teams, channels, and users
version: 3.0.0
vendor: rapid7
support: community
status: []
resources:
  source_url: https://github.com/rapid7/insightconnect-plugins/tree/master/microsoft_teams
  license_url: https://github.com/rapid7/insightconnect-plugins/blob/master/LICENSE
  vendor_url: https://www.microsoft.com
  docs_url: https://insightconnect.help.rapid7.com/docs/microsoft-teams
tags:
- microsoft
- teams
- office 365
- chat
hub_tags:
  use_cases: [alerting_and_notifications, application_management, threat_detection_and_response, user_management]
  keywords: [microsoft, teams, office 365, chat]
  features: []
types:
  team:
    displayName:
        title: "Display Name"
        type: string
        description: "Display name"
        required: false
    id:
        title: "ID"
        type: string
        description: "ID"
        required: false
    description:
        title: "Description"
        type: string
        description: "Description"
        required: false
  channel:
    displayName:
      title: "Display Name"
      type: string
      description: "Display name"
      required: false
    id:
      title: "ID"
      type: string
      description: "ID"
      required: false
    description:
      title: "Description"
      type: string
      description: "Description"
      required: false
  body:
    content:
      title: "Content"
      type: string
      description: "Content"
      required: false
    contentType:
      title: "Content Type"
      type: string
      description: "Content type"
      required: false
  user:
    displayName:
      title: "Display name"
      type: string
      description: "Display name"
      required: false
    id:
      title: "ID"
      type: string
      description: "ID"
      required: false
  from:
    user:
      title: "User"
      type: user
      description: "User"
      required: false
  message:
     body:
       title: "Body"
       type: body
       description: "Body"
       required: false
     from:
       title: "From"
       type: from
       description: "From"
       required: false
     createdDateTime:
       title: "Created Date Time"
       type: string
       description: "Created date time"
       required: false
     webUrl:
       title: "Web URL"
       type: string
       description: "Web URL"
       required: false
     importance:
       title: "Importance"
       type: string
       description: "Importance"
       required: false
     messageType:
       title: "Message Type"
       type: string
       description: "Message type"
       required: false
     locale:
       title: "Locale"
       type: string
       description: "Locale"
       required: false
     id:
       title: "ID"
       type: string
       description: "ID"
       required: false
  group:
      mailNickname:
        title: "Mail Nickname"
        type: string
        description: "Mail nickname"
        required: false
      id:
        title: "ID"
        type: string
        description: "ID"
        required: false
      mail:
        title: "Mail"
        type: string
        description: "Mail"
        required: false
      description:
        title: "Description"
        type: string
        description: "Description"
        required: false
      securityEnabled:
        title: "Security Enabled"
        type: boolean
        description: "Security enabled"
        required: false
      displayName:
        title: "Display Name"
        type: string
        description: "Display name"
        required: false
      createdDateTime:
        title: "Created Date Time"
        type: string
        description: "Created date time"
        required: false
      mailEnabled:
        title: "Mail Enabled"
        type: boolean
        description: "Mail enabled"
        required: false

connection:
  application_id:
    title: Application ID
    description: Application (client) ID
    type: string
    required: true
    example: 63a0cad6-ac64-435c-a221-5d37c97b763e
  directory_id:
    title: Directory ID
    description: Directory (tenant) ID
    type: string
    required: true
    example: 9e538ff5-dcb2-46a9-9a28-f93b8250deb0
  application_secret:
    title: Application Secret
    description: Application secret
    type: credential_secret_key
    required: true
    example: aMeCAEYdOLlK+qRcD9AjdyxLkCaqZH1UPm7adjJQ5Og=
  username_password:
    type: credential_username_password
    title: "Credentials"
    description: "Username and password"
    required: true
    example: '{ "username": "user", "password": "mypassword" }'

triggers:
  new_message_received:
    title: New Message Received
    description: Poll a channel for new messages
    input:
      team_name:
        title: Team Name
        description: Team name
        type: string
        required: true
        order: 1
        example: InsightConnect Team
      channel_name:
        title: Channel Name
        description: Channel
        type: string
        required: true
        order: 2
        example: InsightConnect Channel
      message_content:
        title: Message Content
        description: Regex to match new messages against
        type: string
        required: false
        order: 3
        example: "[Tt]est"
    output:
      message:
        title: Message
        description: The message object that was created
        type: message
        required: false

actions:
  get_teams:
    title: Get Teams
    description: Returns all the teams the configured user is allowed to see
    input:
      team_name:
        title: Team Name
        description: Optional regex-capable team name to look for
        type: string
        required: false
        example: InsightConnect Team
    output:
      teams:
        title: Teams
        description: Array of team objects
        type: "[]team"
        required: false
  get_channels_for_team:
    title: Get Channels for Team
    description: Returns all the channels associated with a team
    input:
      team_name:
        title: Team Name
        description: Team name to look for
        type: string
        required: true
        order: 1
        example: InsightConnect Team
      channel_name:
        title: Channel Name
        description: Optional regex-capable channel to look for
        type: string
        required: false
        order: 2
        example: InsightConnect Channel
    output:
      channels:
        title: Channels
        description: Array of channels
        type: "[]channel"
        required: false
  send_message:
    title: Send Message
    description: Send a message
    input:
      team_name:
        title: Team Name
        description: Team name
        type: string
        required: true
        order: 1
        example: InsightConnect Team
      channel_name:
        title: Channel Name
        description: Channel
        type: string
        required: true
        order: 2
        example: InsightConnect Channel
      thread_id:
        title: Thread ID
        description: To post in a thread, select parent message ID
        type: string
        required: true
        order: 3
        example: 1595889908700
      message:
        title: Message
        description: Message to send
        type: string
        required: true
        order: 4
        example: Hello!
    output:
      message:
        title: Message
        description: The message object that was created
        type: message
        required: false
  send_message_by_guid:
    title: Send Message by GUID
    description: Sends a message using the GUID for the team and channel. This is more performant than send message
    input:
      team_guid:
        title: Team GUID
        description: Team GUID
        type: string
        required: true
        order: 1
        example: xxxxx-xxxxx-xxxx-xxxx
      channel_guid:
        title: Channel GUID
        description: Channel GUID
        type: string
        required: true
        order: 2
        example: xxxxx-xxxxx-xxxx-xxxx
      is_html:
        title: Is HTML
        description: Is the message HTML
        type: boolean
        required: true
        order: 3
        example: false
      message:
        title: Message
        description: Message to send
        type: string
        required: true
        order: 4
        example: Hello!
    output:
      message:
        title: Message
        description: The message object that was created
        type: message
        required: false
  send_html_message:
    title: Send HTML Message
    description: Send HTML as a message
    input:
      team_name:
        title: Team Name
        description: Team name
        type: string
        required: true
        order: 1
        example: InsightConnect Team
      channel_name:
        title: Channel Name
        description: Channel name
        type: string
        required: true
        order: 2
        example: InsightConnect Channel
      thread_id:
        title: Thread ID
        description: To post in a thread, select parent message ID
        type: string
        required: true
        order: 3
        example: 1595889908700
      message_content:
        title: Message Content
        description: HTML content to send
        type: string
        required: true
        order: 4
        example: "<b>Hello!</b>"
    output:
      message:
        title: Message
        description: The message object that was created
        type: message
        required: false
  add_member_to_team:
    title: Add Member to Team
    description: Add a member to a team
    input:
      team_name:
        title: Team Name
        description: Team name
        type: string
        required: true
        order: 1
        example: InsightConnect Team
      member_login:
        title: Member Login
        description: Member login e.g. user@example.com
        type: string
        required: true
        order: 2
        example: user@example.com
    output:
      success:
        title: Success
        description: Boolean indicating if this action was successful
        type: boolean
        required: true
  remove_member_from_team:
    title: Remove Member from Team
    description: Remove a member from a team
    input:
      team_name:
        title: Team Name
        description: Team name
        type: string
        required: true
        order: 1
        example: InsightConnect Team
      member_login:
        title: Member Login
        description: Member Login e.g. user@example.com
        type: string
        required: true
        order: 2
        example: user@example.com
    output:
      success:
        title: Success
        description: Boolean indicating if this action was successful
        type: boolean
        required: true
  add_channel_to_team:
    title: Add Channel to Team
    description: Add a channel to a team
    input:
      team_name:
        title: Team Name
        description: Team name
        type: string
        required: true
        order: 1
        example: InsightConnect Team
      channel_name:
        title: Channel Name
        description: Channel name
        type: string
        required: true
        order: 2
        example: InsightConnect Channel
      channel_description:
        title: Channel Description
        description: Channel description
        type: string
        required: true
        order: 3
        example: This is a test channel.
    output:
      success:
        title: Success
        description: Boolean indicating if this action was successful
        type: boolean
        required: true
  remove_channel_from_team:
    title: Remove Channel from Team
    description: Remove a channel from a team
    input:
      team_name:
        title: Team Name
        description: Team name
        type: string
        required: true
        order: 1
        example: InsightConnect Team
      channel_name:
        title: Channel Name
        description: Channel name
        type: string
        required: true
        order: 2
        example: InsightConnect Channel
    output:
      success:
        title: Success
        description: Boolean indicating if this action was successful
        type: boolean
        required: true
  create_teams_enabled_group:
    title: Create Teams Enabled Group
    description: Create a group in Azure and enable it for Microsoft Teams
    input:
      group_name:
        title: Team Name
        description: Team name
        type: string
        required: true
        order: 1
        example: test_group
      group_description:
        title: Group Description
        description: Group description
        type: string
        required: true
        order: 2
        example: A test group
      mail_nickname:
        title: Mail Nickname
        description: The nickname for the email address of this group in Outlook
        type: string
        required: true
        order: 3
        example: TestGroup
      mail_enabled:
        title: Mail Enabled
        description: Should e-mail should be enabled for this group
        type: boolean
        required: true
        order: 4
        example: false
      owners:
        title: Owners
        description: A list of usernames to set as owners
        type: "string[]"
        required: false
        order: 5
        example: ['user@example.com']
      members:
        title: Members
        description: A list of usernames to set as members
        type: "string[]"
        required: false
        order: 6
        example: ['user@example.com']
    output:
      group:
        title: Group
        description: Information about the group that was created
        type: group
        required: false
  delete_team:
    title: Delete Team
    description: Delete a team and the associated group from Azure
    input:
      team_name:
        title: Team Name
        description: Team Name
        type: string
        required: true
        example: Test Team
    output:
      success:
        title: Success
        description: Boolean indicating if this action was successful
        type: boolean
        required: true
