plugin_spec_version: v2
name: nfs
title: NFS
description: Access files via NFS
version: 1.0.2
vendor: rapid7
support: community
status: []
tags:
- NFS
- Network File System
- nfs
connection:
  mount_pathname:
    title: Mount pathname
    description: Full pathname of the mount point on the NFS server (path separator
      is /)
    type: string
    required: true
  client_machine_name:
    title: Client machine name
    description: Network name of client machine (not the external DNS name)
    type: string
    required: true
  exports_file_hostname:
    title: Exports file Hostname
    description: Hostname of the client machine in the NFS server's /etc/exports file
    type: string
    required: true
  client_external_ip:
    title: Client external IP
    description: External IP that the client machine uses to contact the NFS server
    type: string
    required: true
  timeout:
    title: Timeout
    description: Assume the NFS server is down after this many seconds (0 means no
      timeout)
    type: integer
    required: false
actions:
  read:
    title: Read
    description: Read the named file via NFS
    input:
      file_pathname:
        title: File pathname
        description: File pathname starting with NFS mount point (path separator is
          /)
        type: string
        required: true
      lines_to_read:
        title: Lines to read
        description: Number of lines to read (unsupplied or -1 means read all lines)
        type: integer
        required: false
    output:
      lines_read:
        title: Lines read
        description: Lines read from the NFS-mounted file
        type: '[]string'
        required: true
  write:
    title: Write
    description: Write to the named file via NFS
    input:
      file_pathname:
        title: File pathname
        description: File pathname starting with NFS mount point (path separator is
          /)
        type: string
        required: true
      create_if_missing:
        title: Create if missing
        description: Create the named file before beginning write
        type: boolean
        required: false
        default: true
      remove_if_present:
        title: Remove if present
        description: Remove then re-create an empty file of the same name before beginning
          write
        type: boolean
        required: false
      lines_to_write:
        title: Lines to write
        description: Lines to write to the named file
        type: '[]string'
        required: true
    output:
      write_successful:
        title: Write successful
        description: The NFS write operation succeeded
        type: boolean
        required: true
triggers:
  file_changed:
    description: Reports any file changes within the given interval
    input:
      file_pathname:
        title: File pathname
        description: File pathname starting with NFS mount point (path separator is
          /)
        type: string
        required: true
      interval:
        type: integer
        description: How often to detect file changes (in seconds)
        default: 60
        required: true
    output:
      changed_attributes:
        title: Changed attributes
        description: Object containing the attributes that were updated
        type: object
        required: true
