# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Provides a list of IP network ranges with WHOIS records that match a specific query"


class Input:
    COUNTRY = "country"
    INCLUDE_TOTAL_COUNT = "include_total_count"
    IP = "ip"
    PAGE = "page"
    SERVER = "server"


class Output:
    RESPONSE = "response"


class ReverseIpWhoisInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "country": {
      "type": "string",
      "description": "Limits results to IP addresses allocated to an entity with a particular country",
      "order": 2
    },
    "include_total_count": {
      "type": "boolean",
      "description": "Returns the total number of results for a query",
      "default": false,
      "order": 4
    },
    "ip": {
      "type": "string",
      "title": "IP",
      "description": "Required for single IP result",
      "order": 1
    },
    "page": {
      "type": "string",
      "description": "Providing the page number allows access to additional pages of data",
      "order": 5
    },
    "server": {
      "type": "string",
      "description": "Limits results to ranges from a particular WHOIS server",
      "order": 3
    }
  },
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class ReverseIpWhoisOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "response": {
      "$ref": "#/definitions/reverse_ip_whois_response",
      "description": "Response",
      "order": 1
    }
  },
  "definitions": {
    "reverse_ip_whois_response": {
      "type": "object",
      "title": "reverse_ip_whois_response",
      "properties": {
        "country": {
          "type": "string",
          "order": 1
        },
        "ip_from": {
          "type": "string",
          "title": "IP From",
          "order": 2
        },
        "ip_from_alloc": {
          "type": "string",
          "title": "IP From Alloc",
          "order": 3
        },
        "ip_to": {
          "type": "string",
          "title": "IP To",
          "order": 4
        },
        "ip_to_alloc": {
          "type": "string",
          "title": "IP To Alloc",
          "order": 5
        },
        "organization": {
          "type": "string",
          "order": 6
        },
        "range": {
          "type": "string",
          "order": 7
        },
        "record_date": {
          "type": "string",
          "order": 8
        },
        "record_ip": {
          "type": "string",
          "title": "Record IP",
          "order": 9
        },
        "server": {
          "type": "string",
          "order": 10
        },
        "whois_record": {
          "type": "string",
          "order": 11
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
