# GENERATED BY KOMAND SDK - DO NOT EDIT
from setuptools import setup, find_packages


setup(name='threatstack-rapid7-plugin',
      version='1.0.1',
      description='The Threat Stack plugin is used to get information about alerts, assets, and policies',
      author='rapid7',
      author_email='',
      url='',
      packages=find_packages(),
      install_requires=['komand'],  # Add third-party dependencies to requirements.txt, not here!
      scripts=['bin/komand_threatstack']
      )
