./run -c sample account_expire_now > tests/account_expire_now.json
./run -c sample account_reactivate > tests/account_reactivate.json
./run -c sample account_revert_policy > tests/account_revert_policy.json
./run -c sample accounts_by_id > tests/accounts_by_id.json
./run -c sample activities_list > tests/activities_list.json
./run -c sample activities_types > tests/activities_types.json
./run -c sample agents_abort_scan > tests/agents_abort_scan.json
./run -c sample agents_approve_uninstall > tests/agents_approve_uninstall.json
./run -c sample agents_can_start_remote_shell > tests/agents_can_start_remote_shell.json
./run -c sample agents_connect > tests/agents_connect.json
./run -c sample agents_decommission > tests/agents_decommission.json
./run -c sample agents_disconnect > tests/agents_disconnect.json
./run -c sample agents_fetch_applications > tests/agents_fetch_applications.json
./run -c sample agents_fetch_firewall_rules > tests/agents_fetch_firewall_rules.json
./run -c sample agents_fetch_logs > tests/agents_fetch_logs.json
./run -c sample agents_firewall_logging > tests/agents_firewall_logging.json
./run -c sample agents_initiate > tests/agents_initiate.json
./run -c sample agents_processes > tests/agents_processes.json
./run -c sample agents_reject_uninstall > tests/agents_reject_uninstall.json
./run -c sample agents_reload > tests/agents_reload.json
./run -c sample agents_reset_local_config_policy > tests/agents_reset_local_config_policy.json
./run -c sample agents_restart > tests/agents_restart.json
./run -c sample agents_shutdown > tests/agents_shutdown.json
./run -c sample agents_start_remote_shell > tests/agents_start_remote_shell.json
./run -c sample agents_summary > tests/agents_summary.json
./run -c sample agents_terminate_remote_shell > tests/agents_terminate_remote_shell.json
./run -c sample agents_uninstall > tests/agents_uninstall.json
./run -c sample agents_update_software > tests/agents_update_software.json
./run -c sample apps_by_agent_ids > tests/apps_by_agent_ids.json
./run -c sample blacklist_by_content_hash > tests/blacklist_by_content_hash.json
./run -c sample blacklist_by_ioc_hash > tests/blacklist_by_ioc_hash.json
./run -c sample create_account > tests/create_account.json
./run -c sample create_admin_account > tests/create_admin_account.json
./run -c sample create_ioc_threat > tests/create_ioc_threat.json
./run -c sample get_accounts > tests/get_accounts.json
./run -c sample get_threat_summary > tests/get_threat_summary.json
./run -c sample last_activity_as_syslog > tests/last_activity_as_syslog.json
./run -c sample mark_as_benign > tests/mark_as_benign.json
./run -c sample mark_as_threat > tests/mark_as_threat.json
./run -c sample mitigate_threat > tests/mitigate_threat.json
./run -c sample name_available > tests/name_available.json
./run -c sample private_accounts > tests/private_accounts.json
./run -c sample update_account > tests/update_account.json