# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
from setuptools import setup, find_packages


setup(name="github-rapid7-plugin",
      version="3.0.0",
      description="[GitHub](https://github.com/) is a popular web-based Git or version control repository and Internet hosting service GitHub. InsightConnect plugin allows users and issues management. This plugin supports authentication from both personal and organization member accounts",
      author="rapid7",
      author_email="",
      url="",
      packages=find_packages(),
      install_requires=['insightconnect-plugin-runtime'],  # Add third-party dependencies to requirements.txt, not here!
      scripts=['bin/komand_github']
      )
