# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Input:
    NAMESERVER = "nameserver"
    

class Output:
    DOMAIN = "domain"
    

class NsWhoisInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "nameserver": {
      "type": "string",
      "title": "Nameserver Domain",
      "description": "Nameserver's domain name",
      "order": 1
    }
  },
  "required": [
    "nameserver"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class NsWhoisOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "domain": {
      "type": "array",
      "title": "Domain",
      "description": "Array of WHOIS results for the domain provided with all available information",
      "items": {
        "$ref": "#/definitions/email_whois"
      },
      "order": 1
    }
  },
  "required": [
    "domain"
  ],
  "definitions": {
    "email_whois": {
      "type": "object",
      "title": "email_whois",
      "properties": {
        "domains": {
          "type": "array",
          "title": "Domains",
          "description": "Domains registered by this email and whether the domain is current, meaning currently registered by this email address",
          "items": {
            "$ref": "#/definitions/whois_domain"
          },
          "order": 4
        },
        "limit": {
          "type": "integer",
          "title": "Limit",
          "description": "Total number of results for this page of results, default 500",
          "order": 3
        },
        "more_data_available": {
          "type": "boolean",
          "title": "More Data Available",
          "description": "Whether or not there are more than 500 results for this email, either yes or no",
          "order": 2
        },
        "total_results": {
          "type": "integer",
          "title": "Total Results",
          "description": "Total number of results for this email",
          "order": 1
        }
      },
      "required": [
        "more_data_available",
        "limit",
        "domains"
      ],
      "definitions": {
        "whois_domain": {
          "type": "object",
          "title": "whois_domain",
          "properties": {
            "current": {
              "type": "boolean",
              "title": "Current",
              "description": "Whether the domain is current, meaning currently registered by this email address",
              "order": 2
            },
            "domain": {
              "type": "string",
              "title": "Domain",
              "description": "Domain registered by this email",
              "order": 1
            }
          },
          "required": [
            "domain",
            "current"
          ]
        }
      }
    },
    "whois_domain": {
      "type": "object",
      "title": "whois_domain",
      "properties": {
        "current": {
          "type": "boolean",
          "title": "Current",
          "description": "Whether the domain is current, meaning currently registered by this email address",
          "order": 2
        },
        "domain": {
          "type": "string",
          "title": "Domain",
          "description": "Domain registered by this email",
          "order": 1
        }
      },
      "required": [
        "domain",
        "current"
      ]
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
