plugin_spec_version: v2
extension: plugin
product: ["insightconnect"]
name: typo_squatter
title: Typo Squatter
description: Typosquatter detects cybersquatting of domains and allows for domain scoring. This plugin can be used
to aid in phishing investigation and analysis.
version: 1.0.0
vendor: rapid7
support: community
status: []
resources:
  source_url: https://github.com/rapid7/insightconnect-plugins/tree/master/typo_squatter
  license_url: https://github.com/rapid7/insightconnect-plugins/blob/master/LICENSE
  vendor_url: https://www.rapid7.com
tags:
- dns
- typo
- squat
hub_tags:
  use_cases: [phishing_investigations, alert_enrichment]
  keywords: [dns, typo, squat]
  features: []
triggers:
  search_certstream:
    title: Search Certstream
    description: Searches certstream for new certs matching query
    input:
      query:
        title: Query
        description: Query to match
        type: string
        required: false
      domain:
        title: Domain
        description: Domain to check
        type: string
        default: google.com
        required: false
      levenshtein:
        title: Levenshtein
        description: Levenshtein distance from domain score to match
        type: number
        required: false
    output:
      score:
        title: Score
        description: Phishing score
        type: number
        required: false
      domain:
        title: Domain
        description: Matched domain
        type: string
        required: false
actions:
  check_for_squatters:
    title: Check for Squatters
    description: Look for potential typo squatters
    input:
      domain:
        description: Domain to check
        type: string
        default: google.com
        required: true
      flag:
        title: Flag
        description: Flag to pass for dnstwist (Advanced)
        type: string
        required: false
    output:
      potential_squatters:
        title: Potential Squatters
        description: JSON representation of potential squatters
        type: '[]object'
        required: false
  score_domain:
    title: Score Domain
    description: 'Get phishing score for domain. score > 90: Very Suspicous, > 65
      likely phising'
    input:
      domain:
        title: Domain
        description: Domain to check
        type: string
        default: google.com
        required: true
    output:
      score:
        title: Score
        description: Phishing score
        type: number
        required: false
