# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
from setuptools import setup, find_packages

setup(
    name="endoflife_ai-endoflife_ai-plugin",
    version="1.0.0",
    description="[endoflife.ai](https://endoflife.ai) provides end-of-life dates, support status and EOL Risk Scores for 500+ software products. This plugin uses the [endoflife.ai API](https://endoflife.ai/api) to enrich assets, findings and tickets with lifecycle data for triage",
    author="endoflife_ai",
    author_email="",
    url="",
    packages=find_packages(),
    install_requires=["insightconnect-plugin-runtime"],  # Add third-party dependencies to requirements.txt, not here!
    entry_points={"console_scripts": ["icon_endoflife_ai = bin.icon_endoflife_ai:main"]},
)
