class AvailableInputs:
    DomainFields = "analystNotes,counts,enterpriseLists,entity,intelCard,metrics,relatedEntities,risk,sightings,threatLists,timestamps"
    HashFields = "analystNotes,counts,enterpriseLists,entity,hashAlgorithm,intelCard,metrics,relatedEntities,risk,sightings,threatLists,timestamps"
    IpFields = "analystNotes,counts,enterpriseLists,entity,intelCard,location,metrics,relatedEntities,risk,riskyCIDRIPs,sightings,threatLists,timestamps"
    MalwareFields = "analystNotes,counts,entity,intelCard,metrics,relatedEntities,sightings,timestamps"
    UrlFields = "analystNotes,counts,enterpriseLists,entity,metrics,relatedEntities,risk,sightings,timestamps"
    VulnerabilityFields = "analystNotes,commonNames,cpe,cvss,cvssv3,entity,intelCard,metrics,nvdDescription,rawrisk,relatedEntities,relatedLinks,risk,timestamps"
    DomainRiskRuleMap = {
        "Historically Reported by Insikt Group": "analystNote",
        "Newly Registered Certificate With Potential for Abuse - DNS Sandwich": "certTyposquatSandwich",
        "Newly Registered Certificate With Potential for Abuse - Typo or Homograph": "certTyposquatTypo",
        "C&C Nameserver": "cncNameserver",
        "C&C DNS Name": "cncSite",
        "C&C URL": "cncUrl",
        "Compromised URL": "compromisedUrl",
        "Historical COVID-19-Related Domain Lure": "covidLure",
        "Recently Resolved to Host of Many DDNS Names": "ddns",
        "Historically Reported as a Defanged DNS Name": "defanged",
        "Historically Reported by DHS AIS": "dhsAis",
        "Recent Fast Flux DNS Name": "fastFlux",
        "Historically Reported Fraudulent Content": "fraudulentContent",
        "Historically Reported in Threat List": "historicalThreatListMembership",
        "Historically Linked to Cyber Attack": "linkedToCyberAttack",
        "Historical Malware Analysis DNS Name": "malwareAnalysis",
        "Historically Detected Malware Operation": "malwareSiteDetected",
        "Historically Detected Cryptocurrency Mining Techniques": "miningSiteDetected",
        "Blacklisted DNS Name": "multiBlacklist",
        "Historical Phishing Lure": "phishingLure",
        "Historically Detected Phishing Techniques": "phishingSiteDetected",
        "Active Phishing URL": "phishingUrl",
        "Recorded Future Predictive Risk Model": "predictionModelVerdict",
        "Historical Punycode Domain": "punycode",
        "Ransomware Distribution URL": "ransomwareDistribution",
        "Ransomware Payment DNS Name": "ransomwarePayment",
        "Recently Reported by Insikt Group": "recentAnalystNote",
        "Recent COVID-19-Related Domain Lure - Malicious": "recentCovidLure",
        "Recent COVID-19-Related Domain Lure - Suspicious": "recentCovidSpam",
        "Recently Reported as a Defanged DNS Name": "recentDefanged",
        "Recently Reported by DHS AIS": "recentDhsAis",
        "Recently Reported Fraudulent Content": "recentFraudulentContent",
        "Recently Linked to Cyber Attack": "recentLinkedToCyberAttack",
        "Recent Malware Analysis DNS Name": "recentMalwareAnalysis",
        "Recently Detected Malware Operation": "recentMalwareSiteDetected",
        "Recently Detected Cryptocurrency Mining Techniques": "recentMiningSiteDetected",
        "Recent Phishing Lure: Malicious": "recentPhishingLureMalicious",
        "Recent Phishing Lure: Suspicious": "recentPhishingLureSuspicious",
        "Recently Detected Phishing Techniques": "recentPhishingSiteDetected",
        "Recent Punycode Domain": "recentPunycode",
        "Recently Referenced by Insikt Group": "recentRelatedNote",
        "Recently Reported Spam or Unwanted Content": "recentSpamSiteDetected",
        "URL Recently Linked to Suspicious Content": "recentSuspiciousContent",
        "Recent Threat Researcher": "recentThreatResearcher",
        "Recent Typosquat Similarity - DNS Sandwich": "recentTyposquatSandwich",
        "Recent Typosquat Similarity - Typo or Homograph": "recentTyposquatTypo",
        "Recently Active Weaponized Domain": "recentWeaponizedDomain",
        "Recently Defaced Site": "recentlyDefaced",
        "Historically Referenced by Insikt Group": "relatedNote",
        "Recently Resolved to Malicious IP": "resolvedMaliciousIp",
        "Recently Resolved to Suspicious IP": "resolvedSuspiciousIp",
        "Recently Resolved to Unusual IP": "resolvedUnusualIp",
        "Recently Resolved to Very Malicious IP": "resolvedVeryMaliciousIp",
        "Trending in Recorded Future Analyst Community": "rfTrending",
        "Historically Reported Spam or Unwanted Content": "spamSiteDetected",
        "URL Historically Linked to Suspicious Content": "suspiciousContent",
        "Historical Threat Researcher": "threatResearcher",
        "Historical Typosquat Similarity - DNS Sandwich": "typosquatSandwich",
        "Historical Typosquat Similarity - Typo or Homograph": "typosquatTypo",
        "Historically Active Weaponized Domain": "weaponizedDomain",
    }
    HashRiskRuleMap = {
        "Historically Reported in Threat List": "historicalThreatListMembership",
        "Large": "large",
        "Linked to Attack Vector": "linkedToVector",
        "Linked to Cyber Attack": "linkedToCyberAttack",
        "Linked to Malware": "linkedToMalware",
        "Linked to Vulnerability": "linkedToVuln",
        "Malware SSL Certificate Fingerprint": "malwareSsl",
        "Observed in Underground Virus Testing Sites": "observedMalwareTesting",
        "Positive Malware Verdict": "positiveMalwareVerdict",
        "Recently Active Targeting Vulnerabilities in the Wild": "recentActiveMalware",
        "Referenced by Insikt Group": "relatedNote",
        "Reported by DHS AIS": "dhsAis",
        "Reported by Insikt Group": "analystNote",
        "Threat Researcher": "threatResearcher",
        "Trending in Recorded Future Analyst Community": "rfTrending",
    }
    IpRiskRuleMap = {
        "Threat Actor Used Infrastructure": "actorInfrastructure",
        "Historically Reported by Insikt Group": "analystNote",
        "Inside Possible Bogus BGP Route": "bogusBgp",
        "Historical Botnet Traffic": "botnet",
        "Recently Communicating With C&C Server": "c2ExfiltrationVictim",
        "Nameserver for C&C Server": "cncNameserver",
        "Historical C&C Server": "cncServer",
        "Cyber Exploit Signal - Critical": "cyberSignalCritical",
        "Cyber Exploit Signal - Important": "cyberSignalHigh",
        "Cyber Exploit Signal - Medium": "cyberSignalMedium",
        "Recent Host of Many DDNS Names": "ddnsHost",
        "Historically Reported as a Defanged IP": "defanged",
        "Historically Reported by DHS AIS": "dhsAis",
        "Resolution of Fast Flux DNS Name": "fastFluxResolution",
        "Historically Reported in Threat List": "historicalThreatListMembership",
        "Historical Honeypot Sighting": "honeypot",
        "Large": "large",
        "Honeypot Host": "honeypotHost",
        "Recently Active C&C Server": "intermediateActiveCnc",
        "Recent C&C Server": "intermediateCncServer",
        "Historically Linked to Intrusion Method": "linkedIntrusion",
        "Historically Linked to APT": "linkedToAPT",
        "Historically Linked to Cyber Attack": "linkedToCyberAttack",
        "Malicious Packet Source": "maliciousPacketSource",
        "Malware Delivery": "malwareDelivery",
        "Historical Multicategory Blacklist": "multiBlacklist",
        "Historical Open Proxies": "openProxies",
        "Phishing Host": "phishingHost",
        "Historical Positive Malware Verdict": "positiveMalwareVerdict",
        "Recorded Future Predictive Risk Model": "predictionModelVerdict",
        "Actively Communicating C&C Server": "recentActiveCnc",
        "Recently Reported by Insikt Group": "recentAnalystNote",
        "Recent Botnet Traffic": "recentBotnet",
        "Current C&C Server": "recentCncServer",
        "Recently Reported as a Defanged IP": "recentDefanged",
        "Recently Reported by DHS AIS": "recentDhsAis",
        "Recent Honeypot Sighting": "recentHoneypot",
        "Recently Linked to Intrusion Method": "recentLinkedIntrusion",
        "Recently Linked to APT": "recentLinkedToAPT",
        "Recently Linked to Cyber Attack": "recentLinkedToCyberAttack",
        "Recent Multicategory Blacklist": "recentMultiBlacklist",
        "Recent Open Proxies": "recentOpenProxies",
        "Recent Positive Malware Verdict": "recentPositiveMalwareVerdict",
        "Recently Referenced by Insikt Group": "recentRelatedNote",
        "Recent Spam Source": "recentSpam",
        "Recent SSH/Dictionary Attacker": "recentSshDictAttacker",
        "Recent Bad SSL Association": "recentSsl",
        "Recent Threat Researcher": "recentThreatResearcher",
        "Recently Defaced Site": "recentlyDefaced",
        "Historically Referenced by Insikt Group": "relatedNote",
        "Trending in Recorded Future Analyst Community": "rfTrending",
        "Historical Spam Source": "spam",
        "Historical SSH/Dictionary Attacker": "sshDictAttacker",
        "Historical Bad SSL Association": "ssl",
        "Historical Threat Researcher": "threatResearcher",
        "Tor Node": "tor",
        "Unusual IP": "unusualIP",
        "Vulnerable Host": "vulnerableHost",
    }
    UrlRiskRuleMap = {
        "Historically Reported by Insikt Group": "analystNote",
        "C&amp;C URL": "cncUrl",
        "Compromised URL": "compromisedUrl",
        "Historically Reported as a Defanged URL": "defangedURL",
        "Historically Reported by DHS AIS": "dhsAis",
        "Historically Reported Fraudulent Content": "fraudulentContent",
        "Historically Reported in Threat List": "historicalThreatListMembership",
        "Large": "large",
        "Historically Detected Malicious Browser Exploits": "maliciousSiteDetected",
        "Historically Detected Malware Distribution": "malwareSiteDetected",
        "Historically Detected Cryptocurrency Mining Techniques": "miningSiteDetected",
        "Historically Detected Phishing Techniques": "phishingSiteDetected",
        "Active Phishing URL": "phishingUrl",
        "Positive Malware Verdict": "positiveMalwareVerdict",
        "Ransomware Distribution URL": "ransomwareDistribution",
        "Recently Reported by Insikt Group": "recentAnalystNote",
        "Recently Reported as a Defanged URL": "recentDefangedURL",
        "Recently Reported by DHS AIS": "recentDhsAis",
        "Recently Reported Fraudulent Content": "recentFraudulentContent",
        "Recently Detected Malicious Browser Exploits": "recentMaliciousSiteDetected",
        "Recently Detected Malware Distribution": "recentMalwareSiteDetected",
        "Recently Detected Cryptocurrency Mining Techniques": "recentMiningSiteDetected",
        "Recently Detected Phishing Techniques": "recentPhishingSiteDetected",
        "Recent Ransomware Distribution URL": "recentRansomwareDistribution",
        "Recently Referenced by Insikt Group": "recentRelatedNote",
        "Recently Reported Spam or Unwanted Content": "recentSpamSiteDetected",
        "Recently Detected Suspicious Content": "recentSuspiciousSiteDetected",
        "Recently Active URL on Weaponized Domain": "recentWeaponizedURL",
        "Historically Referenced by Insikt Group": "relatedNote",
        "Historically Reported Spam or Unwanted Content": "spamSiteDetected",
        "Historically Detected Suspicious Content": "suspiciousSiteDetected",
    }
    VulnerabilityRiskRuleMap = {
        "Historically Reported by Insikt Group": "analystNote",
        "Web Reporting Prior to CVSS Score": "awaitingCvssScore",
        "Cyber Exploit Signal - Critical": "cyberSignalCritical",
        "Cyber Exploit Signal - Important": "cyberSignalHigh",
        "Cyber Exploit Signal - Medium": "cyberSignalMedium",
        "Historical Suspected Exploit/Tool Development in the Wild": "exploitDev",
        "Historical Observed Exploit/Tool Development in the Wild": "historicExploitDev",
        "Historically Exploited in the Wild by Malware": "historicMalwareActivity",
        "Large": "large",
        "Linked to Historical Cyber Exploit": "linkedToCyberExploit",
        "Historically Linked to Exploit Kit": "linkedToExploitKit",
        "Historically Linked to Malware": "linkedToIntrusionMethod",
        "Historically Linked to Remote Access Trojan": "linkedToRAT",
        "Historically Linked to Ransomware": "linkedToRansomware",
        "Linked to Recent Cyber Exploit": "linkedToRecentCyberExploit",
        "Recently Linked to Exploit Kit": "linkedToRecentExploitKit",
        "Recently Linked to Malware": "linkedToRecentIntrusionMethod",
        "Recently Linked to Remote Access Trojan": "linkedToRecentRAT",
        "Recently Linked to Ransomware": "linkedToRecentRansomware",
        "Exploited in the Wild by Malware": "malwareActivity",
        "NIST Severity - Critical": "nistCritical",
        "Duplicate of Vulnerability in NVD": "nistDuplicate",
        "NIST Severity - High": "nistHigh",
        "NIST Severity - Low": "nistLow",
        "NIST Severity - Medium": "nistMedium",
        "Web Reporting Prior to NVD Disclosure": "noCvssScore",
        "Historical Unverified Proof of Concept Available": "pocUnverified",
        "Historical Verified Proof of Concept Available": "pocVerified",
        "Historical Verified Proof of Concept Available Using Remote Execution": "pocVerifiedRemote",
        "Recently Reported by Insikt Group": "recentAnalystNote",
        "Recent Suspected Exploit/Tool Development in the Wild": "recentExploitDev",
        "Exploited in the Wild by Recently Active Malware": "recentMalwareActivity",
        "Recent Unverified Proof of Concept Available": "recentPocUnverified",
        "Recent Verified Proof of Concept Available": "recentPocVerified",
        "Recent Verified Proof of Concept Available Using Remote Execution": "recentPocVerifiedRemote",
        "Recently Referenced by Insikt Group": "recentRelatedNote",
        "Recently Linked to Penetration Testing Tools": "recentScannerUptake",
        "Historically Referenced by Insikt Group": "relatedNote",
        "Historically Linked to Penetration Testing Tools": "scannerUptake",
    }
