SCAN_COMMAND = "scan"
GET_ITEM_COMMAND = "get_item"
INSERT_COMMAND = "put_item"
UPDATE_COMMAND = "update_item"
LIST_TABLES = "list_tables"
SERVICE_NAME = "dynamodb"
DEFAULT_REGION = "us-east-1"
AWS_NONE_VALUE = "NONE"
