types:
  metadata:
    asn:
      title: "Asn"
      type: string
      description: "Asn"
      required: false
    category:
      title: "Category"
      type: string
      description: "Category"
      required: false
    city:
      title: "City"
      type: string
      description: "City"
      required: false
    country:
      title: "Country"
      type: string
      description: "Country"
      required: false
    country_code:
      title: "Country Code"
      type: string
      description: "Country code"
      required: false
    organization:
      title: "Organization"
      type: string
      description: "Organization"
      required: false
    os:
      title: "Os"
      type: string
      description: "Os"
      required: false
    rdns:
      title: "Rdns"
      type: string
      description: "Rdns"
      required: false
    region:
      title: "Region"
      type: string
      description: "Region"
      required: false
    tor:
      title: "Tor"
      type: boolean
      description: "Tor"
      required: false
  scan:
    port:
      title: "Port"
      type: integer
      description: "Port"
      required: false
    protocol:
      title: "Protocol"
      type: string
      description: "Protocol"
      required: false
  raw_data:
    hassh:
      title: "Hassh"
      type: []object
      description: "Hassh"
      required: false
    ja3:
      title: "Ja3"
      type: []object
      description: "Ja3"
      required: false
    scan:
      title: "Scan"
      type: "[]scan"
      description: "Scan"
      required: false
    web:
      title: "Web"
      type: object
      description: "Web"
      required: false
  

output:
  ip:
      title: "Ip"
      type: string
      description: "Ip"
      required: false
  first_seen:
      title: "First Seen"
      type: string
      description: "First seen"
      required: false
  last_seen:
      title: "Last Seen"
      type: string
      description: "Last seen"
      required: false
  seen:
      title: "Seen"
      type: boolean
      description: "Seen"
      required: false
  tags:
      title: "Tags"
      type: "[]string"
      description: "Tags"
      required: false
  actor:
      title: "Actor"
      type: string
      description: "Actor"
      required: false
  spoofable:
      title: "Spoofable"
      type: boolean
      description: "Spoofable"
      required: false
  classification:
      title: "Classification"
      type: string
      description: "Classification"
      required: false
  cve:
      title: "Cve"
      type: "[]string"
      description: "Cve"
      required: false
  bot:
      title: "Bot"
      type: boolean
      description: "Bot"
      required: false
  vpn:
      title: "Vpn"
      type: boolean
      description: "Vpn"
      required: false
  vpn_service:
      title: "Vpn Service"
      type: string
      description: "Vpn service"
      required: false
  metadata:
      title: "Metadata"
      type: metadata
      description: "Metadata"
      required: false
  raw_data:
      title: "Raw Data"
      type: raw_data
      description: "Raw data"
      required: false
  
