# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Component:
    DESCRIPTION = "Run a message trace"


class Input:
    SENDER_ADDRESS = "Sender_address"
    END_DATE = "end_date"
    START_DATE = "start_date"
    

class Output:
    MESSAGE_TRACES = "message_traces"
    

class MessageTraceInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "Sender_address": {
      "type": "string",
      "title": "Sender Address",
      "description": "Sender address",
      "order": 1
    },
    "end_date": {
      "type": "string",
      "title": "End Date",
      "description": "End date in format MM/DD/YYYY e.g. 09/27/2019",
      "order": 3
    },
    "start_date": {
      "type": "string",
      "title": "Start Date",
      "description": "Start date in format MM/DD/YYYY e.g. 09/27/2019",
      "order": 2
    }
  },
  "required": [
    "Sender_address",
    "end_date",
    "start_date"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class MessageTraceOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "message_traces": {
      "type": "array",
      "title": "Message Traces",
      "description": "Message Trace results",
      "items": {
        "$ref": "#/definitions/message_trace"
      },
      "order": 1
    }
  },
  "required": [
    "message_traces"
  ],
  "definitions": {
    "message_trace": {
      "type": "object",
      "title": "message_trace",
      "properties": {
        "MessageId": {
          "type": "string",
          "title": "Message ID",
          "description": "ID of found email",
          "order": 2
        },
        "Organization": {
          "type": "string",
          "title": "Organization",
          "description": "Organization that message trace was run on",
          "order": 1
        },
        "Received": {
          "type": "string",
          "title": "Received Date",
          "description": "Date email was received",
          "order": 3
        },
        "RecipientAddress": {
          "type": "string",
          "title": "Recipient Address",
          "description": "Recipient address",
          "order": 4
        },
        "SenderAddress": {
          "type": "string",
          "title": "Sender Address",
          "description": "Sender address",
          "order": 6
        },
        "Subject": {
          "type": "string",
          "title": "Subject",
          "description": "Subject",
          "order": 5
        }
      },
      "required": [
        "MessageId",
        "Organization",
        "Received",
        "RecipientAddress",
        "SenderAddress",
        "Subject"
      ]
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
