# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Retrieve a list of software updates"


class Input:
    MACHINE = "machine"


class Output:
    UPDATES = "updates"


class GetMissingSoftwareUpdatesInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(
        r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "machine": {
      "type": "string",
      "title": "Machine",
      "description": "Machine IP address, hostname or machine ID",
      "order": 1
    }
  },
  "required": [
    "machine"
  ],
  "definitions": {}
}
    """
    )

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetMissingSoftwareUpdatesOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(
        r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "updates": {
      "type": "array",
      "title": "Updates",
      "description": "List of updates",
      "items": {
        "$ref": "#/definitions/update"
      },
      "order": 1
    }
  },
  "required": [
    "updates"
  ],
  "definitions": {
    "update": {
      "type": "object",
      "title": "update",
      "properties": {
        "id": {
          "type": "string",
          "title": "ID",
          "description": "Update ID",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Update name",
          "order": 2
        },
        "osBuild": {
          "type": "integer",
          "title": "OS Build",
          "description": "Update OS build",
          "order": 3
        },
        "productsNames": {
          "type": "array",
          "title": "Products Names",
          "description": "Update products names",
          "items": {
            "type": "string"
          },
          "order": 4
        },
        "url": {
          "type": "string",
          "title": "URL",
          "description": "Update URL",
          "order": 5
        },
        "machineMissedOn": {
          "type": "integer",
          "title": "Machine Missed On",
          "description": "Update machine missed on",
          "order": 6
        },
        "cveAddressed": {
          "type": "integer",
          "title": "CVE Addressed",
          "description": "Update CVE addressed",
          "order": 7
        }
      }
    }
  }
}
    """
    )

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
