# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
from setuptools import setup, find_packages


setup(
    name="abuseipdb-rapid7-plugin",
    version="5.1.1",
    description="[AbuseIPDB](https://www.abuseipdb.com) is a database of reported malicious IP addresses that are involved in malicious activity such as spamming, hack attempts, DDoS attacks, etc.This plugin utilizes the [AbuseIPDB API v2](https://docs.abuseipdb.com) to lookup and report malicious IP addresses",
    author="rapid7",
    author_email="",
    url="",
    packages=find_packages(),
    install_requires=["insightconnect-plugin-runtime"],  # Add third-party dependencies to requirements.txt, not here!
    entry_points={"console_scripts": ["komand_abuseipdb = bin.komand_abuseipdb:main"]},
)
