{
  "device": {
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#deviceManagement/managedDevices/$entity",
    "id": "9e8fd111-6c41-1111-85b9-11395662e111",
    "user_id": "ac222ffe-222a-22a1-bbf2-e2222457e464b",
    "device_name": "INTUNE-W10-C",
    "managed_device_owner_type": "personal",
    "enrolled_date_time": "2021-06-24T00:37:04.5885438Z",
    "last_sync_date_time": "2023-08-23T09:05:10.1997623Z",
    "operating_system": "Windows",
    "compliance_state": "compliant",
    "jail_broken": "Unknown",
    "management_agent": "mdm",
    "os_version": "10.0.19044.3084",
    "eas_activated": true,
    "eas_device_id": "FD80418A34D04B5820E08E82604E1111",
    "eas_activation_date_time": "2021-06-24T08:37:10.2303995Z",
    "azure_ad_registered": true,
    "device_enrollment_type": "userEnrollment",
    "email_address": "user@example.com",
    "azure_ad_device_id": "a8dc01bc-1c11-337b-8d63-82f03f5cb111",
    "device_registration_state": "registered",
    "is_supervised": false,
    "exchange_last_successful_sync_date_time": "0001-01-01T00:00:00Z",
    "exchange_access_state": "none",
    "exchange_access_state_reason": "none",
    "is_encrypted": false,
    "user_principal_name": "user@example.com",
    "model": "VMware Virtual Platform",
    "manufacturer": "VMware, Inc.",
    "compliance_grace_period_expiration_date_time": "9999-12-31T23:59:59.9999999Z",
    "serial_number": "VMware-42146feae0gg8142-2839a7304825cc11",
    "user_display_name": "Example User",
    "total_storage_space_in_bytes": 33773584384,
    "free_storage_space_in_bytes": 1660944384,
    "partner_reported_threat_state": "unknown",
    "management_certificate_expiration_date": "2024-02-13T19:33:06Z",
    "ethernet_mac_address": "005056949D3E",
    "physical_memory_in_bytes": 0,
    "device_action_results": [
      {
        "action_name": "windowsDefenderUpdateSignatures",
        "action_state": "done",
        "start_date_time": "2022-04-26T13:19:45.3008934Z",
        "last_updated_date_time": "2022-04-26T13:25:27Z"
      },
      {
        "@odata.type": "#microsoft.graph.windowsDefenderScanActionResult",
        "action_name": "windowsDefenderScan",
        "action_state": "done",
        "start_date_time": "2023-08-23T08:20:27.9731659Z",
        "last_updated_date_time": "2023-08-23T09:04:07Z",
        "scan_type": "Full Scan"
      },
      {
        "@odata.type": "#microsoft.graph.windowsDefenderScanActionResult",
        "action_name": "windowsDefenderScan",
        "action_state": "done",
        "start_date_time": "2023-08-23T08:21:02.3882789Z",
        "last_updated_date_time": "2023-08-23T09:04:07Z",
        "scan_type": "Quick scan"
      }
    ]
  }
}
