# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Input:
    USER_ID = "user_id"
    

class Output:
    USER = "user"
    

class GetUserInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "user_id": {
      "type": "integer",
      "title": "User ID",
      "description": "Unique ID of the user eg. 123",
      "order": 1
    }
  },
  "required": [
    "user_id"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetUserOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "user": {
      "$ref": "#/definitions/single_user",
      "title": "User",
      "description": "Details of the requested user",
      "order": 1
    }
  },
  "definitions": {
    "single_user": {
      "type": "object",
      "title": "single_user",
      "properties": {
        "email": {
          "type": "string",
          "title": "Email",
          "order": 4
        },
        "isGrafanaAdmin": {
          "type": "boolean",
          "title": "IsGrafanaAdmin",
          "order": 5
        },
        "login": {
          "type": "string",
          "title": "Login",
          "order": 3
        },
        "name": {
          "type": "string",
          "title": "Name",
          "order": 2
        },
        "orgId": {
          "type": "integer",
          "title": "OrgId",
          "order": 1
        },
        "theme": {
          "type": "string",
          "title": "Theme",
          "order": 6
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
