plugin_spec_version: v2
extension: plugin
products: [insightconnect]
name: elastalert
title: ElastAlert
description: "ElastAlert provides easy & flexible alerting with Elasticsearch. Users of the ElastAlert plugin can
monitor alerts in real-time for automation use"
version: 1.0.1
vendor: rapid7
support: community
status: []
resources:
  source_url: https://github.com/rapid7/insightconnect-plugins/tree/master/elastalert
  license_url: https://github.com/rapid7/insightconnect-plugins/blob/master/LICENSE
  vendor_url: https://www.yelp.com
tags:
- elasticsearch
- elk
- alert
hub_tags:
  use_cases: [soar, alerting_and_notifications]
  keywords: [elasticsearch, elk, alert]
  features: []

connection:
  credentials:
    title: Basic Auth Username and Password
    description: Basic Auth username and password
    type: credential_username_password
    required: true
triggers:
  receive:
    title: Get Alerts
    description: Listen for and trigger on new alerts from an ElastAlert webhook
    input:
      tcp_port:
        type: integer
        title: TCP Port
        description: TCP port to listen for messages
        required: true
      endpoint:
        type: string
        title: Endpoint
        description: IP address of the Komand host to listen on. 0.0.0.0 to listen
          on the all address
        default: 0.0.0.0
        required: true
      interval:
        type: integer
        description: Interval to wait before reading another message
        default: 5
        required: false
    output:
      alert:
        title: Alert
        description: Alert
        type: object
        required: true
