plugin_spec_version: v2
name: syslog_listener
title: Syslog Listener
description: Syslog Listener
version: 1.2.2
vendor: rapid7
support: community
status: []
tags:
- syslog
- logs
enable_cache: false
triggers:
  listen:
    title: Listen for Syslog Messages
    description: Listen for syslog messages
    input:
      endpoint:
        type: string
        title: Endpoint
        description: IP address of the Komand host to listen on. 0.0.0.0 to listen
          on the all address
        default: 0.0.0.0
        required: true
      port:
        type: integer
        description: Syslog Port. Only one trigger can listen per port. Should be
          > 1024
        default: 5114
        required: true
      transport:
        type: string
        description: Protocol Transport
        enum:
        - TCP
        - UDP
        required: true
      facility:
        title: Facility
        description: Syslog Facility Filter
        type: string
        enum:
        - None
        - KERN
        - USER
        - MAIL
        - DAEMON
        - AUTH
        - SYSLOG
        - LPR
        - NEWS
        - UUCP
        - CRON
        - AUTHPRIV
        - FTP
        - LOCAL0
        - LOCAL1
        - LOCAL2
        - LOCAL3
        - LOCAL4
        - LOCAL5
        - LOCAL6
        - LOCAL7
        default: None
        required: false
      level:
        title: Level
        description: Syslog Level Filter
        type: string
        enum:
        - None
        - EMERG
        - ALERT
        - CRIT
        - ERR
        - WARNING
        - NOTICE
        - INFO
        - DEBUG
        default: None
        required: false
      filter:
        title: Message Filter
        description: Regex Message filter, e.g. '.*hello.*'
        type: string
        required: false
    output:
      msg:
        title: Message
        description: Syslog message
        type: string
        required: false
      facility:
        title: Facility
        description: Syslog Facility
        type: string
        enum:
        - KERN
        - USER
        - MAIL
        - DAEMON
        - AUTH
        - SYSLOG
        - LPR
        - NEWS
        - UUCP
        - CRON
        - AUTHPRIV
        - FTP
        - LOCAL0
        - LOCAL1
        - LOCAL2
        - LOCAL3
        - LOCAL4
        - LOCAL5
        - LOCAL6
        - LOCAL7
        required: false
      level:
        title: Level
        description: Syslog Level
        type: string
        enum:
        - EMERG
        - ALERT
        - CRIT
        - ERR
        - WARNING
        - NOTICE
        - INFO
        - DEBUG
        required: false
      host:
        title: Host
        description: Name or address where message originated from
        type: string
        required: false
      msgid:
        title: Message ID
        description: Message ID
        type: string
        required: false
      proc:
        title: Process Name
        description: Process name
        type: string
        required: false
