package actions

// Code generated by the Komand Go SDK Generator. DO NOT EDIT
import (
	"github.com/rapid7/komand-plugins/fullcontact/types"
)

// LookUpNameStatsInput is the input for LookUpNameStats
type LookUpNameStatsInput struct {
	FamilyName     string `json:"family_name"`
	GivenName      string `json:"given_name"`
	UnspecificName string `json:"unspecific_name"`
}

// LookUpNameStatsOutput is the output for LookUpNameStats
type LookUpNameStatsOutput struct {
	NameInfo types.Name `json:"name_info"`
}

// LookUpNameStatsAction is an action the plugin can take
type LookUpNameStatsAction struct{}
