LIST_ALL_AGENTS_ENDPOINT = "/agents"
LIST_ALL_GROUPS_ENDPOINT = "/groups"
TICKET_ENDPOINT = "/tickets/{ticket_id}"
TICKETS_ENDPOINT = "/tickets"
TICKET_TASK_ENDPOINT = "/tickets/{ticket_id}/tasks/{task_id}"
TICKET_TASKS_ENDPOINT = "/tickets/{ticket_id}/tasks"
SLA_POLICIES_ENDPOINT = "/sla_policies"
