package actions

// Code generated by the Komand Go SDK Generator. DO NOT EDIT

// PauseInput is the input for Pause
type PauseInput struct {
	Reference string `json:"reference"`
}

// PauseOutput is the output for Pause
type PauseOutput struct {
}

// PauseAction is an action the plugin can take
type PauseAction struct{}
