{
    "incident": {
        "acknowledgements": [],
        "alert_counts": {
            "all": 0,
            "resolved": 0,
            "triggered": 0
        },
        "assigned_via": "escalation_policy",
        "assignments": [],
        "created_at": "2023-10-13T10:53:01Z",
        "description": "The server is on fire.",
        "escalation_policy": {
            "html_url": "https://dev-rapid7.pagerduty.com/escalation_policies/PKEYM28",
            "id": "PKEYM28",
            "self": "https://api.pagerduty.com/escalation_policies/PKEYM28",
            "summary": "Default",
            "type": "escalation_policy_reference"
        },
        "first_trigger_log_entry": {
            "html_url": "https://dev-rapid7.pagerduty.com/incidents/Q0G4WBB4K4ILLM/log_entries/R8TRH580Z2TG8C3O5QZA15ID7X",
            "id": "R8TRH580Z2TG8C3O5QZA15ID7X",
            "self": "https://api.pagerduty.com/log_entries/R8TRH580Z2TG8C3O5QZA15ID7X",
            "summary": "Triggered through the website.",
            "type": "trigger_log_entry_reference"
        },
        "html_url": "https://dev-rapid7.pagerduty.com/incidents/Q0G4WBB4K4ILLM",
        "id": "Q0G4WBB4K4ILLM",
        "impacted_services": [
            {
                "html_url": "https://dev-rapid7.pagerduty.com/service-directory/PLPY09O",
                "id": "PLPY09O",
                "self": "https://api.pagerduty.com/services/PLPY09O",
                "summary": "new test service",
                "type": "service_reference"
            }
        ],
        "incident_key": "baf7cf21b1da41b4b0221008339ff361",
        "incident_number": 14,
        "incidents_responders": [],
        "is_mergeable": true,
        "last_status_change_at": "2023-10-13T10:53:30Z",
        "last_status_change_by": {
            "html_url": "https://dev-rapid7.pagerduty.com/users/PYGDZB8",
            "id": "PYGDZB8",
            "self": "https://api.pagerduty.com/users/PYGDZB8",
            "summary": "test user",
            "type": "user_reference"
        },
        "pending_actions": [],
        "priority": {
            "account_id": "P9IAY3D",
            "color": "a8171c",
            "created_at": "2023-09-20T11:32:06Z",
            "id": "PR0EVG8",
            "name": "P1",
            "order": 500000000,
            "schema_version": 0,
            "self": "https://api.pagerduty.com/priorities/PR0EVG8",
            "summary": "P1",
            "type": "priority",
            "updated_at": "2023-09-20T11:32:06Z"
        },
        "resolved_at": "2023-10-13T10:53:30Z",
        "responder_requests": [],
        "self": "https://api.pagerduty.com/incidents/Q0G4WBB4K4ILLM",
        "service": {
            "html_url": "https://dev-rapid7.pagerduty.com/service-directory/PLPY09O",
            "id": "PLPY09O",
            "self": "https://api.pagerduty.com/services/PLPY09O",
            "summary": "new test service",
            "type": "service_reference"
        },
        "status": "resolved",
        "subscriber_requests": [],
        "summary": "[#14] The server is on fire.",
        "teams": [],
        "title": "The server is on fire.",
        "type": "incident",
        "updated_at": "2023-10-13T10:53:30Z",
        "urgency": "high"
    }
}