# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
from setuptools import find_packages, setup

setup(
    name="luminar-cognyte-plugin",
    version="1.0.0",
    description="Fetch feeds from Luminar Taxii server",
    author="cognyte",
    author_email="",
    url="",
    packages=find_packages(),
    install_requires=[
        "insightconnect-plugin-runtime"
    ],  # Add third-party dependencies to requirements.txt, not here!
    entry_points={"console_scripts": ["icon_luminar = bin.icon_luminar:main"]},
)
