# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Obtain host details"


class Input:
    REF = "ref"


class Output:
    HOST = "host"


class GetHostInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "ref": {
      "type": "string",
      "title": "Ref",
      "description": "Object Reference of the host",
      "order": 1
    }
  },
  "required": [
    "ref"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetHostOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "host": {
      "$ref": "#/definitions/Host",
      "title": "Host",
      "description": "Host details",
      "order": 1
    }
  },
  "required": [
    "host"
  ],
  "definitions": {
    "Host": {
      "type": "object",
      "title": "Host",
      "properties": {
        "ref": {
          "type": "string",
          "title": "Ref",
          "description": "Object Reference of the host",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name of the new host",
          "order": 2
        },
        "ipv4addrs": {
          "type": "array",
          "title": "IPv4 Addresses",
          "description": "IP addresses associated with the new host",
          "items": {
            "$ref": "#/definitions/IPv4Addr"
          },
          "order": 3
        },
        "view": {
          "type": "string",
          "title": "View",
          "description": "The network view this host is associated with",
          "order": 4
        },
        "extattrs": {
          "type": "object",
          "title": "Extattrs",
          "description": "Extensible attributes",
          "order": 5
        },
        "aliases": {
          "type": "array",
          "title": "Aliases",
          "description": "Aliases associated with the host",
          "items": {
            "type": "string"
          },
          "order": 6
        }
      },
      "required": [
        "ipv4addrs",
        "name",
        "ref"
      ]
    },
    "IPv4Addr": {
      "type": "object",
      "title": "IPv4Addr",
      "properties": {
        "ipv4addr": {
          "type": "string",
          "title": "IPv4 Address",
          "description": "Either an IP address or a function (e.g. func:nextavailableip:10.1.1.0/24)",
          "order": 1
        },
        "mac": {
          "type": "string",
          "title": "MAC",
          "description": "MAC address",
          "order": 2
        },
        "configure_for_dhcp": {
          "type": "boolean",
          "title": "Configure for DHCP",
          "description": "Configure for DHCP flag",
          "order": 3
        },
        "host": {
          "type": "string",
          "title": "Host",
          "description": "The name of the host",
          "order": 4
        },
        "ref": {
          "type": "string",
          "title": "Ref",
          "description": "Object Reference of the IP address",
          "order": 5
        }
      },
      "required": [
        "ipv4addr",
        "ref"
      ]
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
