plugin_spec_version: v2
extension: plugin
products: [insightconnect]
name: darktrace
title: DarkTrace
version: 1.1.0
description: Automate the management of watched domains and alerting using the Darktrace plugin
vendor: rapid7
support: rapid7
status: []
resources:
  source_url: https://github.com/rapid7/insightconnect-plugins/tree/master/darktrace
  license_url: https://github.com/rapid7/insightconnect-plugins/blob/master/LICENSE
  vendor_url: https://www.darktrace.com/
tags:
- darktrace
- nta
- network
hub_tags:
  use_cases: [threat_detection_and_response]
  keywords: [darktrace, nta, network]
  features: []
types:
  actions:
    alert:
      title: Alert
      type: boolean
      description: Alert
      required: false
    antigena:
      title: Antigena
      type: object
      description: Antigena
      required: false
    breach:
      title: Breach
      type: boolean
      description: Breach
      required: false
    model:
      title: Model
      type: boolean
      description: Model
      required: false
    setPriority:
      title: Set Priority
      type: boolean
      description: Set priority
      required: false
    setTag:
      title: Settag
      type: boolean
      description: Settag
      required: false
    setType:
      title: Settype
      type: boolean
      description: Settype
      required: false
  activeTimes:
    devices:
      title: Devices
      type: object
      description: Devices
      required: false
    tags:
      title: Tags
      type: object
      description: Tags
      required: false
    type:
      title: Type
      type: string
      description: Type
      required: false
    version:
      title: Version
      type: integer
      description: Version
      required: false
  created:
    by:
      title: By
      type: string
      description: By
      required: false
  logic:
    data:
      title: Data
      type: "[]integer"
      description: Data
      required: false
    type:
      title: Type
      type: string
      description: Type
      required: false
    version:
      title: Version
      type: integer
      description: Version
      required: false
  now:
    actions:
      title: Actions
      type: actions
      description: Actions
      required: false
    active:
      title: Active
      type: boolean
      description: Active
      required: false
    activeTimes:
      title: Active Times
      type: activeTimes
      description: Active times
      required: false
    autoSuppress:
      title: Auto Suppress
      type: boolean
      description: Auto suppress
      required: false
    autoUpdatable:
      title: Auto Updatable
      type: boolean
      description: Auto updatable
      required: false
    autoUpdate:
      title: Autoupdate
      type: boolean
      description: Autoupdate
      required: false
    behaviour:
      title: Behaviour
      type: string
      description: Behaviour
      required: false
    created:
      title: Created
      type: created
      description: Created
      required: false
    defeats:
      title: Defeats
      type: "[]object"
      description: Defeats
      required: false
    description:
      title: Description
      type: string
      description: Description
      required: false
    edited:
      title: Edited
      type: created
      description: Edited
      required: false
    interval:
      title: Interval
      type: integer
      description: Interval
      required: false
    logic:
      title: Logic
      type: logic
      description: Logic
      required: false
    message:
      title: Message
      type: string
      description: Message
      required: false
    modified:
      title: Modified
      type: string
      description: Modified
      required: false
    name:
      title: Name
      type: string
      description: Name
      required: false
    phid:
      title: PHID
      type: integer
      description: Policy history ID
      required: false
    pid:
      title: PID
      type: integer
      description: Policy ID
      required: false
    priority:
      title: Priority
      type: integer
      description: Priority
      required: false
    sequenced:
      title: Sequenced
      type: boolean
      description: Sequenced
      required: false
    sharedEndpoints:
      title: Shared Endpoints
      type: boolean
      description: Shared endpoints
      required: false
    tags:
      title: Tags
      type: "[]object"
      description: Tags
      required: false
    throttle:
      title: Throttle
      type: integer
      description: Throttle
      required: false
    uuid:
      title: UUID
      type: string
      description: UUID
      required: false
    version:
      title: Version
      type: integer
      description: Version
      required: false
  then:
    actions:
      title: Actions
      type: actions
      description: Actions
      required: false
    active:
      title: Active
      type: boolean
      description: Active
      required: false
    activeTimes:
      title: Active Times
      type: activeTimes
      description: Active times
      required: false
    autoSuppress:
      title: Auto Suppress
      type: boolean
      description: Auto suppress
      required: false
    autoUpdatable:
      title: Auto Updatable
      type: boolean
      description: Auto updatable
      required: false
    autoUpdate:
      title: Auto Update
      type: boolean
      description: Auto update
      required: false
    behaviour:
      title: Behaviour
      type: string
      description: Behaviour
      required: false
    created:
      title: Created
      type: created
      description: Created
      required: false
    defeats:
      title: Defeats
      type: "[]object"
      description: Defeats
      required: false
    description:
      title: Description
      type: string
      description: Description
      required: false
    edited:
      title: Edited
      type: created
      description: Edited
      required: false
    interval:
      title: Interval
      type: integer
      description: Interval
      required: false
    logic:
      title: Logic
      type: logic
      description: Logic
      required: false
    modified:
      title: Modified
      type: string
      description: Modified
      required: false
    name:
      title: Name
      type: string
      description: Name
      required: false
    phid:
      title: PHID
      type: integer
      description: Policy history ID
      required: false
    pid:
      title: PID
      type: integer
      description: Policy ID
      required: false
    priority:
      title: Priority
      type: integer
      description: Priority
      required: false
    sequenced:
      title: Sequenced
      type: boolean
      description: Sequenced
      required: false
    sharedEndpoints:
      title: Sharedendpoints
      type: boolean
      description: Sharedendpoints
      required: false
    tags:
      title: Tags
      type: "[]object"
      description: Tags
      required: false
    throttle:
      title: Throttle
      type: integer
      description: Throttle
      required: false
    uuid:
      title: UUID
      type: string
      description: UUID
      required: false
    version:
      title: Version
      type: integer
      description: Version
      required: false
  model:
    now:
      title: Now
      type: now
      description: Now
      required: false
    then:
      title: Then
      type: then
      description: Then
      required: false
  data:
    left:
      title: Left
      type: string
      description: Left
      required: false
  logic_0:
    data:
      title: Data
      type: data
      description: Data
      required: false
    version:
      title: Version
      type: string
      description: Version
      required: false
  metric:
    label:
      title: Label
      type: string
      description: Label
      required: false
    mlid:
      title: MLID
      type: integer
      description: Metric logic ID
      required: false
    name:
      title: Name
      type: string
      description: Name
      required: false
  arguments:
    value:
      title: Value
      type: string
      description: Value
      required: false
  triggeredFilters:
    arguments:
      title: Arguments
      type: arguments
      description: Arguments
      required: false
    cfid:
      title: CFID
      type: integer
      description: Component filter ID
      required: false
    comparatorType:
      title: Comparator Type
      type: string
      description: Comparator type
      required: false
    filterType:
      title: Filter Type
      type: string
      description: Filter type
      required: false
    id:
      title: ID
      type: string
      description: Identifier
      required: false
    trigger:
      title: Trigger
      type: arguments
      description: Trigger
      required: false
  triggeredComponents:
    cbid:
      title: CBID
      type: integer
      description: Component breach ID
      required: false
    chid:
      title: CHID
      type: integer
      description: Component history ID
      required: false
    cid:
      title: CID
      type: integer
      description: Component ID
      required: false
    interval:
      title: Interval
      type: integer
      description: Interval
      required: false
    logic:
      title: Logic
      type: logic_0
      description: Logic
      required: false
    metric:
      title: Metric
      type: metric
      description: Metric
      required: false
    size:
      title: Size
      type: integer
      description: Size
      required: false
    threshold:
      title: Threshold
      type: integer
      description: Threshold
      required: false
    time:
      title: Time
      type: integer
      description: Time
      required: false
    triggeredFilters:
      title: Triggered Filters
      type: "[]triggeredFilters"
      description: Triggered filters
      required: false
  device:
    did:
      title: Did
      type: integer
      description: Did
      required: false


  trigger_result:
    creationTime:
        title: Creation Time
        type: integer
        description: Creation time
        required: false
    commentCount:
        title: Comment Count
        type: integer
        description: Comment count
        required: false
    pbid:
        title: PBID
        type: integer
        description: Policy breach ID
        required: false
    time:
        title: Time
        type: integer
        description: Time
        required: false
    model:
        title: Model
        type: model
        description: Model
        required: false
    triggeredComponents:
        title: Triggered Components
        type: "[]triggeredComponents"
        description: Triggered components
        required: false
    score:
        title: Score
        type: float
        description: Score
        required: false
    device:
        title: Device
        type: device
        description: Device
        required: false
connection:
  url:
    title: URL
    type: string
    description: API URL
    required: true
  api_public_token:
    title: API Public Token
    type: credential_secret_key
    description: Enter API public token
    required: true
    example: 1452d258-7c12-7c12-7c12-1452d25874c2
  api_private_token:
    title: API Private Token
    type: credential_secret_key
    description: Enter API private token
    required: true
    example: 1452d258-7c12-7c12-7c12-1452d25874c2
actions:
  update_watched_domains:
    title: Update Watched Domains
    description: Add or remove items from the Watched Domains list. If an indicator is added, DarkTrace will monitor network traffic for that URL and create alerts from it
    input:
      entry:
        title: Entry
        description: An external domain, hostname or IP address
        type: string
        required: true
        example: 192.168.10.10
      watched_domain_status:
        title: Watched Domain Status
        description: Determine whether item should be added or remove from the list. Set True to add, set false to remove
        type: boolean
        required: true
        example: true
      description:
        title: Description
        description: Description of the indicator
        type: string
        required: false
        default: Watched Domains managed by InsightConnect
        example: Watched Domains managed by InsightConnect
      source:
        title: Source
        description: Source of an indicator
        type: string
        required: false
        default: InsightConnect
        example: InsightConnect
      expiration_time:
        title: Expiration Time
        description: Expiration time of an indicator
        type: string
        required: false
        example: 2020-04-03 15:23:20
      hostname:
        title: Hostname
        description: Set to true to treat the added items as hostnames rather than domains
        type: boolean
        required: false
        example: true
    output:
      success:
        title: Success
        description: Success
        type: boolean
        required: true
      added:
        title: Added
        description: Added
        type: integer
        required: false
      updated:
        title: Updated
        description: Updated
        type: integer
        required: false
triggers:
  pull_alerts:
    title: Get Alerts
    description: Trigger workflows on model breach alerts and logs
    input:
      frequency:
        title: Frequency
        type: integer
        description: Poll frequency in seconds
        default: 300
        example: 300
        required: false
      did:
        title: DID
        type: integer
        description: ID of device modelled in the Darktrace system
        example: 1
        required: false
      minscore:
        title: Min Score
        type: integer
        description: Return only breaches with a minimum score
        example: 0
        required: false
      pbid:
        title: PBID
        type: integer
        description: Only return the model breach with the specified policy breach ID
        example: 300
        required: false
      pid:
        title: PID
        type: integer
        description: Only return model breaches for the specified model
        example: 300
        required: false
      uuid:
        title: UUID
        type: string
        description: Only return model breaches for the specified model
        example: fc707223-d2d2-475c-b09b-dec4e800eb2e
        required: false
    output:
      results:
        type: "[]trigger_result"
        title: Results
        description: Alerts results
        required: true
