# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Component:
    DESCRIPTION = "Get user information"


class Input:
    USER_ID = "user_id"
    

class Output:
    USER_INFORMATION = "user_information"
    

class GetUserInfoInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "user_id": {
      "type": "string",
      "title": "User ID",
      "description": "User ID e.g. bob@hotmail.com",
      "order": 1
    }
  },
  "required": [
    "user_id"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetUserInfoOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "user_information": {
      "$ref": "#/definitions/user_information",
      "title": "User Information",
      "description": "Information about a user",
      "order": 1
    }
  },
  "required": [
    "user_information"
  ],
  "definitions": {
    "user_information": {
      "type": "object",
      "title": "user_information",
      "properties": {
        "@odata.context": {
          "type": "string",
          "title": "@odata.Context",
          "description": "@odata.context",
          "order": 7
        },
        "accountEnabled": {
          "type": "boolean",
          "title": "Account Enabled",
          "description": "Account enabled",
          "order": 1
        },
        "businessPhones": {
          "type": "array",
          "title": "Business Phones",
          "description": "Business phones",
          "items": {
            "type": "string"
          },
          "order": 9
        },
        "displayName": {
          "type": "string",
          "title": "Display Name",
          "description": "Display name",
          "order": 2
        },
        "givenName": {
          "type": "string",
          "title": "Given Name",
          "description": "Given Name",
          "order": 12
        },
        "id": {
          "type": "string",
          "title": "ID",
          "description": "ID",
          "order": 13
        },
        "jobTitle": {
          "type": "string",
          "title": "Job Title",
          "description": "Job title",
          "order": 5
        },
        "mail": {
          "type": "string",
          "title": "Mail",
          "description": "Mail",
          "order": 10
        },
        "mobilePhone": {
          "type": "string",
          "title": "Mobile Phone",
          "description": "Mobile phone",
          "order": 3
        },
        "officeLocation": {
          "type": "string",
          "title": "Office Location",
          "description": "Office location",
          "order": 8
        },
        "preferredLanguage": {
          "type": "string",
          "title": "Preferred Language",
          "description": "Preferred language",
          "order": 4
        },
        "surname": {
          "type": "string",
          "title": "Surname",
          "description": "Surname",
          "order": 11
        },
        "userPrincipalName": {
          "type": "string",
          "title": "User Principal Name",
          "description": "User principal name",
          "order": 6
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
