{
  "asn": "3215",
  "asnCidr": "2.2.0.0/16",
  "ansCountryCode": "FR",
  "asnDate": "2010-07-12",
  "asnDescription": "France Telecom - Orange, FR",
  "ansRegistry": "ripencc",
  "handle": "2.0.0.0 - 2.15.255.255",
  "startAddress": "2.0.0.0",
  "endAddress": "2.15.255.255",
  "ipVersion": "v4",
  "name": "FR-TELECOM-20100712",
  "type": "ALLOCATED PA",
  "country": "FR",
  "parentHandle": "0.0.0.0 - 255.255.255.255",
  "entities": [
    {
      "roles": [
        "registrant"
      ],
      "handle": "FT-BRX"
    }
  ],
  "events": [
    {
      "eventAction": "last changed",
      "eventDate": "2017-04-10T14:16:37Z"
    }
  ],
  "port43": "whois.ripe.net"
}
