{
    "agent": {
        "id": "ac88c0ac243d35da0943wqewqe21312e12qxa35d4d65dee24",
        "platform": "linux",
        "host": {
            "vendor": "Ubuntu",
            "version": "18.04",
            "description": "Ubuntu Linux 18.04",
            "hostNames": [
                {
                    "name": "ivm-agent-ub18"
                },
                {
                    "name": "ivm-agent-ub18.vuln.lax.rapid7.com"
                }
            ],
            "primaryAddress": {
                "ip": "11.44.23.53",
                "mac": "01-51-53-44-A8-D1"
            },
            "uniqueIdentity": [
                {
                    "source": "Endpoint Agent",
                    "id": "ac88c0ac243d35da094335d4d65dee24eq3412edqwdqw"
                }
            ],
            "attributes": [
                {
                    "key": "cpuinfo",
                    "value": "Intel(R) Xeon(R) CPU E5-2697 v4 @ 2.30GHz"
                },
                {
                    "key": "timezone",
                    "value": "GMT-7"
                },
                {
                    "key": "release",
                    "value": "4.15.0-43-generic"
                },
                {
                    "key": "proxies",
                    "value": "{}"
                }
            ]
        },
        "agent_info": {
            "agentSemanticVersion": "3.1.5.14",
            "agentStatus": "ONLINE",
            "quarantineState": {
                "currentState": "UNQUARANTINED"
            }
        }
    }
}