{
    "agent": {
        "id": "a1cfb273EQWE12312EDSAXZc8e7d46a9e2a0e2dae01a0ce",
        "platform": "windows",
        "host": {
            "description": "Windows 10 10.0.19041  Multiprocessor Free",
            "hostNames": [
                {
                    "name": "ivm-agent-win"
                }
            ],
            "primaryAddress": {
                "ip": "12.43.13.43"
            }
        },
        "agent_info": {
            "agentSemanticVersion": "3.1.4.52",
            "agentStatus": "STALE",
            "quarantineState": {
                "currentState": "QUARANTINED"
            }
        }
    }
}