plugin_spec_version: v2
name: slack
title: Slack
description: Slack integrations
version: 2.0.1
vendor: rapid7
support: community
status: []
tags:
- slack
- chat
connection:
  token:
    type: password
    description: Authentication token
    required: true
    title: Token
types:
  file_reference:
    id:
      type: string
    name:
      type: string
    title:
      type: string
    is_external:
      type: boolean
    permalink:
      type: string
    permalink_public:
      type: string
  message:
    user:
      type: string
      description: User name
    user_id:
      type: string
      description: Slack User ID
    channel:
      type: string
      description: channel name
    channel_id:
      type: string
      description: Slack channel ID
    text:
      type: string
      description: Text
    ts:
      type: string
      description: Timestamp
triggers:
  message:
    title: New Message
    description: Trigger on message
    input:
      match_user:
        title: Match User
        type: string
        description: 'Regex match on username sending the message. Otherwise: listen
          for any private message'
        required: false
      match_channel:
        type: string
        description: 'Regex match on channel. Otherwise: listen on any channel'
        required: false
        title: Match Channel
      match_text:
        type: string
        description: Regex match on message content e.g. hi or .*hi.* matches `john
          says hi` in the message text
        required: false
        title: Match Text
      type:
        title: Type
        type: string
        description: Trigger on direct messages, group chats, or any
        enum:
        - any
        - direct
        - group
        default: any
        required: true
    output:
      message:
        type: message
        description: Message
        required: false
        title: Message
      type:
        type: string
        description: Message Type
        required: false
        title: Type
      timestamp:
        type: string
        description: Timestamp
        required: false
        title: Timestamp
  event:
    title: Slack Event
    description: Trigger on event
    input:
      subtype:
        title: Subtype
        type: string
        description: Event subtype to monitor
        enum:
        - bot_message
        - channel_archive
        - channel_join
        - channel_leave
        - channel_name
        - channel_purpose
        - channel_topic
        - channel_unarchive
        - file_comment
        - file_mention
        - file_share
        - group_archive
        - group_join
        - group_leave
        - group_name
        - group_purpose
        - group_topic
        - group_unarchive
        - me_message
        - message_changed
        - message_deleted
        - pinned_item
        - unpinned_item
        required: true
    output:
      event:
        type: object
        description: Event
        required: false
        title: Event
      timestamp:
        type: string
        description: Timestamp
        required: false
        title: Timestamp
  message_with_file:
    title: New Message With File
    description: Trigger on a message with a file attachment
    input:
      match_text:
        type: string
        description: Regexp match on message text
        required: false
        title: Match Text
      match_filename:
        type: string
        description: Regexp match on a specific filename
        required: false
        title: Match Filename
    output:
      message:
        type: object
        description: Message
        required: false
        title: Message
      type:
        type: string
        description: Message type
        required: false
        title: Type
      timestamp:
        description: Timestamp
        type: string
        required: false
        title: Timestamp
      file:
        type: file
        description: File
        required: false
        title: File
actions:
  upload_snippet:
    description: Upload a snippet to Slack
    input:
      title:
        type: string
        description: Title of Snippet
        required: false
        title: Title
      filetype:
        type: string
        description: File type
        required: false
        title: Filetype
      filename:
        type: string
        description: File name
        required: false
        title: Filename
      content:
        type: string
        description: Snippet text
        required: true
        title: Content
      channels:
        type: string
        description: Channels which the file should be shared to (comma-separated)
        required: false
        title: Channels
    output:
      file:
        type: file_reference
        required: false
        title: File
        description: File
  upload_file:
    description: Upload a file to Slack
    input:
      title:
        type: string
        description: Title of Attachment
        required: false
        title: Titlee
      filename:
        type: string
        description: File name
        required: false
        title: Filename
      content:
        type: bytes
        description: File content (base64 encoded)
        required: false
        title: Content
      channels:
        type: string
        description: Channels which the file should be shared to (comma-separated)
        required: false
        title: Channels
    output:
      file:
        type: file_reference
        required: false
        title: File
        description: File
  post_message:
    description: Post a message to the Slack channel
    input:
      message:
        type: string
        description: Message to send
        required: false
        title: Message
      username:
        type: string
        description: Username to post to. Username, channel, or channel id must be
          specified
        required: false
        title: Username
      channel:
        type: string
        description: 'Channel name to post to (e.g. #dev)'
        required: false
        title: Channel
      channel_id:
        type: string
        description: Channel ID to post to (will ignore username/channel if specified)
        required: false
        title: Channel ID
      icon_emoji:
        type: string
        description: Icon to use when posting
        required: false
        title: Icon Emoji
      attachments:
        type: '[]object'
        description: JSON array of attachments - see https://api.slack.com/docs/message-attachments
          (Advanced)
        required: false
        title: Attachments
    output:
      message_id:
        type: string
        description: MessageID of successful message
        required: false
        title: Message ID
      timestamp:
        type: string
        description: Timestamp of sucessful message
        required: false
        title: Timestamp
  search:
    title: Search messages
    description: Search message archive
    output:
      matches:
        type: '[]object'
        required: false
        title: Matches
        description: Matches found
      count:
        type: integer
        required: false
        title: Count
        description: Count
      total:
        type: integer
        required: false
        title: Total
        description: Total
      page:
        type: integer
        required: false
        title: Page
        description: Page
      pages:
        type: integer
        required: false
        title: Pages
        description: Pages
    input:
      count:
        default: 100
        required: false
        type: integer
        title: Count
        description: Count
      highlight:
        required: false
        type: boolean
        title: Highlight
        description: Highlight
      page:
        default: 1
        required: false
        type: integer
        title: Page
        description: Page
      query:
        required: true
        type: string
        title: Query
        description: Search query
      sort:
        default: score
        required: false
        type: string
        title: Sort
        description: Sort
      sort_dir:
        default: desc
        required: false
        type: string
        title: Sort Dir
        description: Sort dir
  disable:
    title: Disable User
    description: Disable user with specific email address (Slack Plus Only)
    input:
      email:
        type: string
        required: true
        title: Email
        description: Email
    output:
      success:
        type: boolean
        required: true
        title: Success
        description: Success
  enable:
    title: Enable User
    description: Enable user with specific email address (Slack Plus Only)
    input:
      email:
        type: string
        required: true
        title: Email
        description: Email
    output:
      success:
        type: boolean
        required: true
        title: Success
        description: Success
