{
  "generated": "2021-06-27T19:58:04.283Z",
  "reports": [
    {
      "scope": "THREAT",
      "id": "blacklisted_as_integer",
      "name": "example.com",
      "threatStatus": "active",
      "forensics": [
        {
          "display": "Attachment with SHA-256: 30f800f97aeaa8d62bdf3a6fb2b0681179a360c12e127f07038f8521461e5050",
          "engine": "av",
          "malicious": true,
          "note": "Attachment with SHA-256: 30f800f97aeaa8d62bdf3a6fb2b0681179a360c12e127f07038f8521461e5050",
          "platforms": [
            {
              "name": "pps",
              "os": "pps"
            }
          ],
          "type": "attachment",
          "what": {
            "blacklisted": true,
            "rule": "Av",
            "sha256": "30f800f97aeaa8d62bdf3a6fb2b0681179a360c12e127f07038f8521461e5050"
          }
        }
      ]
    }
  ]
}
