{
  "generated": "2021-06-27T19:58:04.283Z",
  "reports": [
    {
      "scope": "CAMPAIGN",
      "id": "9de5069c-5afe-602b-2ea0-a04b66beb2c0",
      "name": "Emotet",
      "forensics": [
        {
          "type": "behavior",
          "display": "Test",
          "engine": "iee",
          "malicious": false,
          "note": "Test2",
          "time": 0,
          "what": {
            "rule": "behavior_123456789"
          },
          "platforms": [
            {
              "name": "Win10",
              "os": "win",
              "version": "win10"
            }
          ]
        }
      ]
    }
  ]
}
