{
  "results": {
    "messagesBlocked": [
      {
        "threatsInfoMap": [
          {
            "threat": "Example Threat",
            "threatID": "d22be456cbc0a0e5d900696c36c92c547bea13cc76d32b63ed...",
            "threatStatus": "cleared",
            "threatTime": "2021-08-27T15:59:49.000Z",
            "threatType": "attachment",
            "threatUrl": "https://example.com",
            "classification": "phish"
          }
        ],
        "spamScore": 100,
        "toAddresses": [
          "user@example.com"
        ],
        "subject": "A phishy email",
        "fromAddress": [
          "user@example.com"
        ],
        "quarantineFolder": "Phish"
      }
    ],
    "queryEndTime": "2021-08-23T13:00:00Z"
  }
}
