{
  "results": {
    "clicksBlocked": [],
    "clicksPermitted": [],
    "messagesBlocked": [
      {
        "threatsInfoMap": [
          {
            "threat": "Example Threat",
            "threatID": "d22be456cbc0a0e5d900696c36c92c547bea13cc76d32b63ed...",
            "threatStatus": "active",
            "threatTime": "2021-08-27T15:59:49.000Z",
            "threatType": "attachment",
            "threatUrl": "https://example.com",
            "classification": "phish"
          }
        ],
        "spamScore": 100,
        "toAddresses": [
          "user@example.com"
        ],
        "subject": "Mail delivery failed: returning message to sender",
        "fromAddress": [
          "user@example.com"
        ],
        "quarantineFolder": "Phish"
      }
    ],
    "messagesDelivered": [],
    "queryEndTime": "2021-08-20T14:00:00Z"
  }
}
