format_dict = {
  "4CS": "4cs",
  "6502 ACME Cross Assembler": "6502acme",
  "6502 Kick Assembler": "6502kickass",
  "6502 TASM/64TASS": "6502tasm",
  "ABAP": "adap",
  "ActionScript": "actionscript",
  "ActionScript 3": "actionscript3",
  "Ada": "ada",
  "AIMMS": "aimms",
  "ALGOL 68": "algol68",
  "Apache Log": "apache",
  "AppleScript": "applescript",
  "APT Sources": "apt_sources",
  "ARM": "arm",
  "ASM (NASM)": "asm",
  "ASP": "asp",
  "Asymptote": "asymptote",
  "autoconf": "autoconf",
  "Autohotkey": "autohotkey",
  "Autolt": "autoit",
  "Avisynth": "avisynth",
  "Awk": "awk",
  "BASCOM AVR": "bascomavr",
  "Bash": "bash",
  "Basic4GL": "basic4gl",
  "Batch": "dos",
  "BibTeX": "bibtex",
  "Blitz Basic": "blitzbasic",
  "Blitz3D": "b3d",
  "BLitzMax": "bmx",
  "BNF": "bnf",
  "BOO": "boo",
  "Brainfuck": "bf",
  "C": "c",
  "C (WinAPI)": "c_winapi",
  "C for Macs": "c_mac",
  "C Intermediate Language": "cil",
  "C#": "csharp",
  "C++": "cpp",
  "C++ (WinAPI)": "cpp-winapi",
  "C++ (with Qt extensions)": "cpp-qt",
  "C: Loadrunner": "c_loadrunner",
  "CAD DCL": "caddcl",
  "CAD Lisp": "cadlisp",
  "CFDG": "cfdg",
  "ChaiScript": "chairscript",
  "Chapel": "chapel",
  "Clojre": "clojure",
  "Clone C": "klonec",
  "Clone C++": "klonecpp",
  "CMake": "cmake",
  "COBOL": "cobol",
  "CoffeeScript": "coffeescript",
  "ColdFusion": "cfm",
  "CSS": "css",
  "Cuesheet": "cuesheet",
  "D": "d",
  "Dart": "dart",
  "DCL": "dcl",
  "DCPU-16": "dcpu16",
  "DCS": "dcl",
  "Delphi": "delphi",
  "Delphi Prism (Oxygene)": "oxygene",
  "Diff": "diff",
  "DIV": "div",
  "DOT": "dot",
  "E": "e",
  "Easytrieve": "ezt",
  "ECMAScript": "ecmascript",
  "Eiffel": "eiffel",
  "Email": "email",
  "EPC": "epc",
  "Erlang": "erlang",
  "Euphoria": "euphoria",
  "F#": "fsharp",
  "Falcon": "falcon",
  "Filemaker": "filemaker",
  "FO Language": "fo",
  "Formula One": "f1",
  "Fortran": "fortran",
  "FreeBasic": "freebasic",
  "FreeSWITCH": "freeswitch",
  "GAMBAS": "gambas",
  "Game Maker": "gml",
  "GDB": "gdb",
  "Genero": "genero",
  "Genie": "genie",
  "GetText": "gettext",
  "Go": "go",
  "Groovy": "groovy",
  "GwBasic": "gwbasic",
  "Haskell": "haskell",
  "Haxe": "haxe",
  "HicEst": "hicest",
  "HQ9 Plus": "hq9plus",
  "HTML": "html4strict",
  "HTML 5": "html5",
  "Icon": "icon",
  "IDL": "idk",
  "INI file": "ini",
  "Inno Script": "inno",
  "INTERCAL": "intercal",
  "IO": "io",
  "ISPF Panel Definition": "ispfpanel",
  "J": "j",
  "Java": "java",
  "Java 5": "java5",
  "JavaScript": "javascript",
  "JCL": "jcl",
  "jQuery": "jquery",
  "JSON": "json",
  "Julia": "julia",
  "KiXtart": "kixtart",
  "Latex": "latex",
  "LDIF": "ldif",
  "Liberty BASIC": "lb",
  "Linden Scripting": "lsl2",
  "Lisp": "lisp",
  "LLVM": "llvm",
  "Loco Basic": "locobasic",
  "Logtalk": "logtalk",
  "LOL Code": "lolcode",
  "Lotus Formulas": "lotusformula",
  "Lotus Script": "lotusscript",
  "LScrpt": "lscript",
  "Lua": "lua",
  "M68000 Assembler": "m68k",
  "MagikSF": "magiksf",
  "Make": "make",
  "MapBasic": "mapbasic",
  "Markdown": "markdown",
  "MatLab": "matlab",
  "mIRC": "mirc",
  "MIX Assembler": "mmix",
  "Modula 2": "modula2",
  "Modula 3": "modula3",
  "Motorola 68000 HiSoft Dev": "68000devpac",
  "MPASM": "mpasm",
  "MXML": "mxml",
  "MySQL": "mysql",
  "Nagios": "naigos",
  "NetRexx": "netrexx",
  "newLISP": "newlisp",
  "Nginx": "nginx",
  "Nimrod": "nimrod",
  "None": "text",
  "NullSoft Installer": "nsis",
  "Oberon 2": "oberon2",
  "Objeck Programming Language": "objeck",
  "Objective C": "objc",
  "OCalm Brief": "ocaml-brief",
  "OCaml": "ocaml",
  "Octave": "octave",
  "Open Object Rexx": "oorexx",
  "OpenBSF PACKET FILTER": "pf",
  "OpenGL Shading": "glsl",
  "Openoffice BASIC": "oobas",
  "Oracle 11": "oracle11",
  "Oracle 8": "oracle8",
  "Oz": "oz",
  "ParaSail": "parasail",
  "PARI/GP": "parigp",
  "Pascal": "pascal",
  "Pawn": "pawn",
  "PCRE": "pcre",
  "Per": "per",
  "Perl": "perl",
  "Perl 6": "perl6",
  "PHP": "php",
  "PHP Brief": "php-brief",
  "Pic 16": "pic16",
  "Pike": "pike",
  "Pixel Bender": "pixelbender",
  "PL/I": "pli",
  "PL/SQL": "plsql",
  "PostgreSQL": "postgresql",
  "PostScript": "postscript",
  "POV-Ray": "povray",
  "Power Shell": "powershell",
  "PowerBuilder": "powerbuilder",
  "ProFTPd": "proftpd",
  "Progress": "progress",
  "Prolog": "prolog",
  "Properties": "properties",
  "ProvideX": "providex",
  "Puppet": "puppet",
  "PureBasic": "purebasic",
  "PyCon": "pycon",
  "Python": "python",
  "Python for S60": "pys60",
  "q/kdb+": "q",
  "QBasic": "qbasic",
  "QML": "qml",
  "R": "rsplus",
  "Racket": "racket",
  "Rails": "rails",
  "RBScript": "rbs",
  "REBOL": "rebol",
  "REG": "reg",
  "Rexx": "rexx",
  "Robots": "robots",
  "RPM Spec": "rpmspec",
  "Ruby": "ruby",
  "Ruby Gnuplot": "gnuplot",
  "Rust": "rust",
  "SAS": "sas",
  "Scala": "scala",
  "Scheme": "scheme",
  "Scilab": "scilab",
  "SCL": "scl",
  "SdlBasic": "sdlbasic",
  "Smalltalk": "smalltalk",
  "Smarty": "smarty",
  "SPARK": "spark",
  "SPARQL": "sparql",
  "SQF": "sqf",
  "SQL": "sql",
  "StandardML": "standardml",
  "StoneScript": "stonescript",
  "SuperCollider": "sclang",
  "Swift": "swift",
  "SystemVerilog": "systemverilog",
  "T-SQL": "tsql",
  "TCL": "tcl",
  "Tera Term": "teraterm",
  "text": "thinbasic",
  "thinBasic": "thinbasic",
  "TypoScript": "typoscript",
  "Unicon": "unicon",
  "UnrealScript": "uscript",
  "UPC": "upc",
  "Urbi": "urbi",
  "Vala": "vala",
  "VB.NET": "vbnet",
  "VBScript": "vbscript",
  "Vedit": "vedit",
  "VeriLog": "verilog",
  "VHDL": "vdhl",
  "VIM": "vim",
  "Visual Pro Log": "visualprolog",
  "VisualBasic": "vb",
  "VisualFoxPro": "visualfoxpro",
  "WhiteSpace": "whitespace",
  "WHOIS": "whois",
  "Winbatch": "winbatch",
  "XBasic": "xbasic",
  "XML": "xml",
  "Xorg Config": "xorg_conf",
  "XPP": "xpp",
  "YAML": "yaml",
  "Z80 Assembler": "z80",
  "ZXBasic": "zxbasic",
}

privacy_dict = {
  "private": "2",
  "unlisted": "1",
  "public": "0",
}

expire_dict = {
  "Never": "N",
  "10 Minutes": "10M",
  "1 Hour": "1H",
  "1 Day": "1D",
  "1 Week": "1W",
  "2 Weeks": "2W",
  "1 Month": "1M",
}
