{
  "user": {
    "id": "12345",
    "status": "PASSWORD_EXPIRED",
    "created": "2023-04-26T14:07:20.000Z",
    "activated": "2023-04-26T14:07:21.000Z",
    "statusChanged": "2023-04-26T14:07:21.000Z",
    "lastUpdated": "2023-04-26T14:07:21.000Z",
    "passwordChanged": "2023-04-26T14:07:21.000Z",
    "type": {
      "id": "12345"
    },
    "profile": {
      "firstName": "John",
      "lastName": "Doe",
      "login": "user_1@rapid7.com",
      "email": "user_1@rapid7.com"
    },
    "credentials": {
      "emails": [
        {
          "value": "user_1@rapid7.com",
          "status": "VERIFIED",
          "type": "PRIMARY"
        }
      ],
      "recoveryQuestion": {
        "question": "Question?"
      },
      "provider": {
        "type": "OKTA",
        "name": "OKTA"
      }
    },
    "links": {
      "suspend": {
        "href": "https://sample.com",
        "method": "POST"
      },
      "schema": {
        "href": "https://sample.com"
      },
      "resetPassword": {
        "href": "https://sample.com",
        "method": "POST"
      },
      "forgotPassword": {
        "href": "https://sample.com",
        "method": "POST"
      },
      "expirePassword": {
        "href": "https://sample.com",
        "method": "POST"
      },
      "changeRecoveryQuestion": {
        "href": "https://sample.com",
        "method": "POST"
      },
      "self": {
        "href": "https://sample.com"
      },
      "type": {
        "href": "https://sample.com"
      },
      "changePassword": {
        "href": "https://sample.com",
        "method": "POST"
      },
      "deactivate": {
        "href": "https://sample.com",
        "method": "POST"
      }
    }
  }
}
