package actions

// Code generated by the Komand Go SDK Generator. DO NOT EDIT

// MacExtractorInput is the input for MacExtractor
type MacExtractorInput struct {
	File []byte `json:"file"`
	Str  string `json:"str"`
}

// MacExtractorOutput is the output for MacExtractor
type MacExtractorOutput struct {
	MacAddrs []string `json:"mac_addrs"`
}

// MacExtractorAction is an action the plugin can take
type MacExtractorAction struct{}
