package actions

// Code generated by the Komand Go SDK Generator. DO NOT EDIT

// Sha1ExtractorInput is the input for Sha1Extractor
type Sha1ExtractorInput struct {
	File []byte `json:"file"`
	Str  string `json:"str"`
}

// Sha1ExtractorOutput is the output for Sha1Extractor
type Sha1ExtractorOutput struct {
	Sha1 []string `json:"sha1"`
}

// Sha1ExtractorAction is an action the plugin can take
type Sha1ExtractorAction struct{}
