{
    "organization": {
        "avatar_url": "https://avatars.githubusercontent.com/u/157362711?v=4",
        "events_url": "https://api.github.com/orgs/test_org/events",
        "hooks_url": "https://api.github.com/orgs/test_org/hooks",
        "id": 157362711,
        "issues_url": "https://api.github.com/orgs/test_org/issues",
        "login": "test_org",
        "members_url": "https://api.github.com/orgs/test_org/members{/member}",
        "node_id": "O_kgDOCWEqFw",
        "public_members_url": "https://api.github.com/orgs/test_org/public_members{/member}",
        "repos_url": "https://api.github.com/orgs/test_org/repos",
        "url": "https://api.github.com/orgs/test_org"
    },
    "organization_url": "https://api.github.com/orgs/test_org",
    "role": "member",
    "state": "pending",
    "url": "https://api.github.com/orgs/test_org/memberships/test_username",
    "user": {
        "avatar_url": "https://avatars.githubusercontent.com/u/144030336?v=4",
        "events_url": "https://api.github.com/users/test_username/events{/privacy}",
        "followers_url": "https://api.github.com/users/test_username/followers",
        "following_url": "https://api.github.com/users/test_username/following{/other_user}",
        "gists_url": "https://api.github.com/users/test_username/gists{/gist_id}",
        "html_url": "https://github.com/test_username",
        "id": 144030336,
        "login": "test_username",
        "node_id": "U_kgDOCJW6gA",
        "organizations_url": "https://api.github.com/users/test_username/orgs",
        "received_events_url": "https://api.github.com/users/test_username/received_events",
        "repos_url": "https://api.github.com/users/test_username/repos",
        "site_admin": false,
        "starred_url": "https://api.github.com/users/test_username/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/test_username/subscriptions",
        "type": "User",
        "url": "https://api.github.com/users/test_username"
    }
}