{
    "issues": [
        {
            "assignee": {
                "avatar_url": "https://avatars.githubusercontent.com/u/157107299?v=4",
                "events_url": "https://api.github.com/users/integrationalliance/events{/privacy}",
                "followers_url": "https://api.github.com/users/integrationalliance/followers",
                "following_url": "https://api.github.com/users/integrationalliance/following{/other_user}",
                "gists_url": "https://api.github.com/users/integrationalliance/gists{/gist_id}",
                "html_url": "https://github.com/integrationalliance",
                "id": 157107299,
                "login": "integrationalliance",
                "node_id": "U_kgDOCV1EYw",
                "organizations_url": "https://api.github.com/users/integrationalliance/orgs",
                "received_events_url": "https://api.github.com/users/integrationalliance/received_events",
                "repos_url": "https://api.github.com/users/integrationalliance/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/integrationalliance/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/integrationalliance/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/integrationalliance"
            },
            "assignees": [
                {
                    "avatar_url": "https://avatars.githubusercontent.com/u/157107299?v=4",
                    "events_url": "https://api.github.com/users/integrationalliance/events{/privacy}",
                    "followers_url": "https://api.github.com/users/integrationalliance/followers",
                    "following_url": "https://api.github.com/users/integrationalliance/following{/other_user}",
                    "gists_url": "https://api.github.com/users/integrationalliance/gists{/gist_id}",
                    "html_url": "https://github.com/integrationalliance",
                    "id": 157107299,
                    "login": "integrationalliance",
                    "node_id": "U_kgDOCV1EYw",
                    "organizations_url": "https://api.github.com/users/integrationalliance/orgs",
                    "received_events_url": "https://api.github.com/users/integrationalliance/received_events",
                    "repos_url": "https://api.github.com/users/integrationalliance/repos",
                    "site_admin": false,
                    "starred_url": "https://api.github.com/users/integrationalliance/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/integrationalliance/subscriptions",
                    "type": "User",
                    "url": "https://api.github.com/users/integrationalliance"
                }
            ],
            "author_association": "OWNER",
            "body": "This was created so we can see if issues are pulled in correctly",
            "comments": 0,
            "comments_url": "https://api.github.com/repos/integrationalliance/Test_new_repo/issues/1/comments",
            "created_at": "2024-01-22T09:42:18Z",
            "events_url": "https://api.github.com/repos/integrationalliance/Test_new_repo/issues/1/events",
            "html_url": "https://github.com/integrationalliance/Test_new_repo/issues/1",
            "id": 2093498528,
            "labels": [
                {
                    "color": "d73a4a",
                    "default": true,
                    "description": "Something isn't working",
                    "id": 6460729259,
                    "name": "bug",
                    "node_id": "LA_kwDOLH_fnc8AAAABgRbnqw",
                    "url": "https://api.github.com/repos/integrationalliance/Test_new_repo/labels/bug"
                },
                {
                    "color": "0075ca",
                    "default": true,
                    "description": "Improvements or additions to documentation",
                    "id": 6460729262,
                    "name": "documentation",
                    "node_id": "LA_kwDOLH_fnc8AAAABgRbnrg",
                    "url": "https://api.github.com/repos/integrationalliance/Test_new_repo/labels/documentation"
                },
                {
                    "color": "cfd3d7",
                    "default": true,
                    "description": "This issue or pull request already exists",
                    "id": 6460729265,
                    "name": "duplicate",
                    "node_id": "LA_kwDOLH_fnc8AAAABgRbnsQ",
                    "url": "https://api.github.com/repos/integrationalliance/Test_new_repo/labels/duplicate"
                }
            ],
            "labels_url": "https://api.github.com/repos/integrationalliance/Test_new_repo/issues/1/labels{/name}",
            "locked": false,
            "node_id": "I_kwDOLH_fnc58yECg",
            "number": 1,
            "reactions": {
                "+1": 0,
                "-1": 0,
                "confused": 0,
                "eyes": 0,
                "heart": 0,
                "hooray": 0,
                "laugh": 0,
                "rocket": 0,
                "total_count": 0,
                "url": "https://api.github.com/repos/integrationalliance/Test_new_repo/issues/1/reactions"
            },
            "repository_url": "https://api.github.com/repos/integrationalliance/Test_new_repo",
            "state": "open",
            "timeline_url": "https://api.github.com/repos/integrationalliance/Test_new_repo/issues/1/timeline",
            "title": "This is a test issue",
            "updated_at": "2024-01-22T09:42:19Z",
            "url": "https://api.github.com/repos/integrationalliance/Test_new_repo/issues/1",
            "user": {
                "avatar_url": "https://avatars.githubusercontent.com/u/157107299?v=4",
                "events_url": "https://api.github.com/users/integrationalliance/events{/privacy}",
                "followers_url": "https://api.github.com/users/integrationalliance/followers",
                "following_url": "https://api.github.com/users/integrationalliance/following{/other_user}",
                "gists_url": "https://api.github.com/users/integrationalliance/gists{/gist_id}",
                "html_url": "https://github.com/integrationalliance",
                "id": 157107299,
                "login": "integrationalliance",
                "node_id": "U_kgDOCV1EYw",
                "organizations_url": "https://api.github.com/users/integrationalliance/orgs",
                "received_events_url": "https://api.github.com/users/integrationalliance/received_events",
                "repos_url": "https://api.github.com/users/integrationalliance/repos",
                "site_admin": false,
                "starred_url": "https://api.github.com/users/integrationalliance/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/integrationalliance/subscriptions",
                "type": "User",
                "url": "https://api.github.com/users/integrationalliance"
            }
        }
    ]
}