# GENERATED BY KOMAND SDK - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Input:
    API_TOKEN = "api_token"
    REGION = "region"
    

class ConnectionSchema(insightconnect_plugin_runtime.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "api_token": {
      "$ref": "#/definitions/credential_secret_key",
      "title": "API Token",
      "description": "Orca Security API Token",
      "order": 2
    },
    "region": {
      "type": "string",
      "title": "Region",
      "description": "The region for Orca Security",
      "default": "US",
      "enum": [
        "US",
        "EU",
        "AU"
      ],
      "order": 1
    }
  },
  "required": [
    "api_token",
    "region"
  ],
  "definitions": {
    "credential_secret_key": {
      "id": "credential_secret_key",
      "type": "object",
      "title": "Credential: Secret Key",
      "description": "A shared secret key",
      "properties": {
        "secretKey": {
          "type": "string",
          "title": "Secret Key",
          "displayType": "password",
          "description": "The shared secret key",
          "format": "password"
        }
      },
      "required": [
        "secretKey"
      ]
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
