plugin_spec_version: v2
extension: plugin
products: [insightconnect]
name: passivetotal
title: PassiveTotal
description: Use PassiveTotal to analyze domains, addresses, and WHOIS data
version: 1.0.2
vendor: rapid7
support: community
status: []
resources:
  source_url: https://github.com/rapid7/insightconnect-plugins/tree/master/passivetotal
  license_url: https://github.com/rapid7/insightconnect-plugins/blob/master/LICENSE
  vendor_url: https://community.riskiq.com/
tags:
- passivetotal
- threat intelligence
hub_tags:
  use_cases: [threat_detection_and_response]
  keywords: [passivetotal, threat intelligence]
  features: []
connection:
  username:
    title: Username
    type: string
    description: Username
    required: true
  api_key:
    title: API Key
    description: API key for PassiveTotal
    type: credential_secret_key
    required: true
types:
  links:
    project:
      description: Link to project
      title: Project
      type: string
    self:
      description: Link to artifact
      title: Self
      type: string
    tag:
      description: Tag
      title: Tag
      type: string
  artifact:
    monitor:
      description: Monitor
      title: Monitor
      type: boolean
    user_tags:
      description: User assigned tag
      title: User Tags
      type: '[]string'
    creator:
      description: Person or organization who added this artifact
      title: Creator
      type: string
    system_tags:
      description: System assigned tag
      title: System Tags
      type: '[]string'
    created:
      description: Creation date
      title: Created
      type: string
    links:
      description: Web links to project and artifact
      title: Links
      type: links
    project:
      description: Project GUID
      title: Project
      type: string
    owner:
      description: Artifact owner
      title: Owner
      type: string
    monitorable:
      description: Artifact can be monitored
      title: Monitorable
      type: boolean
    organization:
      description: Organization
      title: Organization
      type: string
    tag_meta:
      description: Tag Meta
      title: Tag Meta
      type: object
    query:
      description: Query
      title: Query
      type: string
    guid:
      description: Artifact GUID
      title: GUID
      type: string
    type:
      description: Type of artifact eg. domain
      title: Type
      type: string
    tags:
      description: Tags
      title: Tags
      type: '[]string'
  address_record:
    network:
      description: Network subnet
      type: string
    autonomous_system_name:
      description: Autonomous System Name
      type: string
    country:
      description: Country Code
      type: string
    ever_compromised:
      description: True if ever compromised
      type: boolean
    sinkhole:
      description: True if sinkholed
      type: boolean
    latitude:
      dsecription: Latitude
      type: number
    longitude:
      dsecription: Longitude
      type: number
    autonomous_system_number:
      dsecription: Autonomous System Number
      type: integer
    tags:
      description: Tags
      type: '[]string'
  domain_record:
    ever_compromised:
      description: True if ever compromised
      type: boolean
    primary_domain:
      description: True if primary Domain
      type: string
    tags:
      description: Tags
      type: '[]string'
    subdomains:
      description: Subdomains
      type: '[]string'
    dynamic_dns:
      description: True if Dynamic DNS
      type: boolean
    tld:
      description: TLD
      type: string
  ssl_record:
    issuerStreetAddress:
      description: IssuerStreetAddress
      type: string
    subjectSerialNumber:
      description: SubjectSerialNumber
      type: string
    subjectEmailAddress:
      description: SubjectEmailAddress
      type: string
    expirationDate:
      description: ExpirationDate
      type: string
    issuerSerialNumber:
      description: IssuerSerialNumber
      type: string
    issuerOrganizationName:
      description: IssuerOrganization
      type: string
    subjectCommonName:
      description: SubjectCommonName
      type: string
    subjectSurname:
      description: SubjectSurname
      type: string
    subjectCountry:
      description: SubjectCountry
      type: string
    subjectGivenName:
      description: SubjectGivenName
      type: string
    issuerProvince:
      description: IssuerProvince
      type: string
    subjectLocalityName:
      description: SubjectLocalityName
      type: string
    issuerStateOrProvinceName:
      description: IssuerStateOrProvinceName
      type: string
    issuerCommonName:
      description: IssuerCommonName
      type: string
    issueDate:
      description: IssueDate
      type: string
    issuerEmailAddress:
      description: IssuerEmailAddress
      type: string
    subjectOrganizationUnitName:
      description: SubjectOrganizationUnitName
      type: string
    subjectOrganizationName:
      description: SubjectOrganizationName
      type: string
    fingerprint:
      description: Fingerprint
      type: string
    issuerLocalityName:
      description: IssuerLocalityName
      type: string
    issuerGivenName:
      description: IssuerGivenName
      type: string
    issuerCountry:
      description: IssuerCountry
      type: string
    subjectStateOrProvinceName:
      description: SubjectStateOrProvinceName
      type: string
    sha1:
      description: SHA1
      type: string
    sslVersion:
      description: SSL Version
      type: string
    issuerSurname:
      description: IssuerSurname
      type: string
    serialNumber:
      description: SerialNumber
      type: string
    subjectStreetAddress:
      description: SubjectStreetAddress
      type: string
    issuerOrganizationUnitName:
      description: IssuerOrganizationUnitName
      type: string
    subjectProvince:
      description: SubjectProvince
      type: string
  contact_record:
    city:
      description: City
      type: string
    country:
      description: Country
      type: string
    email:
      description: Email
      type: string
    name:
      description: Name
      type: string
    organization:
      description: Organization
      type: string
    postalCode:
      description: Postal code
      type: string
    state:
      description: State
      type: string
    street:
      description: Street
      type: string
    telephone:
      description: Telephone
      type: string
  whois_record:
    registryUpdatedAt:
      description: Last time the record was updated
      type: string
    domain:
      description: Domain associated with the record
      type: string
    billing:
      description: Billing details
      type: object
    zone:
      description: Zone details
      type: object
    nameServers:
      description: Nameservers for the record
      type: '[]string'
    registered:
      description: Registration date of the record
      type: string
    lastLoadedAt:
      description: Last processed by local servers
      type: string
    whoisServer:
      description: Location of the WHOIS server hoster
      type: string
    contactEmail:
      description: Contact email for the record
      type: string
    admin:
      description: Administrator contact details
      type: contact_record
    expiresAt:
      description: When the record details expire
      type: string
    registrar:
      description: Registrar associated with the record
      type: string
    tech:
      description: Technical contact details
      type: contact_record
    registrant:
      description: Registrant contact details
      type: contact_record
  whois_keyword_result:
    focusPoint:
      type: string
    matchType:
      type: string
    fieldMatch:
      type: string
triggers:
  project_updated:
    title: Project Updated
    description: Looks for updates to a project
    input:
      project_name:
        title: Project Name
        type: string
        description: The name of the project to retrieve artifacts from
        required: true
      frequency:
        title: Frequency
        type: integer
        description: The time between updates in seconds
        default: 300
        required: false
    output:
      updated_list:
        title: Updated List
        description: Results as list of JSON
        type: '[]artifact'
        required: false
actions:
  lookup_domains:
    title: Lookup Domains
    description: Lookup Domains
    input:
      domains:
        title: Domains
        type: '[]string'
        description: Domains
        required: true
    output:
      domain_records:
        title: Domain Records
        description: Domain Records
        type: '[]domain_record'
        required: false
      found_domains:
        title: Found Domains
        description: Domains found
        type: '[]string'
        required: false
  lookup_domain:
    title: Lookup Domain
    description: Lookup Domain
    input:
      domain:
        title: Domain
        type: string
        description: Domain, e.g. 4.2.2.2
        required: true
    output:
      domain_record:
        title: Domain Record
        description: Domain Record
        type: domain_record
        required: false
      found:
        title: Found
        type: boolean
        description: True if found
        required: false
  lookup_addresses:
    title: Lookup Addresses
    description: Lookup IP addresses
    input:
      addresses:
        title: Addresses
        type: '[]string'
        description: IP Addresses
        required: true
    output:
      found_addresses:
        title: Found Addresses
        description: IP Addresses Found
        type: '[]string'
        required: false
      address_records:
        title: Address Records
        description: IP Address Records
        type: '[]address_record'
        required: false
  lookup_address:
    title: Lookup Address
    description: Lookup IP address
    input:
      address:
        title: Address
        type: string
        description: IP Address, e.g. 4.2.2.2
        required: true
    output:
      address_record:
        title: Address Record
        description: IP Address Record
        type: address_record
        required: false
      found:
        title: Found
        type: boolean
        description: True if found
        required: false
  lookup_ssl:
    title: Lookup SSL
    description: Lookup SSL Certificate
    input:
      sha1:
        title: SHA1
        type: string
        description: SHA1 Certificate Hash
        required: true
    output:
      address_record:
        title: Address Records
        description: IP Address Record
        type: address_record
        required: false
      found:
        title: Found
        type: boolean
        description: True if found
        required: false
  history_ssl:
    title: History SSL
    description: Lookup SSL History
    input:
      query:
        title: Query
        type: string
        description: IP Address or SHA-1 Hash
        required: true
    output:
      results:
        title: Results
        description: Results as JSON
        type: '[]object'
        required: false
  get_subdomains:
    title: Get Subdomains
    description: Get subdomains https://api.passivetotal.org/api/docs/#api-Enrichment-GetV2EnrichmentSubdomains
    input:
      query:
        title: Query
        description: Input query, e.g. *.passivetotal.org
        type: string
        required: true
    output:
      count:
        title: Count
        description: Number of results returned
        type: integer
        required: false
      subdomains:
        title: Subdomains
        description: Subdomains returned, e.g [foo, bar, api]
        type: '[]string'
        required: false
  get_whois:
    title: Get WHOIS
    description: WHOIS Query [https://api.passivetotal.org/api/docs/#api-WHOIS-GetV2WhoisQuery]
    input:
      compact_record:
        title: Compact Record
        type: boolean
        description: Set to true to return a compact record
        required: true
      query:
        title: Query
        description: Input query, e.g. www.google.com
        type: string
        required: true
    output:
      found:
        title: Found
        description: True if found
        type: boolean
        required: false
      record:
        title: Record
        description: WHOIS Record Result
        type: whois_record
        required: false
  search_whois:
    title: Search WHOIS
    description: Search WHOIS [https://api.passivetotal.org/api/docs/#api-WHOIS-GetV2WhoisSearchQueryField]
    input:
      field:
        title: Field
        type: string
        description: Field to search on
        enum:
        - domain
        - email
        - name
        - organization
        - address
        - phone
        - nameserver
        required: true
      query:
        title: Query
        description: Input query, e.g. user@example.com
        type: string
        required: true
    output:
      found:
        title: Found
        description: True if found
        type: boolean
        required: false
      record:
        title: Record
        description: WHOIS Record Result
        type: whois_record
        required: false
  search_whois_by_keyword:
    title: Search WHOIS by Keyword
    description: Search WHOIS by keyword
    input:
      query:
        title: Query
        description: Input query, e.g. user@example.com
        type: string
        required: true
    output:
      count:
        title: Count
        description: Number of results returned
        type: integer
        required: false
      results:
        title: Results
        description: WHOIS Keyword Results
        type: '[]whois_keyword_result'
        required: false
  get_monitor_alerts:
    title: Get Monitor Alerts
    description: Retrieve all alerts associated with an artifact or project
    input:
      project:
        title: Projects
        type: string
        description: The name of the project to search by
        required: false
      start:
        title: Start Time
        type: date
        description: Filter results to after this datetime
        required: false
      end:
        title: End Time
        type: date
        description: Filter results to before this datetime
        required: false
    output:
      results:
        title: Results
        type: object
        description: Retrieved alerts
        required: false
      total_records:
        title: Total Records
        type: number
        description: Number of alerts returned
        required: false
