# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Input:
    TARGET_ID = "target_id"
    

class Output:
    MESSAGE = "message"
    SUCCESS = "success"
    

class DeleteTargetInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "target_id": {
      "type": "string",
      "title": "Target ID",
      "description": "Target ID",
      "order": 1
    }
  },
  "required": [
    "target_id"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class DeleteTargetOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "message": {
      "type": "string",
      "title": "Message",
      "description": "Message",
      "order": 2
    },
    "success": {
      "type": "boolean",
      "title": "Success",
      "description": "Success",
      "order": 1
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
