{
  "cve": {
    "cve_id": "CVE-2024-3400",
    "title": "CVE-2024-3400: Improper Neutralization of Special Elements used in a Command",
    "published_date": "2024-04-12T00:00:00",
    "modified_date": "2025-11-21T00:00:00",
    "cvss_v3_base_score": 10.0,
    "cvss_v3_severity": "Critical",
    "cvss_v3_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H",
    "epss_score": 0.94297,
    "epss_percentile": 0.9994,
    "active_risk_score": 1000,
    "exploitable": true,
    "exploited_in_the_wild": true,
    "cisa_kev": true,
    "campaign_count": 9,
    "threat_actor_count": 3,
    "references": [],
    "description": "A command injection as a result of arbitrary file creation vulnerability in the GlobalProtect feature of Palo Alto Networks PAN-OS software for specific PAN-OS versions and distinct feature configurations may enable an unauthenticated attacker to execute arbitrary code with root privileges on the firewall.\n\nCloud NGFW, Panorama appliances, and Prisma Access are not impacted by this vulnerability.",
    "tags": [
      "Remote Execution",
      "CISA KEV",
      "Exploited in the Wild",
      "Rapid7 Critical"
    ]
  },
  "found": true
}
