# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Input:
    ALERT = "alert"
    

class Output:
    ALERT = "alert"
    

class RootcheckParseInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "alert": {
      "type": "string",
      "title": "Alert",
      "description": "OSSEC Rootcheck alert",
      "order": 1
    }
  },
  "required": [
    "alert"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class RootcheckParseOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "alert": {
      "$ref": "#/definitions/rootcheck_alert",
      "title": "Alert",
      "description": "Alert",
      "order": 1
    }
  },
  "required": [
    "alert"
  ],
  "definitions": {
    "rootcheck_alert": {
      "type": "object",
      "title": "rootcheck_alert",
      "properties": {
        "agent": {
          "type": "string",
          "title": "Agent",
          "description": "Agent alert was created on",
          "order": 4
        },
        "alert_id": {
          "type": "number",
          "title": "Alert ID",
          "description": "Alert ID of the OSSEC alert",
          "order": 1
        },
        "category": {
          "type": "string",
          "title": "Alert Category",
          "description": "Alert category",
          "order": 2
        },
        "file": {
          "type": "string",
          "title": "File",
          "description": "File related to alert",
          "order": 8
        },
        "level": {
          "type": "integer",
          "title": "Level",
          "description": "Alert level",
          "order": 6
        },
        "logs": {
          "type": "array",
          "title": "Alert Logs",
          "description": "Alert logs",
          "items": {
            "type": "string"
          },
          "order": 9
        },
        "rule_id": {
          "type": "integer",
          "title": "Rule ID",
          "description": "Rule ID",
          "order": 5
        },
        "rule_name": {
          "type": "string",
          "title": "Alert Name",
          "description": "Alert name",
          "order": 7
        },
        "timestamp": {
          "type": "string",
          "title": "Time Stamp",
          "description": "Time stamp",
          "order": 3
        }
      },
      "required": [
        "timestamp",
        "agent",
        "rule_name",
        "logs",
        "alert_id",
        "category",
        "rule_id",
        "level"
      ]
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
