# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Get site IDs associated with a tag"


class Input:
    ID = "id"


class Output:
    SITE_IDS = "site_ids"


class GetTagSitesInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(
        r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "id": {
      "type": "integer",
      "title": "ID",
      "description": "Tag ID for which to retrieve site associations",
      "order": 1
    }
  },
  "required": [
    "id"
  ],
  "definitions": {}
}
    """
    )

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetTagSitesOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(
        r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "site_ids": {
      "type": "array",
      "title": "Site IDs",
      "description": "Site IDs associated with the tag",
      "items": {
        "type": "integer"
      },
      "order": 1
    }
  },
  "required": [
    "site_ids"
  ],
  "definitions": {}
}
    """
    )

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
