# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Create a new audit in Cyber GRC"


class Input:
    EXPAND = "expand"
    RECORD = "record"


class Output:
    AUDIT = "audit"


class CreateAuditInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "expand": {
      "type": "string",
      "title": "Expand",
      "description": "Comma separated list of related collections to embed in the created record",
      "order": 2
    },
    "record": {
      "type": "object",
      "title": "Audit",
      "description": "The audit to create, as a JSON object matching the CreateAuditDto schema in the Compyl API reference",
      "order": 1
    }
  },
  "required": [
    "record"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class CreateAuditOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "audit": {
      "$ref": "#/definitions/audit",
      "title": "Audit",
      "description": "The created audit",
      "order": 1
    }
  },
  "required": [
    "audit"
  ],
  "definitions": {
    "audit": {
      "type": "object",
      "title": "audit",
      "properties": {
        "frequencyName": {
          "type": "string",
          "title": "Frequency Name",
          "description": "Frequency Name",
          "order": 1
        },
        "controlSet": {
          "$ref": "#/definitions/audit_control_set_lookup",
          "title": "Control Set",
          "description": "Control Set",
          "order": 2
        },
        "auditUsers": {
          "type": "array",
          "title": "Audit Users",
          "description": "Audit Users",
          "items": {
            "$ref": "#/definitions/audit_audit_user_lookup"
          },
          "order": 3
        },
        "documents": {
          "type": "array",
          "title": "Documents",
          "description": "Documents",
          "items": {
            "$ref": "#/definitions/audit_document_lookup"
          },
          "order": 4
        },
        "auditorFindings": {
          "type": "array",
          "title": "Auditor Findings",
          "description": "Auditor Findings",
          "items": {
            "$ref": "#/definitions/audit_auditor_finding_lookup"
          },
          "order": 5
        },
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 6
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 7
        },
        "description": {
          "type": "string",
          "title": "Description",
          "description": "Description",
          "order": 8
        },
        "status": {
          "type": "string",
          "title": "Status",
          "description": "Status",
          "order": 9
        },
        "observationPeriodStart": {
          "type": "string",
          "format": "date-time",
          "displayType": "date",
          "title": "Observation Period Start",
          "description": "Observation Period Start",
          "order": 10
        },
        "observationPeriodEnd": {
          "type": "string",
          "format": "date-time",
          "displayType": "date",
          "title": "Observation Period End",
          "description": "Observation Period End",
          "order": 11
        },
        "startDate": {
          "type": "string",
          "format": "date-time",
          "displayType": "date",
          "title": "Start Date",
          "description": "Start Date",
          "order": 12
        },
        "endDate": {
          "type": "string",
          "format": "date-time",
          "displayType": "date",
          "title": "End Date",
          "description": "End Date",
          "order": 13
        },
        "frequency": {
          "type": "integer",
          "title": "Frequency",
          "description": "Frequency",
          "order": 14
        },
        "controlSetID": {
          "type": "integer",
          "title": "Control Set ID",
          "description": "Control Set ID",
          "order": 15
        },
        "discussionFieldID": {
          "type": "integer",
          "title": "Discussion Field ID",
          "description": "Discussion Field ID",
          "order": 16
        },
        "isArchived": {
          "type": "boolean",
          "title": "Is Archived",
          "description": "Is Archived",
          "order": 17
        },
        "createdDate": {
          "type": "string",
          "format": "date-time",
          "displayType": "date",
          "title": "Created Date",
          "description": "Created Date",
          "order": 18
        },
        "modifiedDate": {
          "type": "string",
          "format": "date-time",
          "displayType": "date",
          "title": "Modified Date",
          "description": "Modified Date",
          "order": 19
        },
        "createdBy": {
          "type": "string",
          "title": "Created By",
          "description": "Created By",
          "order": 20
        },
        "modifiedBy": {
          "type": "string",
          "title": "Modified By",
          "description": "Modified By",
          "order": 21
        },
        "assessments": {
          "type": "array",
          "title": "Assessments",
          "description": "Assessments",
          "items": {
            "$ref": "#/definitions/assessment_lookup"
          },
          "order": 22
        },
        "tasks": {
          "type": "array",
          "title": "Tasks",
          "description": "Tasks",
          "items": {
            "$ref": "#/definitions/task_lookup"
          },
          "order": 23
        },
        "tags": {
          "type": "array",
          "title": "Tags",
          "description": "Tags",
          "items": {
            "$ref": "#/definitions/tag_lookup"
          },
          "order": 24
        },
        "extendedFields": {
          "type": "object",
          "title": "Extended Fields",
          "description": "Extended Fields",
          "order": 25
        }
      }
    },
    "audit_control_set_lookup": {
      "type": "object",
      "title": "audit_control_set_lookup",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 2
        }
      }
    },
    "audit_audit_user_lookup": {
      "type": "object",
      "title": "audit_audit_user_lookup",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 2
        },
        "usersID": {
          "type": "integer",
          "title": "Users ID",
          "description": "Users ID",
          "order": 3
        },
        "userEmail": {
          "type": "string",
          "title": "User Email",
          "description": "User Email",
          "order": 4
        },
        "userFirstName": {
          "type": "string",
          "title": "User First Name",
          "description": "User First Name",
          "order": 5
        },
        "userLastName": {
          "type": "string",
          "title": "User Last Name",
          "description": "User Last Name",
          "order": 6
        },
        "title": {
          "type": "string",
          "title": "Title",
          "description": "Title",
          "order": 7
        },
        "active": {
          "type": "boolean",
          "title": "Active",
          "description": "Active",
          "order": 8
        }
      }
    },
    "audit_document_lookup": {
      "type": "object",
      "title": "audit_document_lookup",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 2
        }
      }
    },
    "audit_auditor_finding_lookup": {
      "type": "object",
      "title": "audit_auditor_finding_lookup",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 2
        }
      }
    },
    "assessment_lookup": {
      "type": "object",
      "title": "assessment_lookup",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 2
        }
      }
    },
    "task_lookup": {
      "type": "object",
      "title": "task_lookup",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 2
        }
      }
    },
    "tag_lookup": {
      "type": "object",
      "title": "tag_lookup",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 2
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
