# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Input:
    FILE = "file"
    

class Output:
    FILE_COUNT = "file_count"
    FILES = "files"
    

class ExtractInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "file": {
      "type": "string",
      "title": "Base64 Encoded Image",
      "displayType": "bytes",
      "description": "Base64 encoded disk image file",
      "format": "bytes",
      "order": 1
    }
  },
  "required": [
    "file"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class ExtractOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "file_count": {
      "type": "integer",
      "title": "File Count",
      "description": "Number of files extracted",
      "order": 2
    },
    "files": {
      "type": "array",
      "title": "Files",
      "description": "Extracted files",
      "items": {
        "type": "string",
        "displayType": "bytes",
        "format": "bytes"
      },
      "order": 1
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
