{
  "reports": [
    {
      "id": "9382986b58cb4b44935e7eba079842f3_18a6d0ec35e44182a0b55b6a2ec16592",
      "cid": "9382986b58cb4b44935e7eba079842f3",
      "createdTimestamp": "2022-08-30T09:17:31Z",
      "origin": "uiproxy",
      "userId": "3e7da174cb6944e8a4cd8a5a59a76727",
      "userName": "user@example.com",
      "sandbox": [
        {
          "sha256": "275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f",
          "environmentId": 100,
          "environmentDescription": "Windows 7 32 bit",
          "submitName": "VirusTotal_IP_Error.png",
          "submissionType": "file",
          "fileType": "PNG image data, 1682 x 1068, 8-bit/color RGBA, non-interlaced",
          "errorMessage": "File \"VirusTotal_IP_Error.png\" was detected as \"image\", this format is not supported on WINDOWS",
          "errorType": "FILE_TYPE_BAD_ERROR",
          "errorOrigin": "CLIENT"
        }
      ],
      "verdict": "no verdict"
    },
    {
      "id": "9382986b58cb4b44935e7eba079842f3_4c95cb1fc7314509a5b9054752e9c4ff",
      "cid": "9382986b58cb4b44935e7eba079842f3",
      "createdTimestamp": "2022-08-30T10:08:49Z",
      "origin": "uiproxy",
      "userId": "6f888e357b5043c6906c51b204c4091b",
      "userName": "user@example.com",
      "sandbox": [
        {
          "sha256": "275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f",
          "environmentId": 100,
          "environmentDescription": "Windows 7 32 bit",
          "submitName": "test.pdf",
          "submissionType": "file",
          "verdict": "no specific threat",
          "fileType": "PDF document, version 1.5",
          "sampleFlags": [
            "Extracted Files"
          ],
          "networkSettings": "default"
        }
      ],
      "verdict": "no specific threat",
      "iocReportStrictCsvArtifactId": "800c46247e66da1cec722880b2ed412498ddc8d739e010cf28652839ffbac33e",
      "iocReportBroadCsvArtifactId": "800c46247e66da1cec722880b2ed412498ddc8d739e010cf28652839ffbac33e",
      "iocReportStrictJsonArtifactId": "1248b73905ba1b8ef5fdca2d3604e41a331b2b8f4c89ccfc714467153c706d00",
      "iocReportBroadJsonArtifactId": "1248b73905ba1b8ef5fdca2d3604e41a331b2b8f4c89ccfc714467153c706d00",
      "iocReportStrictStixArtifactId": "1f7dda003e8c61d1509aa77ded1dc4d6b758324913fc5ccb56322206278642fa",
      "iocReportBroadStixArtifactId": "1f7dda003e8c61d1509aa77ded1dc4d6b758324913fc5ccb56322206278642fa",
      "iocReportStrictMaecArtifactId": "10a13c1729dde89ef436465af0a7f03348bd9c884723f4b1642770806fa2bef6",
      "iocReportBroadMaecArtifactId": "10a13c1729dde89ef436465af0a7f03348bd9c884723f4b1642770806fa2bef6"
    },
    {
      "id": "9382986b58cb4b44935e7eba079842f3_305b3129e8a643f4bb7d6b166867fa13",
      "cid": "9382986b58cb4b44935e7eba079842f3",
      "createdTimestamp": "2022-09-28T07:45:34Z",
      "origin": "uiproxy",
      "userId": "68ffc9dcf90b4ac5856a0d8f2af810a9",
      "userName": "user@example.com",
      "sandbox": [
        {
          "sha256": "275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f",
          "environmentId": 100,
          "environmentDescription": "Windows 7 32 bit",
          "submitName": "Dockerfile",
          "submissionType": "file",
          "fileType": "ASCII text",
          "errorMessage": "The file \"Dockerfile\" has the file format \"text\", which is not supported",
          "errorType": "FILE_TYPE_BAD_ERROR",
          "errorOrigin": "CLIENT"
        }
      ],
      "verdict": "no verdict"
    },
    {
      "id": "9382986b58cb4b44935e7eba079842f3_92c8b7525e2b4888bd9e2fe7391c7104",
      "cid": "9382986b58cb4b44935e7eba079842f3",
      "createdTimestamp": "2022-11-07T14:14:18Z",
      "origin": "apigateway",
      "sandbox": [
        {
          "sha256": "275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f",
          "environmentId": 100,
          "environmentDescription": "Windows 7 32 bit",
          "submitName": "my_submit_name",
          "submissionType": "file",
          "verdict": "no specific threat",
          "fileType": "PDF document, version 1.3",
          "sampleFlags": [
            "Extracted Files"
          ],
          "networkSettings": "default"
        }
      ],
      "userTags": [
        "example"
      ],
      "verdict": "whitelisted",
      "iocReportStrictCsvArtifactId": "6fea35833e8419f847d2f5f21e322ae4b0e6e7a27a04151a8fd34144270768c4",
      "iocReportBroadCsvArtifactId": "6fea35833e8419f847d2f5f21e322ae4b0e6e7a27a04151a8fd34144270768c4",
      "iocReportStrictJsonArtifactId": "6d936ea006e3e290c1e530254a37bc2063536caf732159e4bcd6692ca9c483a8",
      "iocReportBroadJsonArtifactId": "6d936ea006e3e290c1e530254a37bc2063536caf732159e4bcd6692ca9c483a8",
      "iocReportStrictStixArtifactId": "20c2b7d225014eff60080fb7a5d97682daffb9a7f3cbc2e909d27cd20f51fdcb",
      "iocReportBroadStixArtifactId": "20c2b7d225014eff60080fb7a5d97682daffb9a7f3cbc2e909d27cd20f51fdcb",
      "iocReportStrictMaecArtifactId": "6160988cf579c1e54f12f3b511715c642a30f7efcf92535840fd82dd9cc649ff",
      "iocReportBroadMaecArtifactId": "6160988cf579c1e54f12f3b511715c642a30f7efcf92535840fd82dd9cc649ff"
    }
  ]
}