plugin_spec_version: v2
extension: plugin
products: [insightconnect]
name: rss
title: RSS
description: The RSS plugin allows you to monitor an RSS feed
version: 1.0.3
vendor: rapid7
support: community
status: []
resources:
  source_url: https://github.com/rapid7/insightconnect-plugins/tree/master/rss
  license_url: https://github.com/rapid7/insightconnect-plugins/blob/master/LICENSE
tags:
- rss
- atom
- feed
hub_tags:
  use_cases: [data_utility, threat_detection_and_response, alerting_and_notifications]
  keywords: [rss, atom, feed]
  features: []
enable_cache: true
language: python
connection:
  url:
    title: URL
    type: string
    description: Feed URL
    required: true
triggers:
  poll:
    title: Poll Feed
    description: Poll feed for latest event
    input:
      frequency:
        title: Frequency
        type: integer
        description: How frequently to poll for new events
        default: 15
        required: true
    output:
      results:
        type: object
        title: Results
        description: RSS data
        required: true
