# GENERATED BY KOMAND SDK - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Label issue"


class Input:
    ID = "id"
    LABEL = "label"
    

class Output:
    SUCCESS = "success"
    

class LabelIssueInput(insightconnect_plugin_runtime.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "id": {
      "type": "string",
      "title": "ID",
      "description": "Issue ID",
      "order": 1
    },
    "label": {
      "type": "string",
      "title": "Label",
      "description": "Label to add. To add multiple labels, separate by commas",
      "order": 2
    }
  },
  "required": [
    "id",
    "label"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class LabelIssueOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "success": {
      "type": "boolean",
      "title": "Success",
      "description": "True if successful",
      "order": 1
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
