{
    "tasks": [
        {
            "added_on": "2018-02-07 14:16:48",
            "category": "url",
            "clock": "2018-02-07 14:16:48",
            "completed_on": "2018-02-07 14:20:06",
            "duration": 197,
            "enforce_timeout": false,
            "errors": [],
            "guest": {
                "id": 1,
                "label": "examplelabel",
                "manager": "ExampleManager",
                "name": "examplename",
                "shutdown_on": "2018-02-07 14:20:05",
                "started_on": "2018-02-07 14:16:48",
                "status": "stopped",
                "task_id": 1
            },
            "id": 1,
            "memory": false,
            "options": [
                {
                    "procmemdump": "yes",
                    "route": "none"
                }
            ],
            "package": "ie",
            "priority": 2,
            "route": "none",
            "sample": {},
            "started_on": "2018-02-07 14:16:48",
            "status": "reported",
            "submit_id": 1,
            "tags": [],
            "target": "http://example.com",
            "timeout": 120
        },
        {
            "added_on": "2018-02-07 14:23:35",
            "category": "file",
            "clock": "2018-02-07 14:23:35",
            "completed_on": "2018-02-07 14:26:55",
            "duration": 199,
            "enforce_timeout": false,
            "errors": [],
            "guest": {
                "id": 2,
                "label": "examplelabel",
                "manager": "ExampleManager",
                "name": "examplename",
                "shutdown_on": "2018-02-07 14:26:55",
                "started_on": "2018-02-07 14:23:36",
                "status": "stopped",
                "task_id": 2
            },
            "id": 2,
            "memory": false,
            "options": [
                {
                    "procmemdump": "yes",
                    "route": "none"
                }
            ],
            "package": "exe",
            "platform": "windows",
            "priority": 2,
            "route": "none",
            "sample": {
                "crc32": "6C8E0C97",
                "file_size": 3020136,
                "file_type": "PE32 executable (GUI) Intel 80386, for MS Windows",
                "id": 1,
                "md5": "44d88612fea8a8f36de82e1278abb02f",
                "sha1": "3395856ce81f2b7382dee72602f798b642f14140",
                "sha256": "275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f",
                "sha512": "cc805d5fab1fd71a4ab352a9c533e65fb2d5b885518f4e565e68847223b8e6b85cb48f3afad842726d99239c9e36505c64b0dc9a061d9e507d833277ada336ab"
            },
            "sample_id": 1,
            "started_on": "2018-02-07 14:23:35",
            "status": "reported",
            "submit_id": 2,
            "tags": [],
            "target": "/tmp/cuckoo-tmp/tmp/Example.exe",
            "timeout": 120
        },
        {
            "added_on": "2018-02-07 14:29:47",
            "category": "file",
            "clock": "2018-02-07 14:29:47",
            "completed_on": "2018-02-07 14:33:08",
            "custom": "2",
            "duration": 200,
            "enforce_timeout": false,
            "errors": [],
            "guest": {
                "id": 3,
                "label": "examplelabel",
                "manager": "ExampleManager",
                "name": "examplename",
                "shutdown_on": "2018-02-07 14:33:08",
                "started_on": "2018-02-07 14:29:48",
                "status": "stopped",
                "task_id": 3
            },
            "id": 3,
            "memory": false,
            "options": [
                {}
            ],
            "package": "reboot",
            "priority": 1,
            "route": "none",
            "sample": {
                "crc32": "6C8E0C97",
                "file_size": 3020136,
                "file_type": "PE32 executable (GUI) Intel 80386, for MS Windows",
                "id": 1,
                "md5": "44d88612fea8a8f36de82e1278abb02f",
                "sha1": "3395856ce81f2b7382dee72602f798b642f14140",
                "sha256": "275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f",
                "sha512": "cc805d5fab1fd71a4ab352a9c533e65fb2d5b885518f4e565e68847223b8e6b85cb48f3afad842726d99239c9e36505c64b0dc9a061d9e507d833277ada336ab"
            },
            "sample_id": 1,
            "started_on": "2018-02-07 14:29:47",
            "status": "reported",
            "submit_id": 3,
            "tags": [],
            "target": "/tmp/cuckoo-tmp/tmp/Example.exe",
            "timeout": 0
        },
        {
            "added_on": "2018-02-09 09:49:21",
            "category": "url",
            "clock": "2018-02-09 09:49:21",
            "completed_on": "2018-02-09 09:52:37",
            "duration": 195,
            "enforce_timeout": false,
            "errors": [],
            "guest": {
                "id": 4,
                "label": "examplelabel",
                "manager": "ExampleManager",
                "name": "examplename",
                "shutdown_on": "2018-02-09 09:52:36",
                "started_on": "2018-02-09 09:49:21",
                "status": "stopped",
                "task_id": 4
            },
            "id": 4,
            "memory": false,
            "options": [
                {
                    "procmemdump": "yes",
                    "route": "none"
                }
            ],
            "package": "ie",
            "priority": 2,
            "route": "none",
            "sample": {},
            "started_on": "2018-02-09 09:49:21",
            "status": "reported",
            "submit_id": 4,
            "tags": [],
            "target": "https//:example.com",
            "timeout": 120
        }
    ]
}