{
    "task": {
        "category": "url",
        "errors": [],
        "target": "http://www.malicious.site",
        "guest": {},
        "priority": 1,
        "status": "pending",
        "enforce_timeout": false,
        "timeout": 0,
        "memory": false,
        "tags": [
                    "32bit",
                    "acrobat_6"
                ],
        "id": 1,
        "added_on": "2012-12-19 14:18:25"
    }
}