# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Component:
    DESCRIPTION = "Update details of an existing feed"


class Input:
    ADMINS = "admins"
    DESCRIPTION = "description"
    FEED_ID = "feed_id"
    GUESTS = "guests"
    LINK = "link"
    LOGO = "logo"
    MEMBERS = "members"
    PRIVACY = "privacy"
    TAGS = "tags"
    TOS = "tos"
    

class Output:
    FEED = "feed"
    

class UpdateFeedInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "admins": {
      "type": "array",
      "title": "Admins",
      "description": "List of usernames that have `update`, `post`, and `read` permissions to this feed",
      "items": {
        "type": "string"
      },
      "order": 8
    },
    "description": {
      "type": "string",
      "title": "Description",
      "description": "Feed description text",
      "order": 2
    },
    "feed_id": {
      "type": "string",
      "title": "Feed ID",
      "description": "The feed ID",
      "order": 1
    },
    "guests": {
      "type": "array",
      "title": "Guests",
      "description": "List of usernames that have `read` permission to this feed",
      "items": {
        "type": "string"
      },
      "order": 10
    },
    "link": {
      "type": "string",
      "title": "Link",
      "description": "URL for blog or website where users can learn more about this feed",
      "order": 3
    },
    "logo": {
      "type": "string",
      "title": "Logo",
      "description": "URL for small thumbnail for this feed (must be hosted on imgur CDN)",
      "order": 5
    },
    "members": {
      "type": "array",
      "title": "Members",
      "description": "List of usernames that have `post` and `read` permissions to this feed",
      "items": {
        "type": "string"
      },
      "order": 9
    },
    "privacy": {
      "type": "string",
      "title": "Privacy",
      "description": "Can be set to either `private` or `public` (default)",
      "default": "public",
      "enum": [
        "private",
        "public"
      ],
      "order": 6
    },
    "tags": {
      "type": "array",
      "title": "Tags",
      "description": "List of tags to categorize and help others find this feed",
      "items": {
        "type": "string"
      },
      "order": 7
    },
    "tos": {
      "type": "string",
      "title": "TOS",
      "description": "Terms of Use for this feed",
      "order": 4
    }
  },
  "required": [
    "feed_id"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class UpdateFeedOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "feed": {
      "$ref": "#/definitions/feed",
      "title": "Feed",
      "description": "Updated feed",
      "order": 1
    }
  },
  "required": [
    "feed"
  ],
  "definitions": {
    "feed": {
      "type": "object",
      "title": "feed",
      "properties": {
        "description": {
          "type": "string",
          "title": "Description",
          "description": "Feed description text",
          "order": 4
        },
        "id": {
          "type": "string",
          "title": "ID",
          "description": "Feed ID",
          "order": 1
        },
        "is_admin": {
          "type": "boolean",
          "title": "Is Admin",
          "description": "Boolean indicating if current user can administer this feed",
          "order": 11
        },
        "is_guest": {
          "type": "boolean",
          "title": "Is Guest",
          "description": "Boolean indicating if current user can read from this feed",
          "order": 13
        },
        "is_member": {
          "type": "boolean",
          "title": "Is Member",
          "description": "Boolean indicating if current user can contribute to this feed",
          "order": 12
        },
        "is_owner": {
          "type": "boolean",
          "title": "Is Owner",
          "description": "Boolean indicating if current user owns this feed",
          "order": 10
        },
        "link": {
          "type": "string",
          "title": "Link",
          "description": "URL for blog or website where users can learn more about this feed",
          "order": 5
        },
        "logo": {
          "type": "string",
          "title": "Logo",
          "description": "URL for small thumbnail for this feed (must be hosted on imgur CDN: `https://i.imgur.com/img-id`)",
          "order": 7
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Feed name",
          "order": 2
        },
        "privacy": {
          "type": "string",
          "title": "Privacy",
          "description": "Can be set to either `private` or `public` (default)",
          "order": 8
        },
        "slug": {
          "type": "string",
          "title": "Slug",
          "description": "URL-friendly slug",
          "order": 3
        },
        "tags": {
          "type": "array",
          "title": "Tags",
          "description": "List of tags to categorize and help others find this feed",
          "items": {
            "type": "string"
          },
          "order": 9
        },
        "tos": {
          "type": "string",
          "title": "TOS",
          "description": "Terms of Use for this feed",
          "order": 6
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
