{
  "cyberTerms": [
    {
      "id": "57b974da5b0a195300b6bc7b",
      "value": "OpUSA",
      "type": "Campaign",
      "severity": "High",
      "origins": [
        "Global"
      ],
      "targetCountries": [
        "United States"
      ],
      "targetSectors": [
        "Financial Services",
        "Government"
      ],
      "createdDate": "2016-08-21T09:31:06.000Z",
      "updatedDate": "2022-03-13T13:47:35.879Z",
      "ttps": [
        "DDoS",
        "Defacement",
        "SQL Injection"
      ],
      "overview": "OpUSA was a campaign that was launched by Anonymous hacktivists and various Arab and Muslim hacking groups on May 7, 2013. The campaign was launched in response to the American government\u2019s involvement in wars around the world, specifically in Iraq and Afghanistan. By the end of the campaign, dozens of American websites and servers had been hacked, hundreds of emails were leaked and thousands of social media accounts were hijacked.",
      "additionalInformation": "N/A",
      "relatedThreatActors": [
        "AnonGhost",
        "AnonSec",
        "Anonymous",
        "Mauritania Attacker",
        "Ungku",
        "ZCompany Hacking Crew"
      ]
    }
  ],
  "nextOffset": "2022-03-13T13:47:35.879Z::57b974da5b0a195300b6bc7b"
}
