# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Retrieve the most recent compliance score and automated controls score of each framework, along with an overall score averaged across them. Control sets that are archived or disabled are left out unless one is named with Control Set ID"


class Input:
    CONTROL_SET_ID = "control_set_id"


class Output:
    FRAMEWORKS = "frameworks"
    OVERALL = "overall"


class GetComplianceScoreInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "control_set_id": {
      "type": "integer",
      "title": "Control Set ID",
      "description": "ID of a single control set to score. Leave empty or set to 0 to score every control set",
      "default": 0,
      "order": 1
    }
  },
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetComplianceScoreOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "frameworks": {
      "type": "array",
      "title": "Frameworks",
      "description": "Most recent scores for each control set, most recently calculated first",
      "items": {
        "$ref": "#/definitions/framework_compliance"
      },
      "order": 1
    },
    "overall": {
      "$ref": "#/definitions/overall_compliance",
      "title": "Overall",
      "description": "Scores averaged across the frameworks returned. Cyber GRC does not publish a tenant wide score, so the plugin calculates this one",
      "order": 2
    }
  },
  "required": [
    "frameworks",
    "overall"
  ],
  "definitions": {
    "framework_compliance": {
      "type": "object",
      "title": "framework_compliance",
      "properties": {
        "control_set_id": {
          "type": "integer",
          "title": "Control Set ID",
          "description": "ID of the control set these scores belong to",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name of the control set, omitted when the control set itself could not be read",
          "order": 2
        },
        "compliance": {
          "type": "number",
          "title": "Compliance",
          "description": "Compliance score of this framework",
          "order": 3
        },
        "linked_controls_percentage": {
          "type": "number",
          "title": "Linked Controls Percentage",
          "description": "Percentage of this framework's controls that are linked to evidence",
          "order": 4
        },
        "automated_controls_percentage": {
          "type": "number",
          "title": "Automated Controls Percentage",
          "description": "Percentage of this framework's controls that are evidenced automatically",
          "order": 5
        },
        "date_calculated": {
          "type": "string",
          "title": "Date Calculated",
          "description": "When Cyber GRC last calculated these scores",
          "order": 6
        }
      }
    },
    "overall_compliance": {
      "type": "object",
      "title": "overall_compliance",
      "properties": {
        "compliance": {
          "type": "number",
          "title": "Compliance",
          "description": "Mean compliance score of every framework returned",
          "order": 1
        },
        "automated_controls_percentage": {
          "type": "number",
          "title": "Automated Controls Percentage",
          "description": "Mean automated controls percentage of every framework returned",
          "order": 2
        },
        "framework_count": {
          "type": "integer",
          "title": "Framework Count",
          "description": "Number of frameworks the overall scores were averaged over",
          "order": 3
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
