# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Create an Automox group"


class Input:
    COLOR = "color"
    NAME = "name"
    NOTES = "notes"
    ORG_ID = "org_id"
    PARENT_SERVER_GROUP_ID = "parent_server_group_id"
    POLICIES = "policies"
    REFRESH_INTERVAL = "refresh_interval"


class Output:
    GROUP = "group"
    SUCCESS = "success"


class CreateGroupInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "color": {
      "type": "string",
      "title": "Group Color",
      "description": "Automox console highlight color for the group. Value should be a valid Hex color code",
      "order": 5
    },
    "name": {
      "type": "string",
      "title": "Name",
      "description": "Name of the group",
      "order": 2
    },
    "notes": {
      "type": "string",
      "title": "Group Notes",
      "description": "Define notes for the group",
      "order": 6
    },
    "org_id": {
      "type": "integer",
      "title": "Organization ID",
      "description": "Identifier of organization",
      "order": 1
    },
    "parent_server_group_id": {
      "type": "integer",
      "title": "Parent Server Group ID",
      "description": "Name of the parent group. Defaults to Default Group ID if this is omitted",
      "order": 4
    },
    "policies": {
      "type": "array",
      "title": "Policy IDs",
      "description": "List of policy IDs to assign to group",
      "items": {
        "type": "integer"
      },
      "order": 7
    },
    "refresh_interval": {
      "type": "integer",
      "title": "Refresh Interval",
      "description": "Frequency of device refreshes in minutes",
      "default": 1440,
      "order": 3
    }
  },
  "required": [
    "name",
    "refresh_interval"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class CreateGroupOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "group": {
      "$ref": "#/definitions/group",
      "title": "Group",
      "description": "Detailed information about the created group",
      "order": 2
    },
    "success": {
      "type": "boolean",
      "title": "Success",
      "description": "Was operation successful",
      "order": 1
    }
  },
  "required": [
    "group",
    "success"
  ],
  "definitions": {
    "group": {
      "type": "object",
      "title": "group",
      "properties": {
        "id": {
          "type": "integer",
          "title": "Group ID",
          "description": "The group identifier",
          "order": 1
        },
        "organization_id": {
          "type": "integer",
          "title": "Organization ID",
          "description": "The organization identifier of the group",
          "order": 2
        },
        "name": {
          "type": "string",
          "title": "Group Name",
          "description": "The name of the group",
          "order": 3
        },
        "refresh_interval": {
          "type": "integer",
          "title": "Refresh Interval",
          "description": "Frequency of device refreshes in minutes",
          "order": 4
        },
        "parent_server_group_id": {
          "type": "integer",
          "title": "Parent Server Group ID",
          "description": "The identifier of the parent group",
          "order": 5
        },
        "ui_color": {
          "type": "string",
          "title": "Color",
          "description": "Automox console highlight color for the group",
          "order": 6
        },
        "notes": {
          "type": "string",
          "title": "Notes",
          "description": "Notes defined for the group",
          "order": 7
        },
        "enable_os_auto_update": {
          "type": "boolean",
          "title": "Enable OS Auto Update",
          "description": "Enable operating system auto update",
          "order": 8
        },
        "server_count": {
          "type": "integer",
          "title": "Device Count",
          "description": "Number of devices assigned to group",
          "order": 9
        },
        "policies": {
          "type": "array",
          "title": "Policies",
          "description": "List of policies assigned to group",
          "items": {
            "type": "integer"
          },
          "order": 10
        }
      },
      "required": [
        "id",
        "organization_id"
      ]
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
