# GENERATED BY KOMAND SDK - DO NOT EDIT
from setuptools import setup, find_packages


setup(name='tshark-rapid7-plugin',
      version='1.0.3',
      description='TShark is a tool for dumping and analyzing network traffic. With the TShark plugin for Rapid7 InsightConnect, users can open PCAP data for further analysis and intel gathering',
      author='rapid7',
      author_email='',
      url='',
      packages=find_packages(),
      install_requires=['komand'],  # Add third-party dependencies to requirements.txt, not here!
      scripts=['bin/komand_tshark']
      )
