# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Read contents from a PCAP file"


class Input:
    FILTER = "filter"
    OPTIONS = "options"
    PCAP = "pcap"


class Output:
    DUMP_CONTENTS = "dump_contents"
    DUMP_FILE = "dump_file"
    STDERR = "stderr"


class ReadInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(
        r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "filter": {
      "type": "string",
      "title": "BPF",
      "description": "Berkeley Packet Filter",
      "order": 3
    },
    "options": {
      "type": "string",
      "title": "Options",
      "description": "Tcpdump Flags and Options (must be space-separated)",
      "order": 2
    },
    "pcap": {
      "type": "string",
      "format": "bytes",
      "displayType": "bytes",
      "title": "PCAP File",
      "description": "Base64 encoded PCAP file",
      "order": 1
    }
  },
  "required": [
    "pcap"
  ],
  "definitions": {}
}
    """
    )

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class ReadOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(
        r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "dump_contents": {
      "type": "array",
      "title": "Dump Contents",
      "description": "Traffic Dump as Array",
      "items": {
        "type": "string"
      },
      "order": 1
    },
    "dump_file": {
      "type": "string",
      "format": "bytes",
      "displayType": "bytes",
      "title": "Dump File",
      "description": "Traffic Dump as File",
      "order": 2
    },
    "stderr": {
      "type": "string",
      "title": "Standard Error",
      "description": "Tcpdump Standard Error",
      "order": 3
    }
  },
  "definitions": {}
}
    """
    )

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
