{
  "ticket": {
    "id": 200,
    "summary": "test",
    "recordType": "ServiceTicket",
    "board": {
      "id": 30,
      "name": "Network Security - South",
      "info": {
        "board_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//service/boards/30"
      }
    },
    "status": {
      "id": 550,
      "name": "In Progress",
      "info": {
        "status_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//service/boards/30/statuses/550"
      }
    },
    "company": {
      "id": 19298,
      "identifier": "Example",
      "name": "Example Company",
      "info": {
        "company_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//company/companies/19298",
        "mobileGuid": "5ec92caf-0922-4120-9268-21580dbbcef8"
      }
    },
    "siteName": "Main - Catchall",
    "addressLine1": "address line 1",
    "addressLine2": "address line 2",
    "city": "London",
    "zip": "111111",
    "contact": {
      "id": 17754,
      "name": "Test Contact",
      "info": {
        "mobileGuid": "1cf867f4-6198-40fe-8f28-91a644f08f3f",
        "contact_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//company/contacts/17754"
      }
    },
    "contactName": "Test Contact",
    "type": {
      "id": 248,
      "name": "Testing",
      "info": {
        "type_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//service/boards/30/types/248"
      }
    },
    "subType": {
      "id": 701,
      "name": "Active Directory",
      "info": {
        "subType_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//service/boards/30/subtypes/701"
      }
    },
    "team": {
      "id": 10,
      "name": "Network Security",
      "info": {
        "team_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//service/boards/30/teams/10"
      }
    },
    "owner": {
      "id": 638,
      "identifier": "userint",
      "name": "user integration",
      "info": {
        "member_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//system/members/638",
        "image_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//system/members/638/image?lm=2022-08-03T19:50:33Z"
      }
    },
    "priority": {
      "id": 8,
      "name": "Priority 4 - Low",
      "sort": 4,
      "info": {
        "priority_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//service/priorities/8",
        "image_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//service/priorities/8/image?lm=2020-05-27T21:17:07Z"
      }
    },
    "serviceLocation": {
      "id": 4,
      "name": "Remote",
      "info": {
        "location_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//service/locations/4"
      }
    },
    "source": {
      "id": 11,
      "name": "Automate",
      "info": {
        "source_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//service/sources/11"
      }
    },
    "requiredDate": "2022-09-30T00:00:00Z",
    "budgetHours": 10.5,
    "agreement": {
      "id": 249,
      "name": "Internal",
      "info": {
        "agreement_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//finance/agreements/249"
      }
    },
    "severity": "Medium",
    "impact": "Low",
    "allowAllClientsPortalView": false,
    "customerUpdatedFlag": false,
    "automaticEmailContactFlag": true,
    "automaticEmailResourceFlag": true,
    "automaticEmailCcFlag": true,
    "automaticEmailCc": "user@example.com;",
    "closedFlag": false,
    "approved": true,
    "estimatedExpenseCost": 0.0,
    "estimatedExpenseRevenue": 0.0,
    "estimatedProductCost": 0.0,
    "estimatedProductRevenue": 0.0,
    "estimatedTimeCost": 0.0,
    "estimatedTimeRevenue": 0.0,
    "billingMethod": "ActualRates",
    "subBillingMethod": "ActualRates",
    "dateResplan": "2022-09-02T08:29:34Z",
    "dateResponded": "2022-09-02T08:29:34Z",
    "resolveMinutes": 0,
    "resPlanMinutes": 0,
    "respondMinutes": 0,
    "isInSla": true,
    "resources": "userint",
    "hasChildTicket": false,
    "hasMergedChildTicketFlag": false,
    "billTime": "NoDefault",
    "billExpenses": "NoDefault",
    "billProducts": "NoDefault",
    "estimatedStartDate": "2022-09-01T00:00:00Z",
    "duration": 22,
    "location": {
      "id": 11,
      "name": "Example Location",
      "info": {
        "location_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//system/locations/11"
      }
    },
    "department": {
      "id": 5,
      "identifier": "Engineering",
      "name": "Engineering",
      "info": {
        "department_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//system/departments/5"
      }
    },
    "mobileGuid": "468dca91-3a2f-4988-9a48-26adcbdd0e69",
    "sla": {
      "id": 3,
      "name": "Example Standard SLA",
      "info": {
        "sla_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//service/SLAs/3"
      }
    },
    "slaStatus": "Resolve by Tue 10/04 11:00 PM UTC-05",
    "requestForChangeFlag": false,
    "currency": {
      "id": 7,
      "symbol": "$",
      "currencyCode": "USD",
      "decimalSeparator": ".",
      "numberOfDecimals": 2,
      "thousandsSeparator": ",",
      "negativeParenthesesFlag": false,
      "displaySymbolFlag": true,
      "currencyIdentifier": "USD",
      "displayIdFlag": false,
      "rightAlign": false,
      "name": "US Dollars",
      "info": {
        "currency_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//finance/currencies/7"
      }
    },
    "info": {
      "lastUpdated": "2022-09-02T08:29:34Z",
      "updatedBy": "user",
      "dateEntered": "2022-09-02T08:29:33Z",
      "enteredBy": "user",
      "activities_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//sales/activities?conditions=ticket/id=945366",
      "scheduleentries_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//schedule/entries?conditions=type/id=4 AND objectId=945366",
      "documents_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//system/documents?recordType=Ticket&recordId=945366",
      "configurations_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//service/tickets/945366/configurations",
      "tasks_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//service/tickets/945366/tasks",
      "notes_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//service/tickets/945366/notes",
      "products_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//procurement/products?conditions=chargeToType='Ticket' AND chargeToId=945366",
      "timeentries_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//time/entries?conditions=(chargeToType='ServiceTicket' OR chargeToType='ProjectTicket') AND chargeToId=945366",
      "expenseEntries_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//expense/entries?conditions=(chargeToType='ServiceTicket' OR chargeToType='ProjectTicket') AND chargeToId=945366"
    },
    "escalationStartDateUTC": "2022-09-30T04:00:00Z",
    "escalationLevel": 10,
    "minutesBeforeWaiting": 0,
    "respondedSkippedMinutes": 0,
    "resplanSkippedMinutes": 0,
    "customFields": [
      {
        "id": 7,
        "caption": "Dispatch Billing Required",
        "type": "Text",
        "entryMethod": "List",
        "numberOfDecimals": 0
      },
      {
        "id": 36,
        "caption": "Business App assigned ",
        "type": "Date",
        "entryMethod": "EntryField",
        "numberOfDecimals": 0
      },
      {
        "id": 37,
        "caption": "T&M Billing Required",
        "type": "Checkbox",
        "entryMethod": "EntryField",
        "numberOfDecimals": 0
      }
    ]
  }
}