{
  "ticket_notes": [
    {
      "id": 1545986,
      "ticketId": 945315,
      "text": "unit text",
      "detailDescriptionFlag": true,
      "internalAnalysisFlag": false,
      "resolutionFlag": false,
      "issueFlag": false,
      "member": {
        "id": 637,
        "identifier": "user",
        "name": "user",
        "_info": {
          "member_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//system/members/637",
          "image_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//system/members/637/image?lm=2022-08-03T19:37:23Z"
        }
      },
      "dateCreated": "2022-09-01T08:45:10Z",
      "createdBy": "user",
      "internalFlag": true,
      "externalFlag": true,
      "_info": {
        "lastUpdated": "2022-09-01T08:45:10Z",
        "updatedBy": "user"
      }
    },
    {
      "id": 1545987,
      "ticketId": 945315,
      "text": "test text",
      "detailDescriptionFlag": true,
      "internalAnalysisFlag": true,
      "resolutionFlag": false,
      "issueFlag": false,
      "member": {
        "id": 637,
        "identifier": "user",
        "name": "user",
        "_info": {
          "member_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//system/members/637",
          "image_href": "https://sandbox-na.myconnectwise.net/v4_6_release/apis/3.0//system/members/637/image?lm=2022-08-03T19:37:23Z"
        }
      },
      "dateCreated": "2022-09-01T08:45:49Z",
      "createdBy": "user",
      "internalFlag": true,
      "externalFlag": true,
      "_info": {
        "lastUpdated": "2022-09-01T08:45:49Z",
        "updatedBy": "user"
      }
    }
  ]
}