plugin_spec_version: v2
extension: plugin
products: ["insightconnect"]
name: microsoft_atp
title: Microsoft Windows Defender ATP
description: The Windows Defender Advanced Threat Protection plugin allows Rapid7 InsightConnect users to quickly take remediation actions across their organization. This plugin can isolate machines, run virus scans, and quarantine files
version: 4.1.0
vendor: rapid7
support: community
status: []
resources:
  vendor_url: https://www.microsoft.com/
tags:
- windows
- atp
- microsoft
- defender
hub_tags:
  use_cases: [threat_detection_and_response, user_management, alerting_and_notifications, devops]
  keywords: [windows, atp, microsoft, defender]
  features: []

types:
  related_user_object:
    domainName:
      title: "Domain Name"
      description: "Domain name"
      required: false
      type: string
    userName:
      title: User Name
      description: User name
      required: false
      type: string
  alert:
    id:
      title: "ID"
      type: string
      description: "ID"
      required: false
    incidentId:
      title: "Incident ID"
      type: integer
      description: "Incident ID"
      required: false
    investigationId:
      title: "Investigation ID"
      type: integer
      description: "Investigation ID"
      required: false
    assignedTo:
      title: "Assigned To"
      type: string
      description: "Assigned To"
      required: false
    severity:
      title: "Severity"
      type: string
      description: "Severity"
      required: false
    status:
      title: "Status"
      type: string
      description: "Status"
      required: false
    classification:
      title: "Classification"
      type: string
      description: "Classification"
      required: false
    determination:
      title: "Determination"
      type: string
      description: "Determination"
      required: false
    investigationState:
      title: "Investigation State"
      type: string
      description: "Investigation state"
      required: false
    detectionSource:
      title: "Detection Source"
      type: string
      description: "Detection source"
      required: false
    category:
      title: "Category"
      type: string
      description: "Category"
      required: false
    threatFamilyName:
      title: "Threat Family Name"
      type: string
      description: "Threat family name"
      required: false
    title:
      title: "Title"
      type: string
      description: "Title"
      required: false
    description:
      title: "Description"
      type: string
      description: "Description"
      required: false
    alertCreationTime:
      title: "Alert Creation Time"
      type: string
      description: "Alert creation time"
      required: false
    firstEventTime:
      title: "First Event Time"
      type: string
      description: "First event time"
      required: false
    lastEventTime:
      title: "Last Event Time"
      type: string
      description: "Last event time"
      required: false
    lastUpdateTime:
      title: "Last Update Time"
      type: string
      description: "Last update time"
      required: false
    resolvedTime:
      title: "Resolved Time"
      type: string
      description: "Resolved time"
      required: false
    machineId:
      title: "Machine ID"
      type: string
      description: "Machine ID"
      required: false
    computerDnsName:
      title: "Computer DNS Name"
      type: string
      description: "Computer DNS name"
      required: false
    rbacGroupName:
      title: "RBAC Group Name"
      type: string
      description: "RBAC group name"
      required: false
    aadTenantId:
      title: "AAD Tenant ID"
      type: string
      description: "AAD tenant ID"
      required: false
    relatedUser:
      title: "Related User"
      type: related_user_object
      description: "Related user"
      required: false

  file_type:
    sha1:
      title: "SHA1"
      type: string
      description: "SHA1"
      required: false
    sha256:
      title: "SHA256"
      type: string
      description: "SHA256"
      required: false
    md5:
      title: "MD5"
      type: string
      description: "MD5"
      required: false
    globalPrevalence:
      title: "Global Prevalence"
      type: integer
      description: "Global prevalence"
      required: false
    globalFirstObserved:
      title: "Global First Observed"
      type: string
      description: "Global first observed"
      required: false
    globalLastObserved:
      title: "Global Last Observed"
      type: string
      description: "Global last observed"
      required: false
    size:
      title: "Size"
      type: integer
      description: "Size"
      required: false
    fileType:
      title: "File Type"
      type: string
      description: "File type"
      required: false
    isPeFile:
      title: "Is PE File"
      type: boolean
      description: "Is PE File"
      required: false
    filePublisher:
      title: "File Publisher"
      type: string
      description: "File publisher"
      required: false
    fileProductName:
      title: "File Product Name"
      type: string
      description: "File product name"
      required: false
    signer:
      title: "Signer"
      type: string
      description: "Signer"
      required: false
    issuer:
      title: "Issuer"
      type: string
      description: "Issuer"
      required: false
    signerHash:
      title: "Signer Hash"
      type: string
      description: "Signer hash"
      required: false
    isValidCertificate:
      title: "Is Valid Certificate"
      type: boolean
      description: "Is valid certificate"
      required: false
    determinationType:
      title: "Determination Type"
      type: string
      description: "Determination type"
      required: false
    determinationValue:
      title: "Determination Value"
      type: string
      description: "Determination value"
      required: false

  machine_software:
     id:
       title: ID
       type: string
       description: ID
       required: false
     computerDnsName:
       title: Computer DNS Name
       type: string
       description: Computer DNS name
       required: false
     osPlatform:
       title: OS Platform
       type: string
       description: OS platform
       required: false
     rbacGroupName:
       title: RBAC Group Name
       type: string
       description: RBAC group name
       required: false
     rbacGroupId:
       title: RBAC Group ID
       type: number
       description: RBAC group ID
       required: false
  machine:
     agentVersion:
       title: "Agent Version"
       type: string
       description: "Agent version"
       required: false
     computerDnsName:
       title: "Computer DNS Name"
       type: string
       description: "Computer DNS name"
       required: false
     exposureLevel:
       title: "Exposure Level"
       type: string
       description: "Exposure level"
       required: false
     firstSeen:
       title: "First Seen"
       type: string
       description: "First seen"
       required: false
     healthStatus:
       title: "Health Status"
       type: string
       description: "Health status"
       required: false
     id:
       title: "ID"
       type: string
       description: "ID"
       required: false
     lastExternalIpAddress:
       title: "Last External IP Address"
       type: string
       description: "Last external IP address"
       required: false
     lastIpAddress:
       title: "Last IP Address"
       type: string
       description: "Last IP address"
       required: false
     lastSeen:
       title: "Last Seen"
       type: string
       description: "Last seen"
       required: false
     osBuild:
       title: "OS Build"
       type: integer
       description: "OS build"
       required: false
     osPlatform:
       title: "OS Platform"
       type: string
       description: "OS platform"
       required: false
     osProcessor:
       title: "OS Processor"
       type: string
       description: "OS processor"
       required: false
     rbacGroupId:
       title: "RBAC Group ID"
       type: integer
       description: "RBAC group ID"
       required: false
     riskScore:
       title: "Risk Score"
       type: string
       description: "Risk score"
       required: false
     version:
       title: "Version"
       type: string
       description: "Version"
       required: false
     machineTags:
       title: "Machine Tags"
       type: '[]string'
       description: "Machine Tags"
       required: false
  machine_action:
     creationDateTimeUtc:
       title: "Creation Date Time UTC"
       type: string
       description: "Creation date time UTC"
       required: false
     errorHResult:
       title: "Error HResult"
       type: integer
       description: "Error HResult"
       required: false
     id:
       title: "ID"
       type: string
       description: "ID"
       required: false
     lastUpdateDateTimeUtc:
       title: "Last Update Date Time UTC"
       type: string
       description: "Last update date time UTC"
       required: false
     machineId:
       title: "Machine ID"
       type: string
       description: "Machine ID"
       required: false
     requestor:
       title: "Requestor"
       type: string
       description: "Requestor"
       required: false
     requestorComment:
       title: "Requestor Comment"
       type: string
       description: "Requestor comment"
       required: false
     status:
       title: "Status"
       type: string
       description: "Status"
       required: false

connection:
  application_id:
    title: Application ID
    description: Application (client) ID
    type: string
    required: true
    example: a74dfb10-i33o-44e1-ba87-5fn2bb4e6b4d
    order: 1
  application_secret:
    title: Application Secret
    description: Application secret
    type: credential_secret_key
    required: true
    example: kQDFcZoJYmxJpiS1x7rdyleyNFwhvLgcOZCkYG+5=
    order: 2
  directory_id:
    title: Directory ID
    description: Directory (tenant) ID
    type: string
    required: true
    example: 3a522933-ae5e-2b63-96ab-3c004b4f7f10
    order: 3

actions:
  get_machine_information:
    title: Get Machine Information
    description: Get details about a machine with its ID
    input:
      machine:
        title: Machine
        description: Machine IP address, hostname and machine ID
        type: string
        example: 2df36d707c1ee5084cef77f3dbfc95db65bc4a73
        required: true
    output:
      machine:
        title: Machine
        description: Machine information
        type: machine
        required: true
  get_file_id_from_alert_id:
    title: Get Files from Alert
    description: Retrieve a list of file information objects related to an alert
    input:
      alert_id:
        type: string
        title: Alert ID
        description: Alert ID to get files from
        example: da637293198146839977_2089064327
        required: true
    output:
      file_list:
        title: File Information
        description: The file ID related to the given alert ID
        type: "[]file_type"
        required: true
  isolate_machine:
    title: Isolate Machine
    description: Isolate a machine from the network
    input:
      machine:
        title: Machine
        description: Machine IP address, hostname and machine ID
        type: string
        example: 2df36d707c1ee5084cef77f3dbfc95db65bc4a73
        required: true
      isolation_type:
        type: string
        description: Type of isolation to perform on target machine
        title: Isolation Type
        required: true
        example: Full
        enum:
        - Full
        - Selective
      comment:
        type: string
        title: Comment
        description: Comment to associate with the isolation action
        example: Isolated by InsightConnect
        required: true
    output:
      machine_isolation_response:
        type: machine_action
        title: Machine Action Response
        description: A response that includes the result of the action, and supplemental information about the action taken
        required: true
  unisolate_machine:
    title: Unisolate Machine
    description: Restore network connectivity to a machine
    input:
      machine:
        title: Machine
        description: Machine IP address, hostname and machine ID
        type: string
        example: 2df36d707c1ee5084cef77f3dbfc95db65bc4a73
        required: true
      comment:
        type: string
        title: Comment
        description: Comment to associate with the unisolate action
        example: Unisolated by InsightConnect
        required: true
    output:
      machine_isolation_response:
        type: machine_action
        title: Machine Action Response
        description: A response that includes the result of the action, and supplemental
          information about the action taken
        required: true
  stop_and_quarantine_file:
    title: Stop and Quarantine File
    description: Stop the execution of a file on a machine and delete it
    input:
      machine:
        title: Machine
        description: Machine IP address, hostname and machine ID
        type: string
        example: 2df36d707c1ee5084cef77f3dbfc95db65bc4a73
        required: true
      comment:
        type: string
        title: Comment
        description: Comment to associate with the stop and quarantine action
        example: InsightConnect has stopped a file.
        required: true
      sha1:
        type: string
        title: SHA1 Hash
        description: SHA1 hash of the file to stop and quarantine on the machine
        example: ad0c0f2fa80411788e81a4567d1d8758b83cd76e
        required: true
    output:
      stop_and_quarantine_response:
        type: machine_action
        title: Stop and Quarantine Response
        description: A response that includes the result of the action, and supplemental
          information about the action taken
        required: true
  run_antivirus_scan:
    title: Run Antivirus Scan
    description: Initiate a Windows Defender Antivirus scan on a machine
    input:
      machine:
        title: Machine
        description: Machine IP address, hostname and machine ID
        type: string
        example: 2df36d707c1ee5084cef77f3dbfc95db65bc4a73
        required: true
      comment:
        type: string
        title: Comment
        description: Comment to associate with the antivirus scan action
        example: InsightConnect has started an antivirus scan.
        required: true
      scan_type:
        type: string
        title: Scan Type
        description: The type of antivirus scan to run
        required: true
        example: Full
        enum:
        - Full
        - Quick
    output:
      machine_action_response:
        type: machine_action
        title: Machine Action Response
        description: A response that includes the result of the action, and supplemental
          information about the action taken
        required: true
  get_machine_action:
    title: Get Machine Action
    description: Retrieve details about an action taken on a machine
    input:
      action_id:
        type: string
        title: Action ID
        description: Action ID
        example: ffd1f0cb-68ad-44ea-bf90-d01061b965ec
        required: true
    output:
      machine_action_response:
        type: machine_action
        title: Machine Action Response
        description: A response that includes the result of the action, and supplemental
          information about the action taken
        required: true
  find_machines_with_installed_software:
    title: Find Machines with Installed Software
    description: Retrieve a list of device references that have specific software installed
    input:
      software:
        title: Software
        description: Name of the software to be searched
        type: string
        required: true
        example: microsoft-_-edge
    output:
      machines:
        title: Machines
        description: List of machines with provided software
        type: '[]machine_software'
        required: true

triggers:
  get_alert_matching_key:
    title: Get Alerts Matching Key
    description: Get alerts that match a given key to its value
    input:
      key:
        type: string
        description: The key to look for in the alert. This key must match the case shown in the example output section in help
        example: assignedTo
        required: true
        order: 1
      value:
        type: string
        description: The value to look for in the alert. The value must match the case of the value returned
        example: user@example.com
        required: true
        order: 2
      frequency:
        type: integer
        description: Poll frequency in seconds
        default: 10
        example: 10
        required: false
        order: 3
    output:
      alert:
        title: Alert
        description: An alert that contains the given key and matching value
        type: 'alert'
        required: true
  get_alerts:
    title: Get Alerts
    description: Return all new alerts
    input:
      frequency:
        type: integer
        description: Poll frequency in seconds
        default: 10
        example: 10
        required: false
    output:
      alert:
        title: Alert
        description: Alert
        type: 'alert'
        required: true
