plugin_spec_version: v2
extension: plugin
products: ["insightconnect"]
name: microsoft_atp
title: Microsoft Windows Defender ATP
description: The Windows Defender Advanced Threat Protection plugin allows Rapid7 InsightConnect users to quickly take remediation actions across their organization. This plugin can isolate machines, run virus scans, and quarantine files
version: 1.5.1
vendor: rapid7
support: community
status: []
resources:
  vendor_url: https://www.microsoft.com/
tags:
- windows
- atp
- microsoft
- defender
hub_tags:
  use_cases: [threat_detection_and_response, user_management, alerting_and_notifications, devops]
  keywords: [windows, atp, microsoft, defender]
  features: []

types:
  related_user_object:
    domainName:
      title: "Domain Name"
      description: "Domain name"
      required: false
      type: string
    userName:
      title: User Name
      description: User name
      required: false
      type: string
  alert:
    id:
      title: "Id"
      type: string
      description: "Id"
      required: false
    incidentId:
      title: "Incidentid"
      type: integer
      description: "Incidentid"
      required: false
    investigationId:
      title: "Investigationid"
      type: integer
      description: "Investigationid"
      required: false
    assignedTo:
      title: "Assignedto"
      type: string
      description: "Assignedto"
      required: false
    severity:
      title: "Severity"
      type: string
      description: "Severity"
      required: false
    status:
      title: "Status"
      type: string
      description: "Status"
      required: false
    classification:
      title: "Classification"
      type: string
      description: "Classification"
      required: false
    determination:
      title: "Determination"
      type: string
      description: "Determination"
      required: false
    investigationState:
      title: "Investigationstate"
      type: string
      description: "Investigationstate"
      required: false
    detectionSource:
      title: "Detectionsource"
      type: string
      description: "Detectionsource"
      required: false
    category:
      title: "Category"
      type: string
      description: "Category"
      required: false
    threatFamilyName:
      title: "Threatfamilyname"
      type: string
      description: "Threatfamilyname"
      required: false
    title:
      title: "Title"
      type: string
      description: "Title"
      required: false
    description:
      title: "Description"
      type: string
      description: "Description"
      required: false
    alertCreationTime:
      title: "Alertcreationtime"
      type: string
      description: "Alertcreationtime"
      required: false
    firstEventTime:
      title: "Firsteventtime"
      type: string
      description: "Firsteventtime"
      required: false
    lastEventTime:
      title: "Lasteventtime"
      type: string
      description: "Lasteventtime"
      required: false
    lastUpdateTime:
      title: "Lastupdatetime"
      type: string
      description: "Lastupdatetime"
      required: false
    resolvedTime:
      title: "Resolvedtime"
      type: string
      description: "Resolvedtime"
      required: false
    machineId:
      title: "Machineid"
      type: string
      description: "Machineid"
      required: false
    computerDnsName:
      title: "Computerdnsname"
      type: string
      description: "Computerdnsname"
      required: false
    rbacGroupName:
      title: "Rbacgroupname"
      type: string
      description: "Rbacgroupname"
      required: false
    aadTenantId:
      title: "Aadtenantid"
      type: string
      description: "Aadtenantid"
      required: false
    relatedUser:
      title: "Relateduser"
      type: related_user_object
      description: "Relateduser"
      required: false
    comments:
      title: "Comments"
      type: "[]string"
      description: "Comments"
      required: false
    evidence:
      title: "Evidence"
      type: "[]string"
      description: "Evidence"
      required: false


connection:
  application_id:
    title: Application ID
    description: Application (client) ID
    type: string
    required: true
    example: xxxxxxx-xxxxxx-xxxxx-xxxx
    order: 1
  application_secret:
    title: Application Secret
    description: Application secret
    type: credential_secret_key
    required: true
    example: xxxxxxxxxxxxxxxxxxxxx
    order: 2
  directory_id:
    title: Directory ID
    description: Directory (tenant) ID
    type: string
    required: true
    example: xxxx-xxxx-xxxx-xxxx-xxx
    order: 3

actions:
  get_machine_id_from_alert_id:
    title: Get Machine ID from Alert
    description: Retrieve the machine ID related to an alert
    input:
      alert_id:
        type: string
        title: Alert ID
        description: Alert ID to get a machine ID from
        required: true
    output:
      machine_information:
        title: Machine Information
        description: The machine ID related to the given Alert ID
        type: object
        required: true
  get_file_id_from_alert_id:
    title: Get File ID from Alert
    description: Retrieve the file ID related to an alert
    input:
      alert_id:
        type: string
        title: Alert ID
        description: Alert ID to get files from
        required: true
    output:
      file_information:
        title: File Information
        description: The file ID related to the given alert ID
        type: object
        required: true
  isolate_machine:
    title: Isolate Machine
    description: Isolate a machine from the network, but keep the connection to Windows
      ATP open
    input:
      machine_id:
        type: string
        title: Machine ID
        description: Machine ID
        required: true
      isolation_type:
        type: string
        description: Type of isolation to perform on target machine
        title: Isolation Type
        required: true
        enum:
        - Full
        - Selective
      comment:
        type: string
        title: Comment
        description: Comment to associate with the isolation action
        required: true
    output:
      machine_isolation_response:
        type: object
        title: Machine Action Response
        description: A response that includes the result of the action, and supplemental
          information about the action taken
        required: true
  unisolate_machine:
    title: Unisolate Machine
    description: Restore network connectivity to a machine
    input:
      machine_id:
        type: string
        title: Machine ID
        description: Machine ID
        required: true
      comment:
        type: string
        title: Comment
        description: Comment to associate with the unisolate action
        required: true
    output:
      machine_isolation_response:
        type: object
        title: Machine Action Response
        description: A response that includes the result of the action, and supplemental
          information about the action taken
        required: true
  stop_and_quarantine_file:
    title: Stop and Quarantine File
    description: Stop the execution of a file on a machine and delete it
    input:
      machine_id:
        type: string
        title: Machine ID
        description: Machine ID
        required: true
      comment:
        type: string
        title: Comment
        description: Comment to associate with the stop and quarantine action
        required: true
      sha1:
        type: string
        title: Sha1
        description: Sha1 of the file to stop and quarantine on the machine
        required: true
    output:
      stop_and_quarantine_response:
        type: object
        title: Stop and Quarantine Response
        description: A response that includes the result of the action, and supplemental
          information about the action taken
        required: true
  run_antivirus_scan:
    title: Run Antivirus Scan
    description: Initiate a Windows Defender Antivirus scan on a machine
    input:
      machine_id:
        type: string
        title: Machine ID
        description: Machine ID
        required: true
      comment:
        type: string
        title: Comment
        description: Comment to associate with the antivirus scan action
        required: true
      scan_type:
        type: string
        title: Scan Type
        description: The type of antivirus scan to run
        required: true
        enum:
        - Full
        - Quick
    output:
      machine_action_response:
        type: object
        title: Machine Action Response
        description: A response that includes the result of the action, and supplemental
          information about the action taken
        required: true
  get_machine_action:
    title: Get Machine Action
    description: Retrieve details about an action taken on a machine
    input:
      action_id:
        type: string
        title: Action ID
        description: Action ID
        required: true
    output:
      machine_action_response:
        type: object
        title: Machine Action Response
        description: A response that includes the result of the action, and supplemental
          information about the action taken
        required: true
triggers:
  get_alert_matching_key:
    title: Get Alerts Matching Key
    description: Get alerts that match a given key to its value
    input:
      key:
        type: string
        description: The key to look for in the alert
        required: true
      value:
        type: string
        description: The value to look for in the alert
        required: true
    output:
      results:
        title: Alerts
        description: All alerts that contain the given key and match its value
        type: 'alert'
        required: true
  get_alerts:
    title: Get Alerts
    description: Return all new alerts
    input:
      frequency:
        type: integer
        description: Poll frequency in seconds
        default: 5
        required: false
    output:
      results:
        title: Alerts
        description: All new alerts are returned
        type: 'alert'
        required: true
