{
  "logs": [{
		"bypass_status_enabled": 1682836486230,
		"enabled_by": {
			"key": "DEKU19BYSSJSOABCD123",
			"name": "Admin"
		},
		"enabled_for": {
			"key": "DUM07ZQ4LY00TABCD123",
			"name": "example-user"
		},
		"priority_event": false,
		"priority_reasons": [],
		"sekey": "SE80GVU5Z47F0ABCD123",
		"state": "new",
		"state_updated_timestamp": null,
		"surfaced_timestamp": 1682836486232,
		"triaged_as_interesting": false,
		"type": "bypass_status",
		"log_type": "trust_monitor_event"
	},
	{
		"action": "user_create",
		"description": {
			"status": "Active",
			"email": "user@example.com",
			"realname": "",
			"notes": "",
			"uname": "user"
		},
		"isotimestamp": "2023-04-30T07:52:18+00:00",
		"object": "user",
		"timestamp": 1682836490,
		"username": "API (Admin API)",
		"log_type": "administrator"
	}, {
		"action": "admin_login",
		"description": {
			"ip_address": "198.51.100.1",
			"role": "User Manager",
			"device": "+111111111",
			"factor": "push",
			"primary_auth_method": "Password"
		},
		"isotimestamp": "2023-04-30T07:53:17+00:00",
		"object": null,
		"timestamp": 1682836495,
		"username": "Admin",
		"log_type": "administrator"
	}, {
		"access_device": {
			"browser": "Chrome",
			"browser_version": "113.0.0.0",
			"epkey": null,
			"flash_version": null,
			"hostname": null,
			"ip": "198.51.100.1",
			"is_encryption_enabled": "unknown",
			"is_firewall_enabled": "unknown",
			"is_password_set": "unknown",
			"java_version": null,
			"location": {
				"city": "Los Angeles",
				"country": "United States",
				"state": "California"
			},
			"os": "Mac OS X",
			"os_version": "10.15.7",
			"security_agents": "unknown"
		},
		"adaptive_trust_assessments": {},
		"alias": "unknown",
		"application": {
			"key": "DI8CODQSMK4BXPLYS47K",
			"name": "User Portal"
		},
		"auth_device": {
			"ip": null,
			"key": "DP3PC0QBDWV78E7F7LU9",
			"location": {
				"city": null,
				"country": null,
				"state": null
			},
			"name": "Generic Smartphone"
		},
		"email": null,
		"event_type": "enrollment",
		"factor": "not_available",
		"isotimestamp": "2023-05-22T09:52:13.041420+00:00",
		"ood_software": null,
		"reason": null,
		"result": "success",
		"timestamp": 1684749133,
		"trusted_endpoint_status": "unknown",
		"txid": "9de5069c-5afe-602b-2ea0-a04b66beb2c0",
		"user": {
			"groups": [],
			"key": "DU60BNA27X94XEOYB5VX",
			"name": "new-user"
		},
		"log_type": "authentication"
	},
	{
        "access_device": {
          "browser": "Chrome",
          "browser_version": "113.0.0.0",
          "epkey": null,
          "flash_version": null,
          "hostname": null,
          "ip": "198.51.100.1",
          "is_encryption_enabled": "unknown",
          "is_firewall_enabled": "unknown",
          "is_password_set": "unknown",
          "java_version": null,
          "location": {
            "city": "Los Angeles",
            "country": "United States",
            "state": "California"
          },
          "os": "Mac OS X",
          "os_version": "10.15.7",
          "security_agents": "unknown"
        },
        "adaptive_trust_assessments": {},
        "alias": "unknown",
        "application": {
          "key": "DI8CODQSMK4BXPLYS47K",
          "name": "User Portal"
        },
        "auth_device": {
          "ip": null,
          "key": "DPS4SII7YZ7ISQITTBE4",
          "location": {
            "city": null,
            "country": null,
            "state": null
          },
          "name": "+111111111"
        },
        "email": null,
        "event_type": "enrollment",
        "factor": "not_available",
        "isotimestamp": "2023-05-17T10:04:19.369345+00:00",
        "ood_software": null,
        "reason": null,
        "result": "success",
        "timestamp": 1684317859,
        "trusted_endpoint_status": "unknown",
        "txid": "9de5069c-5afe-602b-2ea0-a04b66beb2c0",
        "user": {
          "groups": [
            "Test Group"
          ],
          "key": "DUWZR0IUOT27EPXSCOI9",
          "name": "example-user"
        },
        "log_type": "authentication"
      }
],
  "state": {
    "trust_monitor_last_log_timestamp": 1682836486232,
    "previous_trust_monitor_event_hashes": [
      "b7db98ed56420f228cf72b3b80a26c44e14e0dec"
    ],
    "trust_monitor_next_page_params": {
      "limit": "200",
      "maxtime": "1682929966000",
      "mintime": "1682843686000",
      "offset": "1591014"
     },
    "admin_logs_last_log_timestamp": 1682929966,
    "previous_admin_log_hashes": [
      "cd9aa0fc02dd4a4538a3368025b2fab7480fbc7a",
      "79ac88bf9a2b241fc385a1501b614c39cdf7cd8c"
    ],
    "auth_logs_last_log_timestamp": 1684749133,
    "previous_auth_log_hashes": [
      "12f93a8c7ec4baebeb6572636552bf82f8d6eada",
      "17579ab1c166c6ac604c24f798deb5bc54e88029"
    ],
    "auth_logs_next_page_params": {
      "limit": "1000",
      "maxtime": "1682929966000",
      "mintime": "1682843686000",
      "sort": "ts:asc",
      "next_offset": "1683730665255,9de5069c-5afe-602b-2ea0-a04b66beb2c0"
    }
  },
  "status_code": 200
}
