{
  "logs": [{
		"bypass_status_enabled": 1682836486330,
		"enabled_by": {
			"key": "DEKU19BYSSJSOABCD123",
			"name": "Admin"
		},
		"enabled_for": {
			"key": "DUTQPHO6GIQI3ABCD123",
			"name": "example-user2"
		},
		"priority_event": false,
		"priority_reasons": [],
		"sekey": "SETHF3RH69P1JABCD123",
		"state": "new",
		"state_updated_timestamp": null,
		"surfaced_timestamp": 1682836486335,
		"triaged_as_interesting": false,
		"type": "bypass_status",
		"log_type": "trust_monitor_event"
	},
	{
		"action": "user_create",
		"description": {
			"status": "Active",
			"email": "user@example.com",
			"realname": "",
			"notes": "",
			"uname": "user"
		},
		"isotimestamp": "2023-04-30T07:52:18+00:00",
		"object": "user",
		"timestamp": 1682836490,
		"username": "API (Admin API)",
		"log_type": "administrator"
	},
	{
		"action": "admin_login",
		"description": {
			"ip_address": "198.51.100.1",
			"role": "User Manager",
			"device": "+111111111",
			"factor": "push",
			"primary_auth_method": "Password"
		},
		"isotimestamp": "2023-04-30T07:53:17+00:00",
		"object": null,
		"timestamp": 1682836495,
		"username": "Admin",
		"log_type": "administrator"
	},
	{
		"access_device": {
			"browser": "Chrome",
			"browser_version": "113.0.0.0",
			"epkey": null,
			"flash_version": null,
			"hostname": null,
			"ip": "198.51.100.1",
			"is_encryption_enabled": true,
			"is_firewall_enabled": true,
			"is_password_set": true,
			"java_version": null,
			"location": {
				"city": "Los Angeles",
				"country": "United States",
				"state": "California"
			},
			"os": "Mac OS X",
			"os_version": "10.15.7"
		},
		"adaptive_trust_assessments": {},
		"alias": "unknown",
		"application": {
			"key": "DI8CODQSMK4BXPLYS47K",
			"name": "User Portal"
		},
		"auth_device": {
			"ip": null,
			"key": "DPAVQAJMU3BW0LV7O234",
			"location": {
				"city": null,
				"country": null,
				"state": null
			},
			"name": "Generic Smartphone"
		},
		"email": null,
		"event_type": "enrollment",
		"factor": "not_available",
		"isotimestamp": "2023-05-29T11:07:38.631165+00:00",
		"ood_software": null,
		"reason": null,
		"result": "success",
		"timestamp": 1685358458,
		"trusted_endpoint_status": "unknown",
		"txid": "9de5069c-5afe-602b-2ea0-a04b66beb2c1",
		"user": {
			"groups": ["Test Group"],
			"key": "DUOR48RKV2AYN7YVS9BT",
			"name": "example-user2"
		},
		"log_type": "authentication"
	}
],
  "state": {
    "auth_logs_next_page_params": {
      "limit": "1000",
      "maxtime": "1682930026000",
      "mintime": "1682843686000",
      "next_offset": "1683730665255,9de5069c-5afe-602b-2ea0-a04b66beb2c0",
      "sort": "ts:asc"
    },
    "previous_admin_log_hashes": [
      "cd9aa0fc02dd4a4538a3368025b2fab7480fbc7a",
      "79ac88bf9a2b241fc385a1501b614c39cdf7cd8c"
    ],
    "previous_auth_log_hashes": [
      "cb5d554f5ef06cfe57b75eac4ce851dcc8ba064e"
    ],
    "previous_trust_monitor_event_hashes": [
      "985ddf6ee4da694f22141bd45e20e09a4b8c87d0"
    ],
    "trust_monitor_last_log_timestamp": 1682930026000,
    "admin_logs_last_log_timestamp": 1682930026,
    "auth_logs_last_log_timestamp": 1685358458
  },
  "status_code": 200
}
