# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Get a full sandbox report"


class Input:
    IDS = "ids"


class Output:
    REPORTS = "reports"


class GetFullReportInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "ids": {
      "type": "array",
      "title": "IDs",
      "description": "List of summary IDs. Find a summary ID from the response when submitting a malware sample or search with `Get Reports IDs` action",
      "items": {
        "type": "string"
      },
      "order": 1
    }
  },
  "required": [
    "ids"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetFullReportOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "reports": {
      "type": "array",
      "title": "Reports",
      "description": "List of sandbox reports",
      "items": {
        "$ref": "#/definitions/report"
      },
      "order": 1
    }
  },
  "required": [
    "reports"
  ],
  "definitions": {
    "report": {
      "type": "object",
      "title": "report",
      "properties": {
        "id": {
          "type": "string",
          "title": "ID",
          "description": "ID of the report",
          "order": 1
        },
        "cid": {
          "type": "string",
          "title": "CID",
          "description": "CID of the report",
          "order": 2
        },
        "createdTimestamp": {
          "type": "string",
          "format": "date-time",
          "displayType": "date",
          "title": "Created Timestamp",
          "description": "Time when the report was created",
          "order": 3
        },
        "origin": {
          "type": "string",
          "title": "Origin",
          "description": "Origin",
          "order": 4
        },
        "userId": {
          "type": "string",
          "title": "User ID",
          "description": "ID of the user",
          "order": 5
        },
        "userName": {
          "type": "string",
          "title": "User Name",
          "description": "Name of the user",
          "order": 6
        },
        "userUuid": {
          "type": "string",
          "title": "User UUID",
          "description": "UUID of the user",
          "order": 7
        },
        "verdict": {
          "type": "string",
          "title": "Verdict",
          "description": "Verdict of the report",
          "order": 8
        },
        "iocReportStrictCsvArtifactId": {
          "type": "string",
          "title": "IOC Report Strict CSV Artifact ID",
          "description": "IOC report strict CSV artifact ID",
          "order": 9
        },
        "iocReportBroadCsvArtifactId": {
          "type": "string",
          "title": "IOC Report Broad CSV Artifact ID",
          "description": "IOC report broad CSV artifact ID",
          "order": 10
        },
        "iocReportStrictJsonArtifactId": {
          "type": "string",
          "title": "IOC Report Strict JSON Artifact ID",
          "description": "IOC report strict JSON artifact ID",
          "order": 11
        },
        "iocReportBroadJsonArtifactId": {
          "type": "string",
          "title": "IOC Report Broad JSON Artifact ID",
          "description": "IOC report broad JSON artifact ID",
          "order": 12
        },
        "iocReportStrictStixArtifactId": {
          "type": "string",
          "title": "IOC Report Strict STIX Artifact ID",
          "description": "IOC report strict STIX artifact ID",
          "order": 13
        },
        "iocReportBroadStixArtifactId": {
          "type": "string",
          "title": "IOC Report Broad STIX Artifact ID",
          "description": "IOC report broad STIX artifact ID",
          "order": 14
        },
        "iocReportStrictMaecArtifactId": {
          "type": "string",
          "title": "IOC Report Strict Maec Artifact ID",
          "description": "IOC report strict maec artifact ID",
          "order": 15
        },
        "iocReportBroadMaecArtifactId": {
          "type": "string",
          "title": "IOC Report Broad Maec Artifact ID",
          "description": "IOC report broad maec artifact ID",
          "order": 16
        },
        "sandbox": {
          "type": "array",
          "title": "Sandbox",
          "description": "Sandbox details",
          "items": {
            "$ref": "#/definitions/sandbox"
          },
          "order": 17
        },
        "malquery": {
          "type": "array",
          "title": "Malquery",
          "description": "Malquery",
          "items": {
            "$ref": "#/definitions/malquery"
          },
          "order": 18
        }
      }
    },
    "sandbox": {
      "type": "object",
      "title": "sandbox",
      "properties": {
        "sha256": {
          "type": "string",
          "title": "SHA256",
          "description": "SHA256",
          "order": 1
        },
        "environmentId": {
          "type": "integer",
          "title": "Environment ID",
          "description": "Environment ID",
          "order": 2
        },
        "environmentDescription": {
          "type": "string",
          "title": "Environment Description",
          "description": "Environment description",
          "order": 3
        },
        "fileSize": {
          "type": "integer",
          "title": "File Size",
          "description": "File size",
          "order": 4
        },
        "fileType": {
          "type": "string",
          "title": "File Type",
          "description": "File type",
          "order": 5
        },
        "fileTypeShort": {
          "type": "array",
          "title": "File Type Short",
          "description": "File type short",
          "items": {
            "type": "string"
          },
          "order": 6
        },
        "submitName": {
          "type": "string",
          "title": "Submit Name",
          "description": "Submit name",
          "order": 7
        },
        "submitUrl": {
          "type": "string",
          "title": "Submit URL",
          "description": "Submit URL",
          "order": 8
        },
        "submissionType": {
          "type": "string",
          "title": "Submission Type",
          "description": "Submission type",
          "order": 9
        },
        "verdict": {
          "type": "string",
          "title": "Verdict",
          "description": "Verdict",
          "order": 10
        },
        "windowsVersionName": {
          "type": "string",
          "title": "Windows Version Name",
          "description": "Windows version name",
          "order": 11
        },
        "windowsVersionEdition": {
          "type": "string",
          "title": "Windows Version Edition",
          "description": "Windows version edition",
          "order": 12
        },
        "windowsVersionServicePack": {
          "type": "string",
          "title": "Windows Version Service Pack",
          "description": "Windows version service pack",
          "order": 13
        },
        "windowsVersionVersion": {
          "type": "string",
          "title": "Windows Version Version",
          "description": "Windows version version",
          "order": 14
        },
        "windowsVersionBitness": {
          "type": "integer",
          "title": "Windows Version Bitness",
          "description": "Windows version bitness",
          "order": 15
        },
        "extractedFiles": {
          "type": "array",
          "title": "Extracted Files",
          "description": "Extracted files",
          "items": {
            "$ref": "#/definitions/extractedFiles"
          },
          "order": 16
        },
        "extractedInterestingStrings": {
          "type": "array",
          "title": "Extracted Interesting Strings",
          "description": "Extracted interesting strings",
          "items": {
            "$ref": "#/definitions/extractedInterestingStrings"
          },
          "order": 17
        },
        "signatures": {
          "type": "array",
          "title": "Signatures",
          "description": "Signatures",
          "items": {
            "$ref": "#/definitions/signature"
          },
          "order": 18
        },
        "processes": {
          "type": "array",
          "title": "Processes",
          "description": "Processes",
          "items": {
            "$ref": "#/definitions/process"
          },
          "order": 19
        },
        "screenshotsArtifactIds": {
          "type": "array",
          "title": "Screenshots Artifact IDs",
          "description": "Screenshots artifact IDs",
          "items": {
            "type": "string"
          },
          "order": 20
        },
        "architecture": {
          "type": "string",
          "title": "Architecture",
          "description": "Architecture",
          "order": 21
        },
        "sampleFlags": {
          "type": "array",
          "title": "Sample Flags",
          "description": "Sample flags",
          "items": {
            "type": "string"
          },
          "order": 22
        },
        "pcapReportArtifactId": {
          "type": "string",
          "title": "PCAP Report Artifact ID",
          "description": "PCAP report artifact ID",
          "order": 23
        },
        "memoryStringsArtifactId": {
          "type": "string",
          "title": "Memory Strings Artifact ID",
          "description": "Memory strings artifact ID",
          "order": 24
        },
        "memoryDumpsArtifactId": {
          "type": "string",
          "title": "Memory Dumps Artifact ID",
          "description": "Memory dumps artifact ID",
          "order": 25
        },
        "networkSettings": {
          "type": "string",
          "title": "Network Settings",
          "description": "Network settings",
          "order": 26
        },
        "errorMessage": {
          "type": "string",
          "title": "Error Message",
          "description": "Error message",
          "order": 27
        },
        "errorType": {
          "type": "string",
          "title": "Error Type",
          "description": "Error type",
          "order": 28
        },
        "errorOrigin": {
          "type": "string",
          "title": "Error Origin",
          "description": "Error origin",
          "order": 29
        }
      }
    },
    "extractedFiles": {
      "type": "object",
      "title": "extractedFiles",
      "properties": {
        "filePath": {
          "type": "string",
          "title": "File Path",
          "description": "File path",
          "order": 1
        },
        "fileSize": {
          "type": "integer",
          "title": "File Size",
          "description": "File size",
          "order": 2
        },
        "sha256": {
          "type": "string",
          "title": "SHA256",
          "description": "SHA256",
          "order": 3
        },
        "md5": {
          "type": "string",
          "title": "MD5",
          "description": "MD5",
          "order": 4
        },
        "sha1": {
          "type": "string",
          "title": "SHA1",
          "description": "SHA1",
          "order": 5
        },
        "runtimeProcess": {
          "type": "string",
          "title": "Runtime Process",
          "description": "Runtime process",
          "order": 6
        },
        "typeTags": {
          "type": "array",
          "title": "Type Tags",
          "description": "Type tags",
          "items": {
            "type": "string"
          },
          "order": 7
        },
        "threatLevelReadable": {
          "type": "string",
          "title": "Threat Level Readable",
          "description": "Threat level readable",
          "order": 8
        },
        "description": {
          "type": "string",
          "title": "Description",
          "description": "Description",
          "order": 9
        }
      }
    },
    "extractedInterestingStrings": {
      "type": "object",
      "title": "extractedInterestingStrings",
      "properties": {
        "value": {
          "type": "string",
          "title": "Value",
          "description": "Value",
          "order": 1
        },
        "type": {
          "type": "string",
          "title": "Type",
          "description": "Type",
          "order": 2
        },
        "source": {
          "type": "string",
          "title": "Source",
          "description": "Source",
          "order": 3
        },
        "process": {
          "type": "string",
          "title": "Process",
          "description": "Process",
          "order": 4
        }
      }
    },
    "signature": {
      "type": "object",
      "title": "signature",
      "properties": {
        "threatLevelHuman": {
          "type": "string",
          "title": "Threat Level Human",
          "description": "Threat level human",
          "order": 1
        },
        "category": {
          "type": "string",
          "title": "Category",
          "description": "Category",
          "order": 2
        },
        "identifier": {
          "type": "string",
          "title": "Identifier",
          "description": "Identifier",
          "order": 3
        },
        "type": {
          "type": "integer",
          "title": "Type",
          "description": "Type",
          "order": 4
        },
        "relevance": {
          "type": "integer",
          "title": "Relevance",
          "description": "Relevance",
          "order": 5
        },
        "description": {
          "type": "string",
          "title": "Description",
          "description": "Description",
          "order": 6
        },
        "origin": {
          "type": "string",
          "title": "Origin",
          "description": "Origin",
          "order": 7
        }
      }
    },
    "process": {
      "type": "object",
      "title": "process",
      "properties": {
        "uid": {
          "type": "string",
          "title": "UID",
          "description": "UID",
          "order": 1
        },
        "normalizedPath": {
          "type": "string",
          "title": "Normalized Path",
          "description": "Normalized path",
          "order": 2
        },
        "commandLine": {
          "type": "string",
          "title": "Command Line",
          "description": "Command line",
          "order": 3
        },
        "sha256": {
          "type": "string",
          "title": "SHA256",
          "description": "SHA256",
          "order": 4
        },
        "pid": {
          "type": "integer",
          "title": "PID",
          "description": "PID",
          "order": 5
        },
        "iconArtifactId": {
          "type": "string",
          "title": "Icon Artifact ID",
          "description": "Icon artifact ID",
          "order": 6
        },
        "registry": {
          "type": "array",
          "title": "Registry",
          "description": "Registry",
          "items": {
            "$ref": "#/definitions/registry"
          },
          "order": 7
        },
        "mutants": {
          "type": "array",
          "title": "Mutants",
          "description": "Mutants",
          "items": {
            "type": "string"
          },
          "order": 8
        },
        "handles": {
          "type": "array",
          "title": "Handles",
          "description": "Handles",
          "items": {
            "$ref": "#/definitions/handle"
          },
          "order": 9
        },
        "fileAccesses": {
          "type": "array",
          "title": "File Accesses",
          "description": "File accesses",
          "items": {
            "$ref": "#/definitions/fileAccess"
          },
          "order": 10
        }
      }
    },
    "registry": {
      "type": "object",
      "title": "registry",
      "properties": {
        "operation": {
          "type": "string",
          "title": "Operation",
          "description": "Operation",
          "order": 1
        },
        "path": {
          "type": "string",
          "title": "Path",
          "description": "Path",
          "order": 2
        },
        "key": {
          "type": "string",
          "title": "Key",
          "description": "Key",
          "order": 3
        },
        "status": {
          "type": "string",
          "title": "Status",
          "description": "Status",
          "order": 4
        },
        "statusHumanReadable": {
          "type": "string",
          "title": "Status Human Readable",
          "description": "Status human readable",
          "order": 5
        }
      }
    },
    "handle": {
      "type": "object",
      "title": "handle",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 1
        },
        "type": {
          "type": "string",
          "title": "Type",
          "description": "Type",
          "order": 2
        },
        "path": {
          "type": "string",
          "title": "Path",
          "description": "Path",
          "order": 3
        }
      }
    },
    "fileAccess": {
      "type": "object",
      "title": "fileAccess",
      "properties": {
        "type": {
          "type": "string",
          "title": "Type",
          "description": "Type",
          "order": 1
        },
        "path": {
          "type": "string",
          "title": "Path",
          "description": "Path",
          "order": 2
        },
        "mask": {
          "type": "string",
          "title": "Mask",
          "description": "Mask",
          "order": 3
        }
      }
    },
    "malquery": {
      "type": "object",
      "title": "malquery",
      "properties": {
        "verdict": {
          "type": "string",
          "title": "Verdict",
          "description": "Verdict",
          "order": 1
        },
        "input": {
          "type": "string",
          "title": "Input",
          "description": "Input",
          "order": 2
        },
        "type": {
          "type": "string",
          "title": "Type",
          "description": "Type",
          "order": 3
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
