{
  "max_results": "20",
  "prefix": "m",
  "containers": [
    {
      "name": "first",
      "properties": {
        "last_modified": "Wed, 08 Jun 2022 12:48:16 GMT",
        "public_access": "blob",
        "etag": "\"0x8DA494D2826EA21\""
      },
      "metadata": {}
    },
    {
      "name": "second",
      "properties": {
        "last_modified": "Wed, 08 Jun 2022 12:44:35 GMT",
        "etag": "\"0x8DA494CA481C42D\""
      },
      "metadata": {}
    }
  ]
}