{
  "delimiter": "plugin",
  "max_results": "20",
  "blobs": [
    {
      "name": "AdEin.PNG",
      "version_id": "2022-06-14T12:32:03.9792491Z",
      "is_current_version": "true",
      "properties": {
        "creation_time": "Wed, 25 May 2022 13:03:28 GMT",
        "tag_count": "2",
        "server_encrypted": "true",
        "last_modified": "Tue, 14 Jun 2022 12:32:03 GMT",
        "content_type": "image/png",
        "blob_type": "BlockBlob",
        "access_tier": "Hot",
        "etag": "0x8DA4E01E2EE85B"
      },
      "metadata": {
        "aaa": "f",
        "f": "a"
      },
      "tags": [
        {
          "Key": "fds",
          "Value": "dfsg"
        },
        {
          "Key": "g",
          "Value": "zz"
        }
      ]
    },
    {
      "name": "myblob2",
      "properties": {
        "creation_time": "Fri, 20 May 2022 15:42:23 GMT",
        "server_encrypted": "true",
        "last_modified": "Fri, 20 May 2022 15:42:23 GMT",
        "content_type": "application/octet-stream",
        "blob_type": "BlockBlob",
        "access_tier": "Hot",
        "etag": "0x8DA3A7754265C1"
      },
      "metadata": {},
      "tags": []
    },
    {
      "name": "mylob2",
      "version_id": "2022-06-15T08:35:15.4662051Z",
      "is_current_version": "true",
      "properties": {
        "creation_time": "Wed, 15 Jun 2022 08:35:15 GMT",
        "server_encrypted": "true",
        "last_modified": "Wed, 15 Jun 2022 08:35:15 GMT",
        "content_type": "application/octet-stream",
        "blob_type": "BlockBlob",
        "access_tier": "Hot",
        "etag": "0x8DA4EA9F8A9C6A3"
      },
      "metadata": {},
      "tags": []
    }
  ],
  "blobs_with_delimiter_match": [
    "aappeennddapi_bldfffob_plugin",
    "api_bldob_plugin",
    "api_blob_plugin"
  ]
}