# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT

from .create_line_plot.action import CreateLinePlot

from .create_scatter_plot.action import CreateScatterPlot

from .create_distribution_plot.action import CreateDistributionPlot

from .create_joint_plot.action import CreateJointPlot

from .create_pair_plot.action import CreatePairPlot
