# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Component:
    DESCRIPTION = "Poll feed for latest event"


class Input:
    
    FREQUENCY = "frequency"
    

class Output:
    
    RESULTS = "results"
    

class PollInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "frequency": {
      "type": "integer",
      "title": "Frequency",
      "description": "How frequently (in seconds) to poll for new entries",
      "default": 15,
      "order": 1
    }
  },
  "required": [
    "frequency"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class PollOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "results": {
      "type": "object",
      "title": "Results",
      "description": "RSS data",
      "order": 1
    }
  },
  "required": [
    "results"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
