# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Input:
    API_KEY = "api_key"
    APPLICATION_ID = "application_id"
    SKIP_ADDRESS_IPS = "skip_address_ips"
    SKIP_ENTITY_IDS = "skip_entity_ids"
    SKIP_HOST_NAMES = "skip_host_names"
    SKIP_MAC_ADDRESSES = "skip_mac_addresses"
    URL = "url"
    

class ConnectionSchema(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "api_key": {
      "$ref": "#/definitions/credential_secret_key",
      "title": "API Key",
      "description": "API key paired with the Application ID e.g. CU1874A2-G782-47X1-B6J3-1014A92624BC",
      "order": 3
    },
    "application_id": {
      "$ref": "#/definitions/credential_secret_key",
      "title": "Application ID",
      "description": "Application ID to communicate to the Apex Security Manager e.g. 909D88H7-3458-42RN-92FF-012V3CU3D294",
      "order": 2
    },
    "skip_address_ips": {
      "type": "array",
      "title": "Skip Address IPs",
      "description": "Skip address ips on isolate and uninstall actions",
      "items": {
        "type": "string"
      },
      "order": 6
    },
    "skip_entity_ids": {
      "type": "array",
      "title": "Skip Entity ID",
      "description": "Skip entity ids on isolate and uninstall actions",
      "items": {
        "type": "string"
      },
      "order": 4
    },
    "skip_host_names": {
      "type": "array",
      "title": "Skip Host Names",
      "description": "Skip host names on isolate and uninstall actions",
      "items": {
        "type": "string"
      },
      "order": 5
    },
    "skip_mac_addresses": {
      "type": "array",
      "title": "Skip MAC Addresses",
      "description": "Skip MAC addresses on isolate and uninstall actions",
      "items": {
        "type": "string"
      },
      "order": 7
    },
    "url": {
      "type": "string",
      "title": "URL",
      "description": "URL with port number of the Apex Security Manager.",
      "order": 1
    }
  },
  "required": [
    "api_key",
    "application_id",
    "url"
  ],
  "definitions": {
    "credential_secret_key": {
      "id": "credential_secret_key",
      "type": "object",
      "title": "Credential: Secret Key",
      "description": "A shared secret key",
      "properties": {
        "secretKey": {
          "type": "string",
          "title": "Secret Key",
          "displayType": "password",
          "description": "The shared secret key",
          "format": "password"
        }
      },
      "required": [
        "secretKey"
      ]
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
