# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import json

import insightconnect_plugin_runtime


class Component:
    DESCRIPTION = "Trigger workflows to get leaked records feeds from Luminar"


class Input:
    FREQUENCY = "frequency"
    INITIAL_FETCH_DATE = "initial_fetch_date"


class Output:
    RESULTS = "results"


class FetchLeakedRecordsFeedsInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(
        r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "frequency": {
      "type": "integer",
      "title": "Frequency",
      "description": "Poll frequency in seconds",
      "default": 86400,
      "order": 1
    },
    "initial_fetch_date": {
      "type": "string",
      "title": "Initial Fetch Date",
      "description": "The date from which the initial fetch will start. eg YYYY-MM-DD",
      "order": 2
    }
  },
  "required": [
    "initial_fetch_date"
  ],
  "definitions": {}
}
    """
    )

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class FetchLeakedRecordsFeedsOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(
        r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "results": {
      "type": "array",
      "title": "Results",
      "description": "leaked records feed results",
      "items": {
        "type": "object"
      },
      "order": 1
    }
  },
  "required": [
    "results"
  ],
  "definitions": {}
}
    """
    )

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
