plugin_spec_version: v2
extension: plugin
products: [insightconnect]
name: github_enterprise
title: GitHub Enterprise
vendor: rapid7
support: community
status: []
description: GitHub Enterprise plugin allows user management
version: 1.0.2
resources:
  source_url: https://github.com/rapid7/insightconnect-plugins/tree/master/github_enterprise
  license_url: https://github.com/rapid7/insightconnect-plugins/blob/master/LICENSE
  vendor_url: https://github.com
tags:
- github
- enterprise
- issue
- authentication
hub_tags:
  use_cases: [soar, soc_automation, user_management]
  keywords: [github, enterprise, issue, authentication]
  features: []
connection:
  credentials:
    title: GitHub Username and Password (or token)
    description: GitHub username and password (or token)
    type: credential_username_password
    required: true
  host:
    description: Address of enterprise server
    type: string
    required: true
    title: Host
actions:
  promote:
    title: Promote User
    description: Promote an ordinary user to admin
    input:
      user:
        type: string
        description: User to promote
        required: true
    output:
      status:
        title: Status
        description: Status
        type: string
        required: false
  demote:
    title: Demote User
    description: Demote admin to ordinary user
    input:
      user:
        type: string
        description: User to demote
        required: true
    output:
      status:
        title: Status
        description: Status
        type: string
        required: false
  suspend:
    title: Suspend User
    description: Suspend user from enterprise
    input:
      username:
        type: string
        description: GitHub username
        required: true
    output:
      status:
        title: Status
        description: Status
        type: string
        required: false
  unsuspend:
    title: Unsuspend User
    description: Unsuspend user from enterprise
    input:
      username:
        type: string
        description: GitHub username
        required: true
    output:
      status:
        title: Status
        description: Status
        type: string
        required: false
  organization:
    title: Create Organization
    description: Create organization in enterprise
    input:
      name:
        type: string
        description: Organization name
        required: true
      admin:
        type: string
        description: Username of who will manage this organization
        required: true
      profile_name:
        type: string
        description: Organization display name
        required: true
    output:
      status:
        title: Status
        description: Status
        type: string
        required: false
triggers:
  issue:
    title: Issue
    description: Monitor new issues
    input:
      organization:
        type: string
        description: Return issues of a specific organization
        required: false
      repository:
        type: string
        description: Return issues of a specific repository
        required: true
      frequency:
        type: integer
        description: Poll frequency in seconds
        default: 300
        required: false
      assignee:
        type: string
        description: Username of assignee
        required: false
    output:
      issues:
        title: Issues
        description: Issues
        type: object
        required: false
