plugin_spec_version: v2
extension: plugin
products: [insightconnect]
name: carbon_black_defense
title: Carbon Black Defense
description: Find events and retrieve details for specific events
version: 1.1.2
vendor: rapid7
support: rapid7
status: []
resources:
  source_url: https://github.com/rapid7/insightconnect-plugins/tree/master/carbon_black_defense
  license_url: https://github.com/rapid7/insightconnect-plugins/blob/master/LICENSE
  vendor_url: https://www.carbonblack.com/
tags:
- carbon black
- defense
- antivirus
- cloud
hub_tags:
  use_cases: [soar, soc_automation, threat_hunting, threat_detection_and_response, investigations]
  keywords: [carbon black, defense, antivirus, cloud]
  features: []
types:
  hash:
    applicationName:
      title: Application Name
      type: string
    virusName:
      title: Virus Name
      type: string
    reputationProperty:
      title: Reputation Property
      type: string
    effectiveReputation:
      title: Effective Reputation
      type: string
    applicationPath:
      title: Application Path
      type: string
    md5Hash:
      title: MD5 Hash
      type: string
    effectiveReputationSource:
      title: Effective Reputation Source
      type: string
    virusCategory:
      title: Virus Category
      type: string
    sha256Hash:
      title: SHA256 Hash
      type: string
    virusSubCategory:
      title: Virus Sub Category
      type: string
  orgDetails:
    organizationId:
      title: Organization ID
      type: integer
    organizationName:
      title: Organization Name
      type: string
    organizationType:
      title: Organization Type
      type: string
  deviceInfo:
    deviceHostName:
      description: Device Hostname
      title: Device Hostname
      type: string
    deviceId:
      description: Device ID
      title: Device ID
      type: integer
    deviceName:
      description: Device Name
      title: Device Name
      type: string
    deviceType:
      description: Device Type
      title: Device Type
      type: string
    deviceVersion:
      description: Device Version
      title: Device Version
      type: string
    email:
      description: Email
      title: Email
      type: string
    externalIpAddress:
      description: External IP Address
      title: External IP Address
      type: string
    groupName:
      description: Group Name
      title: Group Name
      type: string
    internalIpAddress:
      description: Internal IP Address
      title: Internal IP Address
      type: string
    targetPriorityCode:
      description: Target Priority Code
      title: Target Priority Code
      type: integer
    targetPriorityType:
      description: Target Priority Type
      title: Target Priority Type
      type: string
  policyAction:
    action:
      description: Policy Action
      title: Policy Action
      type: string
    applicationName:
      description: Application Name
      title: Application Name
      type: string
    reputation:
      description: Reputation
      title: Reputation
      type: string
    sha256Hash:
      description: SHA-256 Hash
      title: SHA-256 Hash
      type: string
  deviceLocation:
    areaCode:
      description: Area Code
      title: Area Code
      type: integer
    city:
      description: City
      title: City
      type: string
    countryCode:
      description: Country Code
      title: Country Code
      type: string
    countryName:
      description: Country Name
      title: Country Name
      type: string
    dmaCode:
      description: DMA Code
      title: DMA Code
      type: integer
    latitude:
      description: Latitude
      title: Latitude
      type: float
    longitude:
      description: Longitude
      title: Longitude
      type: float
    metroCode:
      description: Metro Code
      title: Metro Code
      type: integer
    postalCode:
      description: Postal Code
      title: Postal Code
      type: string
    region:
      description: Region
      title: Region
      type: string
  deviceDetails:
    agentLocation:
      description: Agent Location
      title: Agent Location
      type: string
    deviceHostName:
      description: Device Host Name
      title: Device Host Name
      type: string
    deviceId:
      description: Device ID
      title: Device ID
      type: integer
    deviceIpAddress:
      description: Device IP Address
      title: Device IP Address
      type: string
    deviceIpV4Address:
      description: Device IPv4 Address
      title: Device IPv4 Address
      type: string
    deviceLocation:
      description: Device Location
      title: Device Location
      type: deviceLocation
    deviceName:
      description: Device Name
      title: Device Name
      type: string
    deviceOwnerName:
      description: Device Owner Name
      title: Device Owner Name
      type: string
    deviceType:
      description: Device Type
      title: Device Type
      type: string
    deviceVersion:
      description: Device Version
      title: Device Version
      type: string
    email:
      description: Email
      title: Email
      type: string
    groupName:
      description: Group Name
      title: Group Name
      type: string
    targetPriorityCode:
      description: Target Priority Code
      title: Target Priority Code
      type: integer
    targetPriorityType:
      description: Target Priority Type
      title: Target Priority Type
      type: string
  netFlow:
    destAddress:
      description: Net Flow
      title: Net Flow
      type: string
    destPort:
      description: Destination Port
      title: Destination Port
      type: string
    peerFqdn:
      description: Peer Fully Qualified Domain Name
      title: Peer FQDN
      type: string
    peerIpAddress:
      description: Peer IP Address
      title: Peer IP Address
      type: string
    peerIpV4Address:
      description: Peer IPv4 Address
      title: Peer IPv4 Address
      type: string
    peerLocation:
      description: Peer Location
      title: Peer Location
      type: object
    peerSiteReputation:
      description: Peer Site Reputation
      title: Peer Site Reputation
      type: string
    service:
      description: Service
      title: Service
      type: string
    sourceAddress:
      description: Source Address
      title: Source Address
      type: string
    sourcePort:
      description: Source Port
      title: Source Port
      type: string
  parentApp:
    applicationName:
      description: Application Name
      title: Application Name
      type: string
    applicationPath:
      description: Application Path
      title: Application Path
      type: string
    effectiveReputation:
      description: Effective Reputation
      title: Effective Reputation
      type: string
    effectiveReputationSource:
      description: Effective Reputation Source
      title: Effective Reputation Source
      type: string
    md5Hash:
      description: MD5 Hash
      title: MD5 Hash
      type: string
    reputationProperty:
      description: Reputation Property
      title: Reputation Property
      type: string
    sha256Hash:
      description: SHA-256 Hash
      title: SHA-256 Hash
      type: string
    virusCategory:
      description: Virus Category
      title: Virus Category
      type: string
    virusName:
      description: Virus Name
      title: Virus Name
      type: string
    virusSubCategory:
      description: Virus Sub Category
      title: Virus Sub Category
      type: string
  processDetails:
    commandLine:
      description: Process Details
      title: Process Details
      type: string
    fullUserName:
      description: Full User Name
      title: Full User Name
      type: string
    interpreterHash:
      description: Interpreter Hash
      title: Interpreter Hash
      type: string
    interpreterName:
      description: Interpreter Name
      title: Interpreter Name
      type: string
    milisSinceProcessStart:
      description: Milliseconds since process has started
      title: Milliseconds Since Process has Started
      type: integer
    name:
      description: Name
      title: Name
      type: string
    parentCommandLine:
      description: Parent Command Line
      title: Parent Command Line
      type: string
    parentName:
      description: Parent Name
      title: Parent Name
      type: string
    parentPid:
      description: Parent Process ID
      title: Parent PID
      type: integer
    parentPrivatePid:
      description: Parent Private Process ID
      title: Parent Private PID
      type: string
    privatePid:
      description: Private Process ID
      title: Private Process ID
      type: string
    processId:
      description: Process ID
      title: Process ID
      type: integer
    targetCommandLine:
      description: Target Command Line
      title: Target Command Line
      type: string
    targetName:
      description: Target Name
      title: Target Name
      type: string
    targetPid:
      description: Target Process ID
      title: Target Process ID
      type: integer
    targetPrivatePid:
      description: Target Private Process ID
      title: Target Private PID
      type: string
    userName:
      description: User Name
      title: User Name
      type: string
  results:
    alertCategory:
      description: Alert Category
      title: Alert Category
      type: string
    alertScore:
      description: Alert Score
      title: Alert Score
      type: integer
    attackStage:
      description: Attack Stage
      title: Attack Stage
      type: string
    createTime:
      description: Create Time
      title: Create Time
      type: integer
    deviceDetails:
      description: Device Details
      title: Device Details
      type: deviceDetails
    eventId:
      description: Event ID
      title: Event ID
      type: string
    eventTime:
      description: Event Time
      title: Event Time
      type: integer
    eventType:
      description: Event Type
      title: Event Time
      type: string
    incidentId:
      description: Incident ID
      title: Incident ID
      type: string
    longDescription:
      description: Long Description
      title: Long Description
      type: string
    netFlow:
      description: Net Flow
      title: Net Flow
      type: netFlow
    parentApp:
      description: Parent Application
      title: Parent Application
      type: parentApp
    processDetails:
      description: Process Details
      title: Process Details
      type: processDetails
    registryValue:
      description: Registy Value
      title: Registy Value
      type: string
    securityEventCode:
      description: Security Event Code
      title: Security Event Code
      type: string
    selectedApp:
      description: Selected Application
      title: Selected Application
      type: parentApp
    shortDescription:
      description: Short Description
      title: Short Description
      type: string
    targetApp:
      description: Target Application
      title: Target Application
      type: parentApp
    threatIndicators:
      description: Threat Indicators
      title: Threat Indicators
      type: '[]string'
  indicators:
    applicationName:
      description: Application Name
      title: Application Name
      type: string
    indicatorName:
      description: Indicator Name
      title: Indicator Name
      type: string
    sha256Hash:
      description: SHA-256 Hash
      title: SHA-256 Hash
      type: string
  threatInfo:
    incidentId:
      description: Incident ID
      title: Incident ID
      type: string
    indicators:
      description: Indicators
      title: Indicators
      type: '[]indicators'
    score:
      description: Score
      title: Score
      type: integer
    summary:
      description: Summary
      title: Summary
      type: string
    time:
      description: Time
      title: Time
      type: integer
  notifications:
    deviceInfo:
      description: Notifications
      title: Notifications
      type: deviceInfo
    eventDescription:
      description: Event Description
      title: Event Description
      type: string
    eventId:
      description: Event ID
      title: Event ID
      type: string
    eventTime:
      description: Event Time
      title: Event Time
      type: integer
    policyAction:
      description: Policy Action
      title: Policy Action
      type: policyAction
    ruleName:
      description: Rule Name
      title: Rule Name
      type: string
    threatInfo:
      description: Threat Information
      title: Threat Information
      type: threatInfo
    type:
      description: Type
      title: Type
      type: string
    url:
      description: URL
      title: URL
      type: string
  eventInfo:
    eventId:
      title: Event ID
      type: string
    processDetails:
      title: Process Details
      type: processDetails
    eventTime:
      title: Event Time
      type: integer
    deviceSecurityEventCode:
      title: Device Security Event Code
      type: string
    killChainStatus:
      title: Kill Chain Status
      type: string
    selectedApp:
      title: Process Hash
      type: hash
    registryValue:
      title: Registry Value
      type: string
    parentApp:
      title: Parent Hash
      type: hash
    threatScore:
      title: Threat Score
      type: integer
    createTime:
      title: Create Time
      type: integer
    longDescription:
      title: Long Description
      type: string
    threatIndicators:
      title: Threat Indicators
      type: '[]string'
    securityEventCode:
      title: Security Event Code
      type: string
    deviceDetails:
      title: Device Details
      type: deviceDetails
    orgDetails:
      title: Org Details
      type: orgDetails
    eventType:
      title: Event Type
      type: string
    syslogLevel:
      title: Syslog Level
      type: object
    netFlow:
      title: Net Flow
      type: netFlow
    shortDescription:
      title: Short Description
      type: string
    targetApp:
      title: Target Hash
      type: hash
connection:
  url:
    title: URL
    type: string
    description: API URL
    default: https://api.confer.net
    required: true
  api_key:
    title: API Key
    type: credential_secret_key
    description: API key
    required: true
  connector:
    title: Connector
    type: string
    description: Connector ID
    required: true
actions:
  find_event:
    title: Find Event
    description: Retrieves all events matching the input search criteria. Response
      is a list of events in JSON format. Resulting events are sorted in descending
      order of time
    input:
      hostName:
        title: Hostname
        description: Filter on hostnames case insensitive. For example hostName=win-IA9NQ1GN8OI
          will match the hostname WIN-IA9NQ1GN8OI
        type: string
        required: false
      hostNameExact:
        title: Hostname Exact
        description: Filter on the exact hostname. For example hostName=WIN-IA9NQ1GN8OI
          will only return devices with the exact hostname WIN-IA9NQ1GN8OI but not
          a host named win-IA9NQ1GN8OI
        type: string
        required: false
      ownerName:
        title: Owners Name
        description: Filter on owner name case insensitive
        type: string
        required: false
      ownerNameExact:
        title: Owners Name Exact
        description: Same as 'Owners Name' but with case sensitivity
        type: string
        required: false
      ipAddress:
        title: IP Address
        description: Filter on events generated by a device with a given external
          or internal IP address
        type: string
        required: false
      sha256hash:
        title: SHA-256 Hash
        description: Filter on events generated by a process with the given SHA-256
          hash. Note that this hash must be lowercase
        type: string
        required: false
      applicationName:
        title: Application Name
        description: Filter on events generated by a process with the given application
          name (for example, googleupdate.exe. Note that this name must be lowercase)
        type: string
        required: false
      eventType:
        title: Event Type
        description: Filter on events with a given event type
        type: string
        enum:
        - ''
        - NETWORK
        - FILE_CREATE
        - REGISTRY_ACCESS
        - SYSTEM_API_CALL
        - CREATE_PROCESS
        - DATA_ACCESS
        - INJECT_CODE
        required: false
      searchWindow:
        title: Search Window
        description: Filter on events generated within a given relative time frame.
          Note that the default is one day if a searchWindow is not specified. Note
          that events may not be available past 30 days due to retention policies
          e.g. 4d, 2w
        type: string
        required: false
    output:
      success:
        description: Success
        title: Success
        type: boolean
        required: false
      latestTime:
        description: Latest Time
        title: Latest Time
        type: integer
        required: false
      results:
        description: Results
        title: Results
        type: '[]results'
        required: false
      elapsed:
        description: Elapsed
        title: Elapsed
        type: integer
        required: false
      message:
        description: Message
        title: Message
        type: string
        required: false
      totalResults:
        description: Total Results
        title: Total Results
        type: integer
        required: false
  get_details_for_specific_event:
    title: Get Details for Specific Event
    description: Retrieve details for an individual event given the event ID
    input:
      event_id:
        title: Event ID
        description: Event ID
        type: string
        required: true
    output:
      success:
        title: Success
        description: Success
        type: boolean
        required: false
      message:
        title: Message
        description: Message
        type: string
        required: false
      eventinfo:
        title: Event Info
        description: Detailed information on the event
        type: eventInfo
        required: false
triggers:
  get_notifications:
    title: Get Notifications
    description: Allows consumers to get alert and policy action notifications that
      a connector is subscribed to. Only API keys of type 'SIEM' can call the notifications
      API
    input:
      frequency:
        type: integer
        title: Frequency
        description: How often to poll for new notifications requests, in seconds
        default: 10
        required: true
    output:
      notifications:
        description: Collection of Notifications
        title: Notifications
        type: '[]notifications'
        required: false
      message:
        description: Notification Message
        title: Message
        type: string
        required: false
      success:
        description: Notification Success
        title: Success
        type: boolean
        required: false
