plugin_spec_version: v2
extension: plugin
products: [insightconnect]
name: jira
title: Jira
vendor: rapid7
support: rapid7
status: []
description: Automate the creation, search and management of issues, users, and alerting for Jira Software, Jira Server, and Jira ServiceDesk
version: 6.0.3
resources:
  source_url: https://github.com/rapid7/insightconnect-plugins/tree/master/jira
  license_url: https://github.com/rapid7/insightconnect-plugins/blob/master/LICENSE
  vendor_url: https://www.atlassian.com
  docs_url: https://docs.rapid7.com/insightconnect/jira
tags:
  - ticket
  - Jira
hub_tags:
  use_cases: [remediation_management, threat_detection_and_response, reporting_and_analytics]
  keywords: [ticket, jira]
  features: []
types:
  user:
    accountId:
      type: string
      title: Account ID
      description: User account ID
      required: false
    name:
      type: string
      description: User name
      required: false
    email_address:
      type: string
      description: User's email address
      required: false
    display_name:
      type: string
      description: User's display name
      required: false
    active:
      type: boolean
      description: Whether the user is active
      required: false
  comment:
    id:
      type: string
      description: Comment ID
      required: false
    body:
      type: string
      description: Body of comment
      required: false
    author:
      description: Author
      type: user
      required: false
  issue:
    id:
      type: string
      description: Issue ID
      required: false
    project:
      type: string
      description: Project
      required: false
    key:
      type: string
      description: Issue Key
      required: false
    status:
      type: string
      description: Status
      required: false
    url:
      type: string
      description: Issue URL
      required: false
    summary:
      type: string
      description: Summary
      required: false
    description:
      type: string
      description: Description
      required: false
    resolution:
      type: string
      description: Resolution
      required: false
    labels:
      type: '[]string'
      description: Labels
      required: false
    reporter:
      type: string
      description: Reporting User
      required: false
    assignee:
      type: string
      description: Assigned User
      required: false
    created_at:
      type: string
      description: Created At
      required: false
    updated_at:
      type: string
      description: Updated At
      required: false
    resolved_at:
      type: string
      description: Resolved At
      required: false
    attachments:
      type: '[]file'
      description: Attachments
      required: false
    fields:
      type: object
      description: Full list of fields
      required: false
connection:
  url:
    title: URL
    type: string
    description: Jira URL
    default: https://example.atlassian.net
    required: false
    example: https://example.atlassian.net
  user:
    title: User
    type: string
    description: Jira user email
    required: true
    example: user@example.com
  api_key:
    title: API Key
    type: credential_secret_key
    description: Jira API key (Jira password is not supported)
    required: true
    example: 9de5069c5afe602b2ea0a04b66beb2c0
actions:
  transition_issue:
    title: Transition Issue
    description: Transition an issue
    input:
      id:
        title: ID
        type: string
        description: Issue ID
        required: true
        example: 10001
      transition:
        title: Transition
        type: string
        description: ID or name of transition to perform, e.g. In Progress
        required: true
        example: 31
      comment:
        title: Comment
        type: string
        description: Comment to add
        required: false
        example: "Transition executed by InsightConnect"
      fields:
        title: Fields
        type: object
        description: 'Custom fields to assign. Fields used must be present on the screen used for project, issue, and transition type
           e.g: { "field1": { "attribute1": "value1" }, "field2": { "attribute2": "value2" }}'
        required: false
        example: '{ "fields": { "project": { "key": "TEST" }, "summary": "Test Ticket", "description": "Test ticket created from InsightConnect", "issuetype": { "name": "Story" } } }'
    output:
      success:
        title: Success
        type: boolean
        description: True if successful
        required: false
  find_issues:
    title: Find Issues
    description: Search for issues
    input:
      jql:
        title: JQL
        type: string
        description: JQL search string to use
        required: true
        example: 'project = "TEST"'
      max:
        title: Max
        type: integer
        description: Max results to return
        default: 10
        required: true
        example: 10
      get_attachments:
        title: Get Attachments
        description: Get attachments from issue
        required: false
        type: boolean
        default: false
        example: true
    output:
      issues:
        title: Issues
        type: '[]issue'
        required: false
        description: The list of found issues
  assign_issue:
    title: Assign Issue
    description: Assign an issue to a user
    input:
      id:
        title: ID
        type: string
        description: Issue ID
        required: true
        example: 10001
      assignee:
        title: Assignee
        type: string
        description: Username of assignee
        required: true
        example: user1
    output:
      success:
        title: Success
        type: boolean
        description: True if successful
        required: false
  label_issue:
    title: Label Issue
    description: Label issue
    input:
      id:
        title: ID
        type: string
        description: Issue ID
        required: true
        example: 10001
      label:
        title: Label
        type: string
        description: Label to add. To add multiple labels, separate by commas
        required: true
        example: documentation
    output:
      success:
        title: Success
        type: boolean
        description: True if successful
        required: false
  get_comments:
    title: Get Comments
    description: Retrieve all comments on an issue
    input:
      id:
        title: ID
        type: string
        description: Issue ID
        required: true
        example: TEST-1
    output:
      count:
        title: Count
        type: integer
        description: Count of comments found
        required: false
      comments:
        title: Comments
        type: '[]comment'
        description: Comments list
        required: false
  comment_issue:
    title: Comment Issue
    description: Comment on an issue
    input:
      id:
        title: ID
        type: string
        description: Issue ID
        required: true
        example: 10001
      comment:
        title: Comment
        type: string
        description: Comment to add
        required: true
        example: "This comment was added by InsightConnect"
    output:
      comment_id:
        title: Comment ID
        type: string
        description: Comment ID
        required: false
  get_issue:
    title: Get Issue
    description: Retrieve an issue
    input:
      id:
        title: ID
        type: string
        description: Issue ID
        required: true
        example: TEST-1
      get_attachments:
        title: Get Attachments
        description: Get attachments from issue
        required: false
        type: boolean
        default: false
        example: false
    output:
      found:
        title: Found
        type: boolean
        description: True if found
        required: false
      issue:
        title: Issue
        type: issue
        description: Found issue
        required: false
  find_users:
    title: Find Users
    description: Search for a set of users
    input:
      query:
        title: Query
        type: string
        description: Query String, e.g. Joe
        required: true
        example: Joe
      max:
        title: Max
        type: integer
        description: Max results to return
        default: 10
        required: true
        example: 10
    output:
      users:
        title: Users
        type: '[]user'
        required: false
        description: The list of found users
  delete_user:
    title: Delete User
    description: Delete a user account
    input:
      username:
        title: Username
        type: string
        description: Username
        required: false
        example: user1
      account_id:
        title: Account ID
        type: string
        description: Unique identifier for an Atlassian account
        required: false
        example: 5ec00968833be70b7e50df20
    output:
      success:
        title: Success
        type: boolean
        description: True if successful
        required: false
  create_user:
    title: Create User
    description: Create a user account
    input:
      username:
        title: Username
        type: string
        description: Username
        required: false
        example: user1
      email:
        title: Email
        type: string
        description: Email
        required: true
        example: user1@example.com
      password:
        title: Password
        type: string
        description: Password
        required: false
        example: mypassword
      notify:
        title: Notify
        type: boolean
        description: Notify if true
        default: false
        required: true
        enum:
          - true
          - false
        example: false
    output:
      success:
        title: Success
        type: boolean
        description: True if successful
        required: false
  attach_issue:
    title: Add Attachment to Issue
    description: Add an attachment to an issue in Jira
    input:
      id:
        title: ID
        type: string
        description: Issue ID
        required: true
        example: 10001
      attachment_bytes:
        title: Attachment Bytes
        type: bytes
        description: Attachment bytes
        required: true
        example: "TVqQAAMAAAAEAAAA//8AALgAAAAAAA..."
      attachment_filename:
        title: Attachment Filename
        type: string
        description: Attachment filename. Must end with a filetype extension if possible
        required: true
        example: document.pdf
    output:
      id:
        title: ID
        type: string
        description: ID of attachment
        required: false
  create_issue:
    title: Create Issue
    description: Create an issue in Jira
    input:
      summary:
        title: Summary
        type: string
        description: Issue summary
        required: false
        example: "Connect Jira to InsightConnect"
      type:
        title: Type
        type: string
        description: Issue type. Typical issues type include Task, Story, Epic, Bug.
          You can also specify a custom issue type. This input is case-sensitive
        default: Task
        required: false
        example: Story
      description:
        title: Description
        type: string
        description: Issue description
        required: false
        default: ''
        example: "Successfully connect Jira to InsightConnect to automate ticket management"
      project:
        title: Project
        description: Project ID
        type: string
        required: true
        example: TEST
      fields:
        title: Fields
        type: object
        description: Custom fields to assign. Fields used must be present on the same
          screen as the Create screen in Jira
        required: false
        example: '{ "fields": { "project": { "key": "TEST" }, "summary": "Test Ticket", "description": "Test ticket created from InsightConnect", "issuetype": { "name": "Story" } } }'
      attachment_bytes:
        title: Attachment Bytes
        type: bytes
        description: Attachment bytes
        required: false
        example: "TVqQAAMAAAAEAAAA//8AALgAAAAAAA..."
      attachment_filename:
        title: Attachment Filename
        type: string
        description: Attachment filename
        required: false
        example: document.pdf
    output:
      issue:
        title: Issue
        type: issue
        description: Created issue
        required: false
  edit_issue:
    title: Edit Issue
    description: Edit an issue within Jira
    input:
      id:
        title: ID
        description: Issue ID
        type: string
        required: true
        example: TEST-1
      notify:
        title: Notify
        description: Will send a notification email about the issue updated. Admin and project admins credentials need to be used to disable the notification
        type: boolean
        required: true
        default: true
        example: false
      summary:
        title: Summary
        description: Summary field on the issue
        type: string
        required: false
        example: "Connect Jira to InsightConnect for Multiple Teams"
      description:
        title: Description
        description: Description field on the issue
        type: string
        required: false
        example: "Update ticket with additional Jira information for others teams wanting to leverage InsightConnect"
      fields:
        title: Fields
        description: An object of fields and values to change
        type: object
        required: false
        example: '{ "fields": { "project": { "key": "TEST" }, "summary": "Test Ticket", "description": "Test ticket created from InsightConnect", "issuetype": { "name": "Story" } } }'
      update:
        title: Update
        description:  An object that contains update operations to apply, see examples at https://developer.atlassian.com/server/jira/platform/updating-an-issue-via-the-jira-rest-apis-6848604/
        type: object
        required: false
        example: '{ "update": { "labels": [ {"add": "newlabel"} ] } }'
    output:
      success:
        title: Success
        description: If changes were successful
        type: boolean
        required: false
triggers:
  new_issue:
    title: New Issue
    description: Trigger which indicates that a new issue has been created
    input:
      project:
        title: Project
        description: Project ID or name
        type: string
        required: true
        example: TEST
      jql:
        title: JQL
        type: string
        description: JQL search string to use
        required: false
        example: 'project = "TEST"'
      get_attachments:
        title: Get Attachments
        description: Get attachments from issue
        required: false
        type: boolean
        default: false
        example: false
      poll_timeout:
        title: Poll Timeout
        description: Timeout between next poll, default 60
        required: false
        type: integer
        default: 60
        example: 60
    output:
      issue:
        title: Issue
        type: issue
        description: New issue
        required: false
