# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Input:
    ACCOUNT_ID = "account_id"
    AUTHENTICATION_RETRY_LIMIT = "authentication_retry_limit"
    CLIENT_ID = "client_id"
    CLIENT_SECRET = "client_secret"


class ConnectionSchema(insightconnect_plugin_runtime.Input):
    schema = json.loads(
        r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "account_id": {
      "type": "string",
      "title": "Account ID",
      "description": "Zoom app account ID, required for OAuth authentication",
      "order": 3
    },
    "authentication_retry_limit": {
      "type": "integer",
      "title": "OAuth Authentication Retry Limit",
      "description": "How many times to retry authentication to Zoom before failing, required for OAuth authentication",
      "default": 5,
      "order": 4
    },
    "client_id": {
      "type": "string",
      "title": "Client ID",
      "description": "Zoom app client ID, required for OAuth authentication",
      "order": 1
    },
    "client_secret": {
      "$ref": "#/definitions/credential_secret_key",
      "title": "Client Secret",
      "description": "Zoom app client secret, required for OAuth authentication",
      "order": 2
    }
  },
  "required": [
    "account_id",
    "authentication_retry_limit",
    "client_id",
    "client_secret"
  ],
  "definitions": {
    "credential_secret_key": {
      "id": "credential_secret_key",
      "type": "object",
      "title": "Credential: Secret Key",
      "description": "A shared secret key",
      "required": [
        "secretKey"
      ],
      "properties": {
        "secretKey": {
          "type": "string",
          "title": "Secret Key",
          "description": "The shared secret key",
          "format": "password",
          "displayType": "password"
        }
      }
    }
  }
}
    """
    )

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
