{
    "sender_policy": [
        {
            "option": "block_sender",
            "id": "eNo1jsEKgjAAQP9lV4O0dGbQIRuYUEZY1qBLzYFL3Ww6c0b_nh66v8d7H1BToiRlKViC5MzbGdNbDRfH-NHj65Pxi5XEB_xuu7fChTR8I4Zz6AS8bW5TrqNyxzsV5tkL6b4hPZI48DojjM6nezbHhZBXopCrw72jfKT2ycymPn0FuViBCahEwYge0xa0TOhNAFF1I0oqiUjpMLSJI2StXc-xB7qlsmaCD_DfPOmKhqNtmrb5_QHJ4UNd",
            "policy": {
                "description": "some test policy",
                "fromPart": "envelope_from",
                "from": {
                    "type": "everyone"
                },
                "to": {
                    "type": "everyone"
                },
                "fromType": "everyone",
                "toType": "everyone",
                "fromEternal": true,
                "toEternal": true,
                "fromDate": "1900-01-01T00:00:00+0000",
                "toDate": "2100-01-01T23:59:59+0000",
                "override": false,
                "bidirectional": false,
                "conditions": {},
                "enabled": true,
                "enforced": false,
                "createTime": "2022-04-21T06:51:04+0000",
                "lastUpdated": "2022-04-21T06:51:04+0000"
            }
        }
    ]
}