# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Get information about the current user"


class Input:
    pass


class Output:
    SUCCESS = "success"


class GetCurrentUserInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetCurrentUserOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "success": {
      "$ref": "#/definitions/userObject",
      "title": "Success",
      "description": "A user object containing all related fields",
      "order": 1
    }
  },
  "definitions": {
    "userObject": {
      "type": "object",
      "title": "userObject",
      "properties": {
        "status": {
          "type": "string",
          "description": "Get user status",
          "order": 1
        },
        "_type": {
          "type": "string",
          "title": "Type",
          "description": "User type",
          "order": 2
        },
        "hasKey": {
          "type": "boolean",
          "description": "User has a key",
          "order": 3
        },
        "name": {
          "type": "string",
          "description": "Name",
          "order": 4
        },
        "roles": {
          "type": "array",
          "description": "Roles",
          "items": {
            "type": "string"
          },
          "order": 5
        },
        "updatedAt": {
          "type": "integer",
          "title": "Updated At",
          "description": "Time the user was updated in milliseconds or epoch",
          "order": 6
        },
        "user": {
          "type": "string",
          "description": "User",
          "order": 7
        },
        "createdBy": {
          "type": "string",
          "title": "Updated By",
          "description": "Created by",
          "order": 8
        },
        "updatedBy": {
          "type": "string",
          "title": "Updated By",
          "description": "Updated by",
          "order": 9
        },
        "_id": {
          "type": "string",
          "title": "_ID",
          "description": "User ID",
          "order": 10
        },
        "id": {
          "type": "string",
          "title": "ID",
          "description": "ID",
          "order": 11
        },
        "createdAt": {
          "type": "integer",
          "title": "Created At",
          "description": "Time the user was created at in milliseconds or epoch",
          "order": 12
        },
        "preferences": {
          "type": "object",
          "description": "User preferences",
          "order": 13
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
