package actions

// Code generated by the Komand Go SDK Generator. DO NOT EDIT

// ArrayToStringInput is the input for ArrayToString
type ArrayToStringInput struct {
	Delimiter string   `json:"delimiter"`
	Input     []string `json:"input"`
}

// ArrayToStringOutput is the output for ArrayToString
type ArrayToStringOutput struct {
	Output string `json:"output"`
}

// ArrayToStringAction is an action the plugin can take
type ArrayToStringAction struct{}
