package actions

// Code generated by the Komand Go SDK Generator. DO NOT EDIT

// BooleanToIntegerInput is the input for BooleanToInteger
type BooleanToIntegerInput struct {
	Input bool `json:"input"`
}

// BooleanToIntegerOutput is the output for BooleanToInteger
type BooleanToIntegerOutput struct {
	Output int `json:"output"`
}

// BooleanToIntegerAction is an action the plugin can take
type BooleanToIntegerAction struct{}
