{
  "request": {
    "assets": [
      {
        "name": "keyboardMC",
        "id": 301
      }
    ],
    "category": {
      "name": "Software",
      "id": 3
    },
    "created_by": {
      "id": 4,
      "name": "administrator",
      "is_vipuser": false
    },
    "created_time": "Aug 3, 2022 01:11 AM",
    "description": "dessssc",
    "due_by_time": "Aug 3, 2022 01:00 PM",
    "email_ids_to_notify": [
      "user@example.com"
    ],
    "has_notes": false,
    "id": 201,
    "impact": {
      "name": "Medium",
      "id": 2
    },
    "is_overdue": true,
    "is_service_request": false,
    "level": {
      "name": "Tier 4",
      "id": 4
    },
    "mode": {
      "name": "Web Form",
      "id": 2
    },
    "priority": {
      "name": "Normal",
      "id": 2
    },
    "requester": {
      "id": 4,
      "name": "administrator",
      "is_vipuser": false
    },
    "request_type": {
      "name": "Incident",
      "id": 1
    },
    "service_category": {
      "name": "User Management",
      "id": 8
    },
    "site": {
      "name": "Test Site",
      "id": 301
    },
    "status": {
      "name": "Open",
      "id": 2
    },
    "subcategory": {
      "name": "MS Office",
      "id": 5
    },
    "subject": "Plugin action test add request 2",
    "technician": {
      "id": 4,
      "name": "administrator",
      "is_vipuser": false
    },
    "udf_fields": {},
    "urgency": {
      "name": "Urgent",
      "id": 1
    }
  },
  "status": "success"
}