# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT

from .get_agent.action import GetAgent

from .get_agents.action import GetAgents

from .get_agent_status.action import GetAgentStatus

from .start_patch_scan.action import StartPatchScan

from .get_patch_scan_status.action import GetPatchScanStatus

from .get_scanned_machine_details.action import GetScannedMachineDetails

from .search_patches.action import SearchPatches

from .get_patch_details.action import GetPatchDetails

from .get_patch_deployment.action import GetPatchDeployment

from .get_patch_deployment_template_id.action import GetPatchDeploymentTemplateId

from .start_patch_deployment.action import StartPatchDeployment

from .create_patch_scan_template.action import CreatePatchScanTemplate

from .create_patch_group_and_add_cves.action import CreatePatchGroupAndAddCves

from .update_patch_group.action import UpdatePatchGroup

