# GENERATED BY KOMAND SDK - DO NOT EDIT
from setuptools import setup, find_packages


setup(name='tenable_nessus-rapid7-plugin',
      version='2.0.0',
      description='The Tenable Nessus plugin allows you to get, start, and analyze scans',
      author='rapid7',
      author_email='',
      url='',
      packages=find_packages(),
      install_requires=['komand'],  # Add third-party dependencies to requirements.txt, not here!
      scripts=['bin/komand_tenable_nessus']
      )
