package actions

// Code generated by the Komand Go SDK Generator. DO NOT EDIT
import (
	"github.com/rapid7/komand-plugins/slack/types"
)

// UploadSnippetInput is the input for UploadSnippet
type UploadSnippetInput struct {
	Channels string `json:"channels"`
	Content  string `json:"content"`
	Filename string `json:"filename"`
	Filetype string `json:"filetype"`
	Title    string `json:"title"`
}

// UploadSnippetOutput is the output for UploadSnippet
type UploadSnippetOutput struct {
	File types.FileReference `json:"file"`
}

// UploadSnippetAction is an action the plugin can take
type UploadSnippetAction struct{}
