for_sale_category = {
    "antiques": "ata",
    "appliances": "ppa",
    "arts+crafts": "ara",
    "atv/utv/sno": "sna",
    "auto parts": "pta wta",
    "baby+kids": "baa",
    "barter": "bar",
    "beauty+hlth": "haa",
    "bikes": "bia bip",
    "boats": "boo bpa",
    "books": "bka",
    "business": "bfa",
    "cars+trucks": "cta",
    "cds/dvd/vhs": "ema",
    "cell phones": "moa",
    "clothes+acc": "cla",
    "collectibles": "cba",
    "computers": "sya syp",
    "electronics": "ela",
    "farm+garden": "gra",
    "free": "zip",
    "furniture": "fua",
    "garage sale": "gms",
    "general": "foa",
    "heavy equip": "hva",
    "household": "hsa",
    "jewelry": "jwa",
    "materials": "maa",
    "motorcycles": "mca mpa",
    "music instr": "msa",
    "photo+video": "pha",
    "rvs+camp": "rva",
    "sporting": "sga",
    "tickets": "tia",
    "tools": "tla",
    "toys+games": "taa",
    "trailers": "tra",
    "video gaming": "vga",
    "wanted": "waa"
}
