# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Download an attachment by RRN. The RRN determines which attachment is downloaded"


class Input:
    ATTACHMENT_RRN = "attachment_rrn"


class Output:
    ATTACHMENT_CONTENT = "attachment_content"
    SUCCESS = "success"


class DownloadAttachmentInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(
        r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "attachment_rrn": {
      "type": "string",
      "title": "Attachment RRN",
      "description": "The RRN of the attachment",
      "order": 1
    }
  },
  "required": [
    "attachment_rrn"
  ],
  "definitions": {}
}
    """
    )

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class DownloadAttachmentOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(
        r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "attachment_content": {
      "type": "string",
      "format": "bytes",
      "displayType": "bytes",
      "title": "Attachment Content",
      "description": "The base64 encoded content of the attachment",
      "order": 1
    },
    "success": {
      "type": "boolean",
      "title": "Success",
      "description": "Whether the action was successful or not",
      "order": 2
    }
  },
  "required": [
    "success"
  ],
  "definitions": {}
}
    """
    )

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
