plugin_spec_version: v2
name: openvas
title: OpenVAS
description: The Open Vulnerability Assessment System (OpenVAS)
version: 1.0.0
vendor: rapid7
status: ["unsupported"]
tags:
- openvas
- vulnerability
- scanner
types:
  scan:
    name:
      title: Name
      type: string
    scan_id:
      title: Scan ID
      type: string
  datetime:
    year:
      type: integer
      title: Year
      description: Start year, in numeric form i.e. 2017
    month:
      type: integer
      title: Month
      description: Start month, in numeric form i.e. 1-12
    day:
      type: integer
      title: Day
      description: Start day, in numeric form i.e. 1-31
    hour:
      type: integer
      title: Hour
      description: Start hour, in numeric 24 hour form i.e. 0-23
    minute:
      type: integer
      title: Minute
      description: Start minute, in numeric form i.e. 0-59
connection:
  server:
    type: string
    title: Server
    description: OpenVAS Management Protocol Server URL host:port
    required: true
    default: 127.0.0.1:9390
  credentials:
    type: credential_username_password
    title: Username and Password
    description: Username and password
    required: true
  timeout:
    type: integer
    title: Timeout
    description: Timeout to connect to server
    required: true
    default: 10
  ssl_verify:
    type: boolean
    title: SSL Verify
    description: Verify SSL Certificate
    required: true
    default: false
triggers:
  check_scan_done:
    title: Check Scan Done
    description: Poll scan by scan ID for completion
    input:
      scan_id:
        type: string
        title: Scan ID
        description: Scan ID E.g. 9a849831-23a0-48ba-8e8f-a3deeaa45f7e
        required: true
      poll:
        type: float
        title: Poll
        description: Length of time to wait between polling in minutes
        required: false
        default: 3
    output:
      scan_finished:
        type: boolean
        title: Scan Finished
        description: Scan completion status
        required: true
actions:
  create_port_list:
    title: Create Port List
    description: Create a new list of ports to scan in the OpenVAS server
    input:
      name:
        type: string
        title: Port List Name
        description: Port list name
        required: true
      port_list_TCP:
        type: '[]string'
        title: TCP Port List
        description: 'Target Port List for TCP ports, in the form of a JSON array
          for each port or list of ports. For example, the following would be a valid
          list: [''22'', ''80'',''443-445'']'
        required: false
      port_list_UDP:
        type: '[]string'
        title: UDP Port List
        description: 'Target Port List for UDP ports, in the form of a JSON array
          for each port or list of ports. For example, the following would be a valid
          list: [''53'', ''6881-6890'']'
        required: false
    output:
      port_list_id:
        type: string
        title: Port List ID
        description: Port list ID's
        required: false
      success:
        type: boolean
        title: Success
        description: Success
        required: false
      message:
        type: string
        title: Message
        description: Message
        required: false
  create_schedule:
    title: Create Schedule
    description: Create a schedule to run a scan on
    input:
      name:
        title: Schedule Name
        description: Schedule name
        required: true
        type: string
      first_time:
        title: First Time
        description: The first time the schedule will run, in UTC timezone
        type: datetime
        required: true
      duration:
        title: Duration
        description: How long the Manager will run the scheduled task for, in hours
        type: integer
        required: false
      period:
        title: Period
        description: How often the Manager will repeat the scheduled task, in days
        type: integer
        required: false
    output:
      schedule_id:
        type: string
        title: Schedule ID
        description: Schedule ID
        required: false
      success:
        type: boolean
        title: Success
        description: Success
        required: false
      message:
        type: string
        title: Message
        description: Message
        required: false
  create_target:
    title: Create Target
    description: Create a new target in the OpenVAS server
    input:
      name:
        type: string
        title: Target Name
        description: Target Name
        required: true
      host_list:
        type: '[]string'
        title: Target IP List
        description: 'Target IP List, in the form of a JSON array for each host or
          list of hosts. CIDR notation can be used. For example, the following would
          be a valid list: [''192.168.0.101'', ''192.168.1.101,192.168.1.103,192.168.1.105'',''192.168.1.2/24'',''192.168.3.105-112'']'
        required: true
      port_list_id:
        type: string
        title: Port List ID
        description: ID of the Port List to use for scanning, if you want to scan
          a custom list of ports
        required: false
    output:
      target_id:
        type: string
        title: Target ID
        description: Target ID
        required: false
      success:
        type: boolean
        title: Success
        description: Success
        required: false
      message:
        type: string
        title: Message
        description: Message
        required: false
  delete_scan:
    title: Delete Scan
    description: Delete specified scan ID in the OpenVAS server
    input:
      scan_id:
        type: string
        title: Scan ID
        description: Scan ID E.g. 9a849831-23a0-48ba-8e8f-a3deeaa45f7e
        required: true
    output:
      success:
        type: boolean
        title: Success
        description: Success
        required: false
      message:
        type: string
        title: Message
        description: Message
        required: false
  delete_target:
    title: Delete Target
    description: Delete specified target ID in the OpenVAS server
    input:
      target_id:
        type: string
        title: Target ID
        description: Target ID
        required: true
    output:
      success:
        type: boolean
        title: Success
        description: Success
        required: false
      message:
        type: string
        title: Message
        description: Message
        required: false
  get_all_scans:
    title: Get All Scans
    description: Get a list of all scans in the OpenVAS server
    output:
      list_scans:
        type: '[]scan'
        title: List of Scans
        description: JSON array containing the list of all running scans
        required: false
      success:
        type: boolean
        title: Success
        description: Success
        required: false
      message:
        type: string
        title: Message
        description: Message
        required: false
  get_finished_scans:
    title: Get Finished Scans
    description: Get a list of all finished scans
    output:
      list_scans:
        type: '[]scan'
        title: List of Scans
        description: JSON array containing the list of all finished scans
        required: false
      success:
        type: boolean
        title: Success
        description: Success
        required: false
      message:
        type: string
        title: Message
        description: Message
        required: false
  get_report_html:
    title: Get Report HTML
    description: Get the HTML version of the report for a particular scan
    input:
      scan_id:
        type: string
        title: Scan ID
        description: Scan ID E.g. 9a849831-23a0-48ba-8e8f-a3deeaa45f7e
        required: true
    output:
      report:
        type: string
        title: Report
        description: HTML output of report
        required: false
      success:
        type: boolean
        title: Success
        description: Success
        required: false
      message:
        type: string
        title: Message
        description: Message
        required: false
  get_report_xml:
    title: Get Report XML
    description: Get the XML version of the report for a particular scan
    input:
      scan_id:
        type: string
        title: Scan ID
        description: Scan ID
        required: true
    output:
      report:
        type: string
        title: Report
        description: XML output of report
        required: false
      success:
        type: boolean
        title: Success
        description: Success
        required: false
      message:
        type: string
        title: Message
        description: Message
        required: false
  get_running_scans:
    title: Get Running Scans
    description: Get a list of all currently running scans
    output:
      list_scans:
        type: '[]scan'
        title: List of Scans
        description: JSON array containing the list of all running scans
        required: false
      success:
        type: boolean
        title: Success
        description: Success
        required: false
      message:
        type: string
        title: Message
        description: Message
        required: false
  get_scan_configs:
    title: Get Scan Configurations
    description: Get a list of all scan configurations in the OpenVAS server
    output:
      list_scan_configs:
        type: '[]scan'
        title: List of Scan Configurations
        description: JSON array containing the list of all scan configurations
        required: false
      success:
        type: boolean
        title: Success
        description: Success
        required: false
      message:
        type: string
        title: Message
        description: Message
        required: false
  launch_scan:
    title: Launch Scan
    description: Launch a new audit in OpenVAS
    input:
      target:
        type: string
        title: Target IP Address or ID
        description: If only one IP address is to be scanned, the IP can be passed
          directly through this parameter. Otherwise, a target ID can be passed from
          the Create Target functionality
        required: true
      profile:
        type: string
        title: Profile
        description: Scan profile in the OpenVAS server E.g. Full and fast
        required: true
      schedule:
        type: string
        title: Schedule
        description: Schedule id to use for the scan
        required: false
    output:
      success:
        type: boolean
        title: Success
        description: Success
        required: false
      scan_id:
        type: string
        title: Scan ID
        description: Scan ID E.g. 9a849831-23a0-48ba-8e8f-a3deeaa45f7e
        required: false
      target_id:
        type: string
        title: Target ID
        description: Target ID
        required: false
      message:
        type: string
        title: Message
        description: Message
        required: false
  scan_status:
    title: Scan Status
    description: Get status of scan
    input:
      scan_id:
        type: string
        title: Scan ID
        description: Scan ID E.g. 9a849831-23a0-48ba-8e8f-a3deeaa45f7e
        required: true
    output:
      status:
        type: string
        title: Status
        description: Status
        required: false
      success:
        type: boolean
        title: Success
        description: Success
        required: false
      message:
        type: string
        title: Message
        description: Message
        required: false
  stop_scan:
    title: Stop Scan
    description: Stops specified scan ID in the OpenVAS server
    input:
      scan_id:
        type: string
        title: Scan ID
        description: Scan ID E.g. 9a849831-23a0-48ba-8e8f-a3deeaa45f7e
        required: true
    output:
      success:
        type: boolean
        title: Success
        description: Success
        required: false
      message:
        type: string
        title: Message
        description: Message
        required: false
