# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Component:
    DESCRIPTION = "Destroy a direct message"


class Input:
    MESSAGE_ID = "message_id"
    

class Output:
    DESTROYED = "destroyed"
    

class DestroyInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "message_id": {
      "type": "string",
      "title": "Message ID",
      "description": "ID of direct message to destroy",
      "order": 1
    }
  },
  "required": [
    "message_id"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class DestroyOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "destroyed": {
      "type": "boolean",
      "title": "Destroyed",
      "description": "Destroyed",
      "order": 1
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
