# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Trigger workflows to get IOC feeds from Luminar"


class Input:
    FREQUENCY = "frequency"
    INITIAL_FETCH_DATE = "initial_fetch_date"


class Output:
    RESULTS = "results"


class FetchIocFeedsInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "frequency": {
      "type": "integer",
      "title": "Frequency",
      "description": "Poll frequency in seconds",
      "default": 300,
      "order": 1
    },
    "initial_fetch_date": {
      "type": "string",
      "title": "Initial Fetch Date",
      "description": "The date from which the initial fetch will start. eg YYYY-MM-DD",
      "order": 2
    }
  },
  "required": [
    "initial_fetch_date"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class FetchIocFeedsOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "results": {
      "type": "array",
      "title": "Results",
      "description": "IOC feed results",
      "items": {
        "$ref": "#/definitions/results"
      },
      "order": 1
    }
  },
  "required": [
    "results"
  ],
  "definitions": {
    "results": {
      "type": "object",
      "title": "results",
      "properties": {
        "commentCount": {
          "type": "integer",
          "title": "Comment Count",
          "description": "Comment count",
          "order": 1
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
