# GENERATED BY KOMAND SDK - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Updates an incident status for each incident ID provided"


class Input:
    INCIDENT_IDS = "incident_ids"
    INCIDENT_STATUS = "incident_status"
    TYPE = "type"
    

class Output:
    AFFECTED = "affected"
    

class UpdateIncidentStatusInput(insightconnect_plugin_runtime.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "incident_ids": {
      "type": "array",
      "title": "Incident IDs",
      "description": "A list of alert or threat IDs to update the incident status on",
      "items": {
        "type": "string"
      },
      "order": 1
    },
    "incident_status": {
      "type": "string",
      "title": "Incident Status",
      "description": "Incident status",
      "enum": [
        "unresolved",
        "in progress",
        "resolved"
      ],
      "order": 2
    },
    "type": {
      "type": "string",
      "title": "Type",
      "description": "Type of incidents",
      "enum": [
        "threats",
        "alerts"
      ],
      "order": 3
    }
  },
  "required": [
    "incident_ids",
    "incident_status",
    "type"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class UpdateIncidentStatusOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "affected": {
      "type": "integer",
      "title": "Affected",
      "description": "Number of entities affected by the requested operation",
      "order": 1
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
