# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Create a new certification in Cyber GRC"


class Input:
    RECORD = "record"


class Output:
    CERTIFICATION = "certification"


class CreateCertificationInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "record": {
      "type": "object",
      "title": "Certification",
      "description": "The certification to create, as a JSON object matching the CreateCertificationDto schema in the Rapid7 Cyber GRC API reference",
      "order": 1
    }
  },
  "required": [
    "record"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class CreateCertificationOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "certification": {
      "$ref": "#/definitions/certification",
      "title": "Certification",
      "description": "The created certification",
      "order": 1
    }
  },
  "required": [
    "certification"
  ],
  "definitions": {
    "certification": {
      "type": "object",
      "title": "certification",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 2
        },
        "isActive": {
          "type": "boolean",
          "title": "Is Active",
          "description": "Is Active",
          "order": 3
        },
        "createdDate": {
          "type": "string",
          "format": "date-time",
          "displayType": "date",
          "title": "Created Date",
          "description": "Created Date",
          "order": 4
        },
        "modifiedDate": {
          "type": "string",
          "format": "date-time",
          "displayType": "date",
          "title": "Modified Date",
          "description": "Modified Date",
          "order": 5
        },
        "createdBy": {
          "type": "string",
          "title": "Created By",
          "description": "Created By",
          "order": 6
        },
        "modifiedBy": {
          "type": "string",
          "title": "Modified By",
          "description": "Modified By",
          "order": 7
        },
        "itAssets": {
          "type": "array",
          "title": "IT Assets",
          "description": "IT Assets",
          "items": {
            "$ref": "#/definitions/it_asset_lookup"
          },
          "order": 8
        }
      }
    },
    "it_asset_lookup": {
      "type": "object",
      "title": "it_asset_lookup",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "ID",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name",
          "order": 2
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
