# GENERATED BY KOMAND SDK - DO NOT EDIT
import komand
import json


class Component:
    DESCRIPTION = "Fetch and store the the feed file locally"


class Input:
    
    INTERVAL = "interval"
    

class Output:
    
    ENCODEDFEEDFILE = "encodedFeedFile"
    STATUSCODE = "statusCode"
    

class SaveFeedFileInput(komand.Input):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "interval": {
      "type": "integer",
      "title": "Interval",
      "description": "How often (in seconds) to trigger feed download",
      "default": 3600,
      "order": 1
    }
  },
  "required": [
    "interval"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class SaveFeedFileOutput(komand.Output):
    schema = json.loads("""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "encodedFeedFile": {
      "type": "string",
      "title": "Encoded feed file",
      "displayType": "bytes",
      "description": "Base64 encoded feed file",
      "format": "bytes",
      "order": 2
    },
    "statusCode": {
      "type": "integer",
      "title": "HTTP status code",
      "description": "HTTP status code",
      "order": 1
    }
  },
  "required": [
    "encodedFeedFile",
    "statusCode"
  ]
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
