plugin_spec_version: v2
extension: plugin
products: [insightconnect]
name: twitter
title: Twitter
vendor: rapid7
support: community
status: []
description: "Twitter is a microblogging and social networking service. Using the Twitter plugin for
  Rapid7 InsightConnect, users can monitor tweets, post, and block users"
version: 2.0.1
resources:
  source_url: https://github.com/rapid7/insightconnect-plugins/tree/master/twitter
  license_url: https://github.com/rapid7/insightconnect-plugins/blob/master/LICENSE
  vendor_url: https://twitter.com/
tags:
- twitter
- tweet
- social networking
- post
hub_tags:
  use_cases: [soar, alerting_and_notifications, threat_hunting, threat_intel]
  keywords: [twitter, tweet, social networking, post]
  features: []
connection:
  consumer_credentials:
    type: credential_username_password
    description: Consumer Key and Consumer Secret
    title: Consumer credentials
    required: true
  access_token_credentials:
    type: credential_username_password
    description: Access Token and Access Token Secret
    title: Access Token Credentials
    required: true
actions:
  post:
    description: Tweet
    input:
      msg:
        description: Text to tweet
        type: string
        required: true
    output:
      url:
        title: URL of Tweet
        type: string
        description: URL
        required: false
  block:
    description: Block User
    input:
      user:
        description: User to block
        type: string
        required: true
    output:
      blocked:
        title: Blocked
        description: Blocked
        type: boolean
        required: false
  destroy:
    description: Destroy a direct message
    input:
      message_id:
        title: Message ID
        description: ID of direct message to destroy
        type: string
        required: true
    output:
      destroyed:
        title: Destroyed
        description: Destroyed
        type: boolean
        required: false
triggers:
  tweets:
    title: Tweets
    description: Monitor for tweets of interest
    input:
      interval:
        type: integer
        description: Poll interval in seconds
        default: 300
        required: false
      pattern:
        description: Pattern to match
        type: string
        required: true
    output:
      msg:
        title: Message
        description: Tweet message
        type: string
        required: false
      url:
        title: URL
        description: URL of tweet
        type: string
        required: false
      user:
        title: Posting User
        description: Posting user
        type: string
        required: false
  messages:
    title: Messages
    description: Monitor received messages
    input:
      interval:
        type: integer
        description: Poll interval in seconds
        default: 300
        required: false
      pattern:
        description: Pattern to Match
        type: string
        required: false
    output:
      msg:
        title: Message
        description: Twitter Message
        type: string
        required: false
      user:
        title: Posting User
        description: Posting user
        type: string
        required: false
      id:
        title: Message ID
        description: Twitter message ID
        type: string
        required: false
      created_at:
        title: Creation Date
        description: Creation date
        type: string
        required: false
      recipient_id:
        title: Recipient ID
        description: Recipient ID
        type: integer
        required: false
      sender_id:
        title: Sender ID
        description: Sender ID
        type: integer
        required: false
      sender_created_at:
        title: Sender Creation
        description: Sender account creation date
        type: string
        required: false
      sender_default_profile:
        title: Sender Default Profile
        description: Sender uses the default profile
        type: boolean
        required: false
      sender_default_profile_image:
        title: Sender Default Profile Image
        description: Sender uses the default profile image
        type: boolean
        required: false
      sender_description:
        title: Sender Description
        description: Sender profile description
        type: string
        required: false
      sender_followers_count:
        title: Sender Followers Count
        description: Sender's follower count
        type: integer
        required: false
      sender_friends_count:
        title: Sender Friends Count
        description: Sender's friend count
        type: integer
        required: false
      sender_lang:
        title: Sender Language
        description: Sender's language
        type: string
        required: false
      sender_location:
        title: Sender Location
        description: Sender's geographic location
        type: string
        required: false
      sender_name:
        title: Sender Name
        description: Sender's profile name
        type: string
        required: false
  mentions:
    title: Mentions
    description: Monitor for mentions
    input:
      interval:
        type: integer
        description: Poll interval in seconds
        default: 300
        required: false
      pattern:
        description: Pattern to Match
        type: string
        required: false
    output:
      msg:
        title: Message
        description: Twitter message
        type: string
        required: false
      url:
        title: URL
        description: URL of tweet
        type: string
        required: false
      user:
        title: Posting User
        description: Posting user
        type: string
        required: false
  user:
    title: User
    description: Monitor for tweets from a screen name
    input:
      interval:
        type: integer
        description: Poll interval in seconds
        default: 300
        required: false
      screen_name:
        description: Screen Name (no @)
        type: string
        required: true
    output:
      msg:
        title: Message
        description: Message
        type: string
        required: false
      url:
        title: URL
        description: URL of tweet
        type: string
        required: false
      user:
        title: Posting User
        description: Posting user
        type: string
        required: false
