plugin_spec_version: v2
extension: plugin
products: [insightconnect]
name: okta
title: Okta
vendor: rapid7
support: rapid7
status: []
description: Secure identity management and single sign-on to any application
version: 3.5.2
resources:
  source_url: https://github.com/rapid7/insightconnect-plugins/tree/master/okta
  license_url: https://github.com/rapid7/insightconnect-plugins/blob/master/LICENSE
  vendor_url: https://okta.com
tags:
- sso
- provisioning
- deprovisioning
- saml
hub_tags:
  use_cases: [application_management, user_management]
  keywords: [sso, provisioning, deprovisioning, saml]
  features: []
enable_cache: true
types:
  profile:
    email:
      type: string
    secondEmail:
      type: string
    firstName:
      type: string
    lastName:
      type: string
    login:
      type: string
    mobilePhone:
      type: string
  changePassword:
    href:
      type: string
  _links:
    changePassword:
      type: changePassword
    changeRecoveryQuestion:
      type: changePassword
    deactivate:
      type: changePassword
    expirePassword:
      type: changePassword
    forgotPassword:
      type: changePassword
    resetFactors:
      type: changePassword
    resetPassword:
      type: changePassword
  provider:
    type:
      description: Provider type e.g. OKTA
      type: string
    name:
      description: Provider name e.g. OKTA
      type: string
  recovery_question:
    question:
      description: Recovery question e.g. Who's a major player in the cowboy scene?
      type: string
    answer:
      description: Recovery answer e.g. Annie Oakley
      type: string
  credentials:
    password:
      type: object
    provider:
      type: provider
    recovery_question:
      type: recovery_question
  group:
    name:
      description: Group name
      title: Name
      type: string
      required: false
    created:
      description: Created
      title: Created
      type: string
      required: false
    objectClass:
      description: Object class
      title: Object Class
      type: '[]string'
      required: false
    lastUpdated:
      description: Last updated
      title: Last Updated
      type: string
      required: false
    lastMembershipUpdated:
      description: Last membership updated
      title: Last Membership Updated
      type: string
      required: false
    type:
      description: Type
      title: Type
      type: string
      required: false
    id:
      description: Group ID
      title: ID
      type: string
      required: false
  password:
    value:
      description: Password value e.g. tlpWENT2m
      type: string
  credentials_input:
    password:
      type: password
    provider:
      type: provider
    recovery_question:
      type: recovery_question
  user:
    id:
      type: string
    status:
      type: string
    created:
      type: string
    activated:
      type: string
    statusChanged:
      type: string
    lastLogin:
      type: string
    lastUpdated:
      type: string
    passwordChanged:
      type: string
    profile:
      type: profile
    credentials:
      type: credentials_input
    links:
      type: _links
  user_group:
    group_name:
      type: string
    group_id:
      type: string
    users:
      type: "[]user"
  hints:
    allow:
      title: Allow
      type: "[]string"
      description: Allow
      required: false
  deactivate:
    hints:
      title: Hints
      type: hints
      description: Hints
      required: false
    href:
      title: HREF
      type: string
      description: HREF
      required: false
  zone_links:
    deactivate:
      title: Deactivate
      type: deactivate
      description: Deactivate
      required: false
    self:
      title: Self
      type: deactivate
      description: Self
      required: false
  gateways:
    type:
      title: Type
      type: string
      description: Type
      required: false
    value:
      title: Value
      type: string
      description: Value
      required: false
  zone_list:
    zone_links:
      title: Zone Links
      type: zone_links
      description: Zone links
      required: false
    created:
      title: Created
      type: string
      description: Created
      required: false
    gateways:
      title: Gateways
      type: "[]gateways"
      description: Gateways
      required: false
    id:
      title: ID
      type: string
      description: ID
      required: false
    lastUpdated:
      title: Last Updated
      type: string
      description: Last updated
      required: false
    name:
      title: Name
      type: string
      description: Name
      required: false
    proxies:
      title: Proxies
      type: "[]gateways"
      description: Proxies
      required: false
    status:
      title: Status
      type: string
      description: Status
      required: false
    system:
      title: System
      type: boolean
      description: System
      required: false
    type:
      title: Type
      type: string
      description: Type
      required: false

connection:
  okta_url:
    title: Okta Domain
    description: Okta Domain e.g. example.okta.com
    type: string
    required: true
  okta_key:
    title: Okta Key
    description: Okta key
    type: credential_secret_key
    required: true

triggers:
  users_added_removed_from_group:
    title: Monitor User Groups
    description: Monitors a list of groups for user membership changes
    input:
      group_ids:
        title: Group ID's
        description: A list of group ID's
        type: "[]string"
        required: true
        example: ["00g41ix8hKbsu74Ca4x6", "00g41ieu5y7i9XEYE4x6"]
      interval:
        title: Interval
        description: The time in seconds between checks for changes to the groups users
        type: integer
        required: true
        default: 300
        example: 100
    output:
      users_added_from_groups:
        title: Additions
        description: Users added to a group since the last check
        type: "[]user_group"
        required: true
      users_removed_from_groups:
        title: Removals
        description: Users removed from a group since the last check
        type: "[]user_group"
        required: true
actions:
  get_factors:
    title: Get Okta User Factors
    description: Returns an object containing all of a user's factors for MFA
    input:
      user_id:
        title: Okta User ID
        description: User ID to get factors for
        type: string
        required: true
    output:
      factors:
        title: Okta MFA Factors
        description: Obbject containing all the factors of a user for MFA
        type: "[]object"
        required: false
  send_push:
    title: Push MFA Challenge
    description: Push an MFA challenge to a user's device and wait for a success or rejection
    input:
      user_id:
        title: Okta User ID
        description: User ID to push verification to
        type: string
        required: true
      factor_id:
        title: Okta Factor ID
        description: Factor ID of the user to push verification to
        type: string
        required: true
    output:
      factor_status:
        title: Factor Status
        description: User factor status
        type: string
        required: false
  deactivate_user:
    title: Deactivate User
    description: Deactivate a user
    input:
      email:
        title: Okta User Email
        description: The email of the employee to deactivate
        type: string
        required: true
    output:
      email:
        title: Okta User Email
        description: The email of the Okta user
        type: string
        required: false
      user_id:
        title: Okta User ID
        description: The user ID of the Okta user
        type: string
        required: false
      success:
        title: Success
        description: Whether deactivation was successful
        type: boolean
        required: true
  delete_user:
    title: Delete User
    description: Delete a user. Warning, this action cannot be recovered from
    input:
      user_email:
        title: Okta User Email
        description: The email of the user to delete
        type: string
        required: true
      send_admin_email:
        title: Send Admin Email
        description: Sends a deactivation email to the administrator if true. Default value is false
        type: boolean
        default: false
        required: true
    output:
      success:
        title: Success
        description: Whether deactivation was successful
        type: boolean
        required: true
  suspend_user:
    title: Suspend User
    description: Suspend a user
    input:
      email:
        title: Okta User Email
        description: The email of the employee to suspend
        type: string
        required: true
    output:
      email:
        title: Okta User Email
        description: The email of the Okta user
        type: string
        required: false
      user_id:
        title: Okta User ID
        description: The user ID of the Okta user
        type: string
        required: false
      success:
        title: Success
        description: Whether suspension was successful
        type: boolean
        required: true
  unsuspend_user:
    title: Unsuspend User
    description: Unsuspend a user
    input:
      email:
        title: Okta User Email
        description: The email of the Okta user
        type: string
        required: true
    output:
      email:
        title: Okta User Email
        description: The email of the Okta user
        type: string
        required: false
      user_id:
        title: Okta User ID
        description: The user ID of the Okta user
        type: string
        required: false
      success:
        title: Success
        description: Whether unsuspension was successful
        type: boolean
        required: true
  get_user:
    title: Get User
    description: Obtain information about a user
    input:
      email:
        title: Okta User Email
        description: The email of the user to obtain information about
        type: string
        required: true
    output:
      status:
        description: Status
        title: Status
        type: string
        required: false
      profile:
        description: Profile
        title: Profile
        type: profile
        required: false
      passwordChanged:
        description: When the password was changed, e.g. 2013-07-02T21:36:25.344Z
        title: Password Changed
        type: string
        required: false
      created:
        description: When the user was created, e.g. 2013-07-02T21:36:25.344Z
        title: Created
        type: string
        required: false
      activated:
        description: When the user was activated, e.g. 2013-07-02T21:36:25.344Z
        title: Activated
        type: string
        required: false
      lastUpdated:
        description: When the user was last updated, e.g. 2013-07-02T21:36:25.344Z
        title: Last Updated
        type: string
        required: false
      _links:
        description: Links
        title: Links
        type: _links
        required: false
      lastLogin:
        description: When the last login for the user was, e.g. 2013-07-02T21:36:25.344Z
        title: Last Login
        type: string
        required: false
      credentials:
        description: Credentials
        title: Credentials
        type: credentials
        required: false
      id:
        description: User ID
        title: ID
        type: string
        required: false
      statusChanged:
        description: When the status of the user changed, e.g. 2013-07-02T21:36:25.344Z
        title: Status Changed
        type: string
        required: false
      found:
        description: Whether user was found
        title: Found User
        type: boolean
        required: true
  add_user_to_group:
    title: Add User to Group
    description: Add a user to an existing group
    input:
      email:
        title: Okta User Email
        description: The email of the Okta user
        type: string
        required: true
      group_id:
        title: Group ID
        description: The ID of the group to which the user should be added
        type: string
        required: true
    output:
      user_id:
        title: Okta User ID
        description: The user ID of the Okta user
        type: string
        required: false
      success:
        title: Success
        description: Whether the add was successful
        type: boolean
        required: true
  remove_user_from_group:
    title: Remove User from Group
    description: Remove a user from an existing group
    input:
      email:
        title: Okta User Email
        description: The email of the Okta user
        type: string
        required: true
      group_id:
        title: Group ID
        description: The ID of the group to which the user should be added
        type: string
        required: true
    output:
      user_id:
        title: Okta User ID
        description: The user ID of the Okta user
        type: string
        required: false
      success:
        title: Success
        description: Whether the add was successful
        type: boolean
        required: true
  list_groups:
    title: List Groups
    description: List available groups
    input:
      query:
        title: Query
        description: Query to list groups, otherwise all groups will be returned
        type: string
        required: false
    output:
      success:
        title: Success
        description: Whether groups were found
        type: boolean
        required: true
      groups:
        title: Groups
        description: List of groups
        type: '[]group'
        required: false
  assign_user_to_app_sso:
    title: Assign User to Application for Provisioning
    description: Assign user to application for SSO and provisioning
    input:
      applicationId:
        title: Application ID
        description: Application ID
        type: string
        required: true
      appuser:
        title: Application User Model
        description: Application user model as JSON object, see https://developer.okta.com/docs/api/resources/apps#application-user-model
        type: object
        required: false
    output:
      result:
        title: Result
        description: Result
        type: object
        required: true
  create_user:
    title: Create User
    description: Create a new user
    input:
      activate:
        title: Activate
        description: Executes activation lifecycle operation when creating the user
        type: boolean
        default: true
        required: true
      provider:
        title: Provider
        description: Indicates whether to create a user with a specified authentication
          provider
        type: boolean
        default: false
        required: true
      profile:
        title: Profile
        description: Profile properties for user
        type: object
        required: true
      credentials:
        title: Credentials
        description: Credentials for user
        type: credentials_input
        required: false
      groupIds:
        title: Group IDs
        description: IDs of groups that user will be immediately added to at time
          of creation
        type: '[]string'
        required: false
      nextLogin:
        title: Change Password Next Login
        description: Change password next time the user logs in
        type: boolean
        required: true
    output:
      status:
        description: Status
        title: Status
        type: string
        required: false
      profile:
        description: Profile
        title: Profile
        type: profile
        required: false
      passwordChanged:
        description: When the password was changed, e.g. 2013-07-02T21:36:25.344Z
        title: Password Changed
        type: string
        required: false
      created:
        description: When the user was created, e.g. 2013-07-02T21:36:25.344Z
        title: Created
        type: string
        required: false
      activated:
        description: When the user was activated, e.g. 2013-07-02T21:36:25.344Z
        title: Activated
        type: string
        required: false
      lastUpdated:
        description: When the user was last updated, e.g. 2013-07-02T21:36:25.344Z
        title: Last Updated
        type: string
        required: false
      _links:
        description: Links
        title: Links
        type: _links
        required: false
      lastLogin:
        description: When the last login for the user was, e.g. 2013-07-02T21:36:25.344Z
        title: Last Login
        type: string
        required: false
      credentials:
        description: Credentials
        title: Credentials
        type: credentials
        required: false
      id:
        description: User ID
        title: ID
        type: string
        required: false
      statusChanged:
        description: When the status of the user changed, e.g. 2013-07-02T21:36:25.344Z
        title: Status Changed
        type: string
        required: false
  reset_factors:
    title: Reset Factors
    description: Reset all multifactors for user by email
    input:
      email:
        title: Okta User Email
        description: The email of the employee to reset factors
        type: string
        required: true
    output:
      success:
        title: Success
        description: Whether the reset was successful
        type: boolean
        required: true
      email:
        title: Okta User Email
        description: The email of the Okta user
        type: string
        required: false
      user_id:
        title: Okta User ID
        description: The user ID of the Okta user
        type: string
        required: false
  update_blacklist_zones:
    title: Update Blacklist Zones
    description: Block or unblock address or network by adding or removing from a blacklist network zone
    input:
      name:
        title: Name
        description: Name of blacklist zone
        type: string
        required: true
        example: InsightConnect Blacklist Zone
      address:
        title: Address
        description: IP address, Network range, or CIDR to block or unblock
        type: string
        required: true
        example: 198.51.100.1
      blacklist_state:
        title: Blacklist State
        description: True to block, false to unblock
        type: boolean
        required: false
        default: True
        example: True
    output:
      zone_list:
        title: Zone List
        description: Updated zone list
        type: zone_list
        required: true
