plugin_spec_version: v2
extension: plugin
products: [insightconnect]
name: google_cloud_pub_sub
title: Google Cloud Pub Sub
description: A fully-managed real-time messaging service that allows you to send and
  receive messages
version: 3.1.2
vendor: rapid7
support: community
status: []
resources:
  source_url: https://github.com/rapid7/insightconnect-plugins/tree/master/google_cloud_pub_sub
  license_url: https://github.com/rapid7/insightconnect-plugins/blob/master/LICENSE
  vendor_url: https://www.google.com/
tags:
- google cloud
- message broker
hub_tags:
  use_cases: [data_utility, alerting_and_notifications]
  keywords: [google cloud, message broker, google]
  features: []
connection:
  admin_user:
    title: Admin User
    description: Optional admin user to impersonate, e.g. admin@domain.com
    type: string
    required: false
  project_id:
    title: Project ID
    description: Project ID from service credentials e.g subpub-1528163449245
    type: string
    required: true
  private_key_id:
    title: Private Key ID
    description: Private Key ID from service credentials
    type: string
    required: true
  private_key:
    title: Private Key
    description: Private Key from service credentials
    type: credential_asymmetric_key
    required: true
  client_email:
    title: Client Email
    description: Client email from service credentials
    type: string
    required: true
  client_id:
    title: Client ID
    description: Client ID e.g. 109587155068933904953
    type: string
    required: true
  client_x509_cert_url:
    title: Client X509 Cert URL
    description: X509 cert URL from service credentials
    type: string
    required: true
  auth_uri:
    title: Auth URI
    description: OAUTH2 Auth URI
    type: string
    required: true
    default: https://accounts.google.com/o/oauth2/auth
  token_uri:
    title: Token URI
    description: OAUTH2 Token URI
    type: string
    required: true
    default: https://accounts.google.com/o/oauth2/token
  auth_provider_x509_cert_url:
    title: Auth Provider Cert URL
    description: OAUTH2 Auth Provider x509 Cert URL
    type: string
    required: true
    default: https://www.googleapis.com/oauth2/v1/certs
triggers:
  subscription:
    title: Subscription
    description: Pulls new messages from a subscription
    input:
      subscription:
        title: Subscription
        description: The subscription to pull from
        type: string
        required: true
      project_id:
        title: Project ID
        description: The project ID for the subscription e.g. subpub-1528163449245
        type: string
        required: true
      number_of_messages:
        title: Number of Messages
        description: The number of messages to return at one time as a list. Must
          be 1 or more
        type: integer
        required: true
        default: 1
    output:
      messages:
        title: Messages
        description: Messages found in the subscription
        type: '[]string'
        required: false
actions:
  publish:
    title: Publish
    description: Publish
    input:
      topic:
        title: Topic
        description: The name of the topic to publish to
        type: string
        required: true
      message:
        title: Message
        description: The message to publish to the topic
        type: string
        required: true
      project_id:
        title: Project ID
        description: The project ID for the topic e.g. subpub-1528163449245. If left
          blank the plugin will use the project ID found in the connection
        type: string
        required: false
    output:
      success:
        title: Success
        description: Return true if it worked
        type: boolean
        required: false
  create_topic:
    title: Create Topic
    description: Create a new topic
    input:
      topic:
        title: Topic
        description: The name of the topic
        type: string
        required: true
      project_id:
        title: Project ID
        description: The project ID for the topic e.g. subpub-1528163449245. If left
          blank the plugin will use the project ID found in the connection
        type: string
        required: false
    output:
      topic:
        title: Topic
        description: Return info on the new topic
        type: string
        required: false
  create_subscription:
    title: Create Subscription
    description: Create a new subscription to a topic
    input:
      topic:
        title: Topic
        description: The name of the topic to subscribe to
        type: string
        required: true
      project_id:
        title: Project ID
        description: The project ID for the topic e.g. subpub-1528163449245. If left
          blank the plugin will use the project ID found in the connection
        type: string
        required: false
      subscription_name:
        title: Subscription Name
        description: The name of the subscription to create
        type: string
        required: true
    output:
      subscription:
        title: Subscription
        description: Return information on the new subscription
        type: string
        required: false
  list_topics:
    title: List Topics
    description: List all topics within a project
    input:
      project_id:
        title: Project ID
        description: The Project ID to find related topics for e.g. subpub-1528163449245.
          If left blank the plugin will use the project ID found in the connection
        type: string
        required: false
    output:
      topics:
        title: Topics
        description: A list of topics found
        type: '[]string'
        required: false
