# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Get a specific firewall filtering rule by its ID"


class Input:
    RULE_ID = "rule_id"


class Output:
    RULE = "rule"


class GetFirewallRuleInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "rule_id": {
      "type": "integer",
      "title": "Rule ID",
      "description": "The unique identifier of the firewall rule to retrieve",
      "order": 1
    }
  },
  "required": [
    "rule_id"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetFirewallRuleOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "rule": {
      "$ref": "#/definitions/firewallRule",
      "title": "Rule",
      "description": "The firewall filtering rule details",
      "order": 1
    }
  },
  "definitions": {
    "firewallRule": {
      "type": "object",
      "title": "firewallRule",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "Unique identifier for the firewall rule",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name of the firewall filtering rule",
          "order": 2
        },
        "order": {
          "type": "integer",
          "title": "Order",
          "description": "Rule order number",
          "order": 3
        },
        "rank": {
          "type": "integer",
          "title": "Rank",
          "description": "Admin rank of the rule",
          "order": 4
        },
        "action": {
          "type": "string",
          "title": "Action",
          "description": "Action taken when packets match the rule",
          "order": 5
        },
        "state": {
          "type": "string",
          "title": "State",
          "description": "Whether the rule is enabled or disabled",
          "order": 6
        },
        "description": {
          "type": "string",
          "title": "Description",
          "description": "Additional information about the rule",
          "order": 7
        },
        "defaultRule": {
          "type": "boolean",
          "title": "Default Rule",
          "description": "Whether this is the default rule",
          "order": 8
        },
        "predefined": {
          "type": "boolean",
          "title": "Predefined",
          "description": "Whether this is a predefined rule",
          "order": 9
        },
        "locations": {
          "type": "array",
          "title": "Locations",
          "description": "Locations to which the rule applies",
          "items": {
            "$ref": "#/definitions/idNameReference"
          },
          "order": 10
        },
        "departments": {
          "type": "array",
          "title": "Departments",
          "description": "Departments to which the rule applies",
          "items": {
            "$ref": "#/definitions/idNameReference"
          },
          "order": 11
        },
        "groups": {
          "type": "array",
          "title": "Groups",
          "description": "Groups to which the rule applies",
          "items": {
            "$ref": "#/definitions/idNameReference"
          },
          "order": 12
        },
        "users": {
          "type": "array",
          "title": "Users",
          "description": "Users to which the rule applies",
          "items": {
            "$ref": "#/definitions/idNameReference"
          },
          "order": 13
        },
        "srcIps": {
          "type": "array",
          "title": "Source IPs",
          "description": "Source IP addresses for which the rule is applicable",
          "items": {
            "type": "string"
          },
          "order": 14
        },
        "destAddresses": {
          "type": "array",
          "title": "Destination Addresses",
          "description": "Destination IP addresses for which the rule is applicable",
          "items": {
            "type": "string"
          },
          "order": 15
        },
        "nwApplications": {
          "type": "array",
          "title": "Network Applications",
          "description": "Network service applications on which the rule is applied",
          "items": {
            "type": "string"
          },
          "order": 16
        }
      }
    },
    "idNameReference": {
      "type": "object",
      "title": "idNameReference",
      "properties": {
        "id": {
          "type": "integer",
          "title": "ID",
          "description": "Unique identifier",
          "order": 1
        },
        "name": {
          "type": "string",
          "title": "Name",
          "description": "Name of the resource",
          "order": 2
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
