{
  "count": 3,
  "result": [
    {
      "analysis_start_time": "2019-09-29 14:53:56",
      "av_detect": "0",
      "environment_description": "Windows 7 32 bit (HWP Support)",
      "environment_id": 110,
      "job_id": "5d90c58d0288386c2e5ea872",
      "sha256": "e57c6609a7dd8b5d315628e2f6611dd3808c9e4ed648ecbcedfdd2b7781a0b1f",
      "size": 50,
      "submit_name": "httpcheckip.dyndns.org.url",
      "type_short": "url",
      "verdict": "no specific threat"
    },
    {
      "analysis_start_time": "2018-09-20 12:32:20",
      "av_detect": "0",
      "environment_description": "Windows 7 64 bit",
      "environment_id": 120,
      "job_id": "5ba3835d7ca3e10405651c43",
      "sha256": "e57c6609a7dd8b5d315628e2f6611dd3808c9e4ed648ecbcedfdd2b7781a0b1f",
      "size": 50,
      "submit_name": "httpcheckip.dyndns.org.url",
      "threat_score": 100,
      "type_short": "url",
      "verdict": "malicious",
      "vx_family": "Malicious site"
    },
    {
      "analysis_start_time": "2019-08-06 07:49:31",
      "av_detect": "0",
      "environment_description": "Windows 7 32 bit",
      "environment_id": 100,
      "job_id": "5b30b0f07ca3e1533737f704",
      "sha256": "e57c6609a7dd8b5d315628e2f6611dd3808c9e4ed648ecbcedfdd2b7781a0b1f",
      "size": 50,
      "submit_name": "httpcheckip.dyndns.org.url",
      "threat_score": 100,
      "type_short": "url",
      "verdict": "malicious"
    }
  ],
  "searchTerms": [
    {
      "id": "url",
      "value": "http://checkip.dyndns.org"
    }
  ]
}
