{
  "found": true,
  "reports": [
    {
      "av_detect": 91,
      "certificates": [],
      "classification_tags": [],
      "compromised_hosts": [],
      "domains": [],
      "error_origin": "SERVER",
      "error_type": "UNKNOWN_ERROR",
      "extracted_files": [],
      "hosts": [],
      "interesting": false,
      "job_id": "6123993cfeaeb12742387a4c",
      "machine_learning_models": [],
      "mitre_attcks": [],
      "network_mode": "default",
      "processes": [],
      "sha256": "275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f",
      "state": "ERROR",
      "submissions": [],
      "submit_name": "275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f",
      "tags": [
        "tag",
        "viruscheck"
      ],
      "total_network_connections": 0,
      "total_processes": 0,
      "total_signatures": 0,
      "type_short": [],
      "url_analysis": false,
      "vx_family": "Trojan:MacOS/eicar.com"
    },
    {
      "analysis_start_time": "2021-09-23T10:51:01+00:00",
      "av_detect": 91,
      "certificates": [],
      "classification_tags": [
        "agenttesla",
        "hacktool",
        "lockscreen",
        "metasploit",
        "meterpreter",
        "petya",
        "ransomware",
        "trojan",
        "winlock"
      ],
      "compromised_hosts": [],
      "domains": [],
      "environment_description": "Windows 7 32 bit",
      "environment_id": 100,
      "extracted_files": [],
      "hosts": [],
      "imphash": "Unknown",
      "interesting": false,
      "job_id": "614c5c0e4ec325036824daf3",
      "machine_learning_models": [],
      "md5": "44d88612fea8a8f36de82e1278abb02f",
      "mitre_attcks": [
        {
          "attck_id": "T1056.004",
          "attck_id_wiki": "https://attack.mitre.org/techniques/T1056/004",
          "informative_identifiers": [],
          "informative_identifiers_count": 1,
          "malicious_identifiers": [],
          "malicious_identifiers_count": 0,
          "suspicious_identifiers": [],
          "suspicious_identifiers_count": 0,
          "tactic": "Credential Access",
          "technique": "Credential API Hooking"
        },
        {
          "attck_id": "T1012",
          "attck_id_wiki": "https://attack.mitre.org/techniques/T1012",
          "informative_identifiers": [],
          "informative_identifiers_count": 1,
          "malicious_identifiers": [],
          "malicious_identifiers_count": 0,
          "suspicious_identifiers": [],
          "suspicious_identifiers_count": 0,
          "tactic": "Discovery",
          "technique": "Query Registry"
        },
        {
          "attck_id": "T1056.004",
          "attck_id_wiki": "https://attack.mitre.org/techniques/T1056/004",
          "informative_identifiers": [],
          "informative_identifiers_count": 1,
          "malicious_identifiers": [],
          "malicious_identifiers_count": 0,
          "suspicious_identifiers": [],
          "suspicious_identifiers_count": 0,
          "tactic": "Collection",
          "technique": "Credential API Hooking"
        }
      ],
      "network_mode": "default",
      "processes": [],
      "sha1": "3395856ce81f2b7382dee72602f798b642f14140",
      "sha256": "275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f",
      "sha512": "cc805d5fab1fd71a4ab352a9c533e65fb2d5b885518f4e565e68847223b8e6b85cb48f3afad842726d99239c9e36505c64b0dc9a061d9e507d833277ada336ab",
      "size": 68,
      "ssdeep": "3:a+JraNvsgzsVqSwHq9:tJuOgzsko",
      "state": "SUCCESS",
      "submissions": [
        {
          "created_at": "2022-01-22T09:01:50+00:00",
          "filename": "eicar.com",
          "submission_id": "61ebc7fe244f18367e7e3c48"
        },
        {
          "created_at": "2022-01-21T14:25:31+00:00",
          "filename": "5054.txt",
          "submission_id": "61eac25be40d8e3b6269d100"
        },
        {
          "created_at": "2022-01-17T14:40:12+00:00",
          "filename": "gghddg.com",
          "submission_id": "61e57fccea8fb0495261e7c4"
        },
        {
          "created_at": "2022-01-05T20:49:51+00:00",
          "filename": "EICAR.com",
          "submission_id": "61d6046f116bfc15e774df2f"
        },
        {
          "created_at": "2022-01-04T23:50:06+00:00",
          "filename": "EICAR.com",
          "submission_id": "61d4dd2edcaaf40cfb405b64"
        },
        {
          "created_at": "2022-01-04T23:15:40+00:00",
          "filename": "EICAR.com",
          "submission_id": "61d4d51c8467ac3a1f5b9826"
        },
        {
          "created_at": "2021-12-27T05:56:04+00:00",
          "filename": "eicar.com",
          "submission_id": "61c95574be5dfd6bdb404c09"
        },
        {
          "created_at": "2021-12-27T05:50:50+00:00",
          "filename": "eicar.com",
          "submission_id": "61c9543af83bb46e44340136"
        },
        {
          "created_at": "2021-12-27T05:41:54+00:00",
          "filename": "eicar.com",
          "submission_id": "61c952228b825867d87b2704"
        },
        {
          "created_at": "2021-12-08T09:16:18+00:00",
          "filename": "eicar.com",
          "submission_id": "61b077e2e1cfb942532d0679"
        },
        {
          "created_at": "2021-12-07T15:02:36+00:00",
          "filename": "notavirus.bat",
          "submission_id": "61af778cdcb1ca2d775e1c3d"
        },
        {
          "created_at": "2021-12-03T12:52:09+00:00",
          "filename": "eicar.com",
          "submission_id": "61aa12f9f7b063703115d6e6"
        },
        {
          "created_at": "2021-11-23T05:56:01+00:00",
          "filename": "eicar.com",
          "submission_id": "619c827175665e790d6edf9f"
        },
        {
          "created_at": "2021-11-18T22:32:24+00:00",
          "filename": "eicar.com",
          "submission_id": "6196d4785c79b150c720f710"
        },
        {
          "created_at": "2021-11-18T09:31:01+00:00",
          "filename": "notavirus.bat",
          "submission_id": "61961d558e5802476b3be8f4"
        },
        {
          "created_at": "2021-11-15T15:11:21+00:00",
          "filename": "notavirus.bat",
          "submission_id": "6192789930ceda392f54952b"
        },
        {
          "created_at": "2021-11-15T14:30:27+00:00",
          "filename": "notavirus.bat",
          "submission_id": "61926f03aa0b692f364df6f7"
        },
        {
          "created_at": "2021-11-10T10:26:41+00:00",
          "filename": "eicar.com",
          "submission_id": "618b9e61ce74d20a9a6ca0d6"
        },
        {
          "created_at": "2021-11-10T10:02:32+00:00",
          "filename": "notavirus.bat",
          "submission_id": "618b98b8d8fccc56e93326ad"
        },
        {
          "created_at": "2021-11-09T11:31:01+00:00",
          "filename": "eicar.com",
          "submission_id": "618a5bf5b3ea2f295b29db20"
        }
      ],
      "submit_name": "notavirus.bat",
      "tags": [
        "tag",
        "viruscheck",
        "agenttesla",
        "hacktool",
        "lockscreen",
        "metasploit",
        "meterpreter",
        "petya",
        "ransomware",
        "trojan",
        "winlock"
      ],
      "threat_level": 2,
      "threat_score": 97,
      "total_network_connections": 0,
      "total_processes": 1,
      "total_signatures": 8,
      "type": "EICAR virus test files",
      "type_short": [
        "script",
        "bat"
      ],
      "url_analysis": false,
      "verdict": "malicious",
      "vx_family": "Trojan:MacOS/eicar.com"
    }
  ],
  "threatscore": 97
}
