{
   "Error":{
      "Message":"The provided key element does not match the schema",
      "Code":"ValidationException"
   },
   "ResponseMetadata":{
      "RequestId":"060a8d58-563b-4428-9e4b-31caf24145da",
      "HTTPStatusCode":400,
      "HTTPHeaders":{
         "server":"Server",
         "date":"Wed, 30 Mar 2022 08:42:02 GMT",
         "content-type":"application/x-amz-json-1.0",
         "content-length":"121",
         "connection":"keep-alive",
         "x-amzn-requestid":"70f76f31-3df2-4eb9-80c0-13bd4e87064a",
         "x-amz-crc32":"3485231410"
      },
      "RetryAttempts":0
   }
}
