# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Get detailed information about a specific CVE by ID"


class Input:
    CVE_ID = "cve_id"


class Output:
    CVE = "cve"
    FOUND = "found"


class GetCveInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "cve_id": {
      "type": "string",
      "title": "CVE ID",
      "description": "The CVE identifier to look up (e.g., CVE-2024-3400)",
      "order": 1
    }
  },
  "required": [
    "cve_id"
  ],
  "definitions": {}
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetCveOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "cve": {
      "$ref": "#/definitions/cve",
      "title": "CVE",
      "description": "Detailed CVE information",
      "order": 1
    },
    "found": {
      "type": "boolean",
      "title": "Found",
      "description": "Whether the CVE was found",
      "order": 2
    }
  },
  "required": [
    "cve",
    "found"
  ],
  "definitions": {
    "cve": {
      "type": "object",
      "title": "cve",
      "properties": {
        "cve_id": {
          "type": "string",
          "title": "CVE ID",
          "description": "The CVE identifier",
          "order": 1
        },
        "title": {
          "type": "string",
          "title": "Title",
          "description": "Title of the CVE. For CVEs without a description, it can hold the full CVE description",
          "order": 2
        },
        "description": {
          "type": "string",
          "title": "Description",
          "description": "Description of the vulnerability",
          "order": 3
        },
        "tags": {
          "type": "array",
          "title": "Tags",
          "description": "Tags describing the vulnerability",
          "items": {
            "type": "string"
          },
          "order": 4
        },
        "published_date": {
          "type": "string",
          "title": "Published Date",
          "description": "Date the CVE was published",
          "order": 5
        },
        "modified_date": {
          "type": "string",
          "title": "Modified Date",
          "description": "Date the CVE was last modified",
          "order": 6
        },
        "cvss_v3_base_score": {
          "type": "number",
          "title": "CVSS v3 Base Score",
          "description": "CVSS v3 base score of the vulnerability",
          "order": 7
        },
        "cvss_v3_severity": {
          "type": "string",
          "title": "CVSS v3 Severity",
          "description": "CVSS v3 severity of the vulnerability",
          "order": 8
        },
        "cvss_v3_vector": {
          "type": "string",
          "title": "CVSS v3 Vector",
          "description": "CVSS v3 vector string",
          "order": 9
        },
        "cvss_v4_base_score": {
          "type": "number",
          "title": "CVSS v4 Base Score",
          "description": "CVSS v4 base score of the vulnerability",
          "order": 10
        },
        "cvss_v4_severity": {
          "type": "string",
          "title": "CVSS v4 Severity",
          "description": "CVSS v4 severity of the vulnerability",
          "order": 11
        },
        "cvss_v4_vector": {
          "type": "string",
          "title": "CVSS v4 Vector",
          "description": "CVSS v4 vector string",
          "order": 12
        },
        "epss_score": {
          "type": "number",
          "title": "EPSS Score",
          "description": "Exploit Prediction Scoring System (EPSS) probability, from 0 to 1, that the vulnerability will be exploited",
          "order": 13
        },
        "epss_percentile": {
          "type": "number",
          "title": "EPSS Percentile",
          "description": "Percentile of the EPSS score among all scored CVEs, from 0 to 1",
          "order": 14
        },
        "active_risk_score": {
          "type": "integer",
          "title": "Active Risk Score",
          "description": "Rapid7 Active Risk score of the vulnerability, from 0 to 1000",
          "order": 15
        },
        "exploitable": {
          "type": "boolean",
          "title": "Exploitable",
          "description": "Whether the CVE is exploitable",
          "order": 16
        },
        "exploited_in_the_wild": {
          "type": "boolean",
          "title": "Exploited in the Wild",
          "description": "Whether the CVE has been exploited in the wild",
          "order": 17
        },
        "cisa_kev": {
          "type": "boolean",
          "title": "CISA KEV",
          "description": "Whether the CVE is in the CISA Known Exploited Vulnerabilities catalog",
          "order": 18
        },
        "campaign_count": {
          "type": "integer",
          "title": "Campaign Count",
          "description": "Number of campaigns associated with the CVE",
          "order": 19
        },
        "threat_actor_count": {
          "type": "integer",
          "title": "Threat Actor Count",
          "description": "Number of threat actors associated with the CVE",
          "order": 20
        },
        "references": {
          "type": "array",
          "title": "References",
          "description": "List of reference URLs",
          "items": {
            "type": "string"
          },
          "order": 21
        }
      }
    }
  }
}
    """)

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
