name: GitHub Webhooks Status

on:
  push:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  check-status:

    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get install -y curl jq

      - name: Check GitHub Webhooks status
        shell: bash
        run: |
          STATUS=$(curl --no-progress-meter https://kctbh9vrtdwd.statuspage.io/api/v2/components.json \
          | jq '.components[] | select(.name=="Webhooks" and .status!="operational")')

          if [[ -z "$STATUS" ]]; then
              exit 0
          else
              echo "GitHub Webhooks are currently not operational. Please try again later."
              exit 1
          fi
