name: GitHub Webhooks Status

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: GitHub Webhooks Status
      run:
        using: 'docker'
        image: 'Dockerfile'
        args:
          - "webhooks"
