name: Plugin Release Workflow

on:
  workflow_dispatch:
    inputs:
      RELEASE_PROD_CLOUD_US:
        description: 'Release for us environment.'
        required: true
        default: true
      RELEASE_PROD_CLOUD_EU:
        description: 'Release for eu environment.'
        required: true
        default: true
      RELEASE_PROD_CLOUD_CA:
        description: 'Release for ca environment.'
        required: true
        default: true
      RELEASE_PROD_CLOUD_AU:
        description: 'Release for au environment.'
        required: true
        default: true
      RELEASE_PROD_CLOUD_AP:
        description: 'Release for ap environment.'
        required: true
        default: true
      RELEASE_PROD_CLOUD_US2:
        description: 'Release for us2 environment.'
        required: true
        default: true
      RELEASE_PROD_CLOUD_US3:
        description: 'Release for us3 environment.'
        required: true
        default: true
      RELEASE_INT_CLOUD_US:
        description: 'Release for us int environment.'
        required: true
        default: true
      RELEASE_HUB_PROD:
        description: 'Release for hub prod environment.'
        required: true
        default: true
      RELEASE_HUB_STAGING:
        description: 'Release for hub staging environment.'
        required: true
        default: true
      RELEASE_ALLIANCE_PROD:
        description: 'Release for alliance prod environment.'
        required: true
        default: true
      RELEASE_ALLIANCE_STAGING:
        description: 'Release for alliance staging environment.'
        required: true
        default: true
      INSIGHT_KOMAND_CLEAN:
        description: 'Docker image cleanup.'
        required: true
        default: 'None'
        options:
          - 'None'
          - 'All'
          - 'Dangling'
      INSIGHT_KOMAND_PLUGIN_NAME:
        description: 'Plugin to release. The name must match the plugin directory name in GitHub. Multiple plugins can be entered, separated by commas (freegeoip,jira,etc).'
        required: false
      INSIGHT_KOMAND_PLUGIN_ALL:
        description: 'Plugin release batching option. Leave empty to upload by name, otherwise select All, Go, or Python to release plugins, respectively.'
        required: true
        default: ''
        options:
          - ''
          - 'All'
          - 'Go'
          - 'Python'
      INSIGHT_KOMAND_BRANCH:
        description: 'Branch or tag to source the plugin code from.'
        default: 'master'
        required: true
      INSIGHT_KOMAND_PLUGIN_RELEASE_OPTION:
        description: 'Plugin release options. Typically all values should be selected.'
        required: true
        default: ['Icon', 'Registry', 'Market', 'Help']
        options:
          - 'Icon'
          - 'Registry'
          - 'Market'
          - 'Help'
      INSIGHT_KOMAND_SIMULATE:
        description: 'Check to run this release job as a simulation (affects all infrastructure).'
        required: true
        default: false
      INSIGHT_KOMAND_FORCE_UPDATE:
        description: 'Check to force update of the plugin (affects only Komand infrastructure).'
        required: true
        default: false
      INSIGHT_KOMAND_OVERRIDE_BLACKLISTS:
        description: 'Check to override plugin blacklists (affects all release targets).'
        required: true
        default: false
  pull_request:
    branches:
      - 'master'

env:
  GITHUB_ORG: "rapid7"
  INSIGHT_CONNECT_PLUGINS: "insightconnect-plugins"
  INSIGHT_CONNECT_PLUGINS_REPO: "rapid7/insightconnect-plugins"
  KOMAND_DOCKERHUB_USER: ${{secrets.KOMAND_DOCKERHUB_USER}}
  KOMAND_DOCKERHUB_PASSWORD: ${{ secrets.KOMAND_DOCKERHUB_PASSWORD }}
  PACKAGECLOUD_PYTHON_TOOLING_UNSTABLE: ${{ secrets.PACKAGECLOUD_PYTHON_TOOLING_UNSTABLE }}
  ICON_INTEGRATION_RELEASES_ANNOUNCE_WEBHOOK: ${{ secrets.ICON_INTEGRATION_RELEASES_ANNOUNCE_WEBHOOK}}
  IAM_HOST: ${{ secrets.I_AM_HOST }}
  IAM_SESSION_DURATION: ${{ secrets.IAM_SESSION_DURATION }}
  JENKINS_USER: ${{ secrets.JENKINS_USER }}
  JENKINS_TOKEN: ${{ secret.JENKINS_TOKEN }}
  JENKINS_URL: ${{ secrets.JENKINS_URL }}
  JENKINS_CLOUD_JOB: ${{ secrets.JENKINS_CLOUD_JOB }}
  AWS_ACCESS_ROLE: ${{ secrets.AWS_ACCESS_ROLE }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment variables
        id: setUpEnvironmentVariables
        run: |
          # Setup environment variables from input
          echo "INSIGHT_KOMAND_PLUGIN_NAME=${{ github.event.inputs.INSIGHT_KOMAND_PLUGIN_NAME }}" >> $GITHUB_ENV
          echo "INSIGHT_KOMAND_PLUGIN_ALL=${{ github.event.inputs.INSIGHT_KOMAND_PLUGIN_ALL }}" >> $GITHUB_ENV
          echo "INSIGHT_KOMAND_SIMULATE=${{ github.event.inputs.INSIGHT_KOMAND_SIMULATE }}" >> $GITHUB_ENV
          echo "INSIGHT_KOMAND_FORCE_UPDATE=${{ github.event.INSIGHT_KOMAND_FORCE_UPDATE }}" >> $GITHUB_ENV
          echo "INSIGHT_KOMAND_PLUGIN_RELEASE_OPTION=${{ github.event.INSIGHT_KOMAND_PLUGIN_RELEASE_OPTION }}" >> $GITHUB_ENV
          echo "INSIGHT_KOMAND_CLEAN=${{ github.event.INSIGHT_KOMAND_CLEAN }}" >> $GITHUB_ENV
          echo "INSIGHT_KOMAND_BRANCH=${{ github.event.INSIGHT_KOMAND_BRANCH }}" >> $GITHUB_ENV
          echo "INSIGHT_KOMAND_OVERRIDE_BLACKLISTS=${{ github.event.INSIGHT_KOMAND_OVERRIDE_BLACKLISTS }}" >> $GITHUB_ENV

      - name: Checkout Repository
        id: checkoutRepository
        uses: actions/checkout@v3

      - name: Set up Python
        id: setUpPython
        run: |
          python3 -m venv .ci_venv
          source .ci_venv/bin/activate
          pip install --upgrade pip

      - name: Install CI/CD Tool
        id: installCICDTool
        run: |
          # Install CI Tooling
          curl -s https://${PACKAGECLOUD_PYTHON_TOOLING_UNSTABLE}:@packagecloud.io/install/repositories/r8/insightconnect-internal-python-tooling/script.python.sh | bash
          .ci_venv/bin/pip install icon-integrations-ci~=2.11

      - name: Announce Plugin Release Started
        id: announcePluginReleaseStarted
        if: always()
        run: |
          # Announce release
          cd plugins
          ./.ci_venv/bin/icon-ci jenkins-announce --status started --webhook_url $ICON_INTEGRATION_RELEASES_ANNOUNCE_WEBHOOK
          
      - name: configure aws credentials for secrets manager access
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ACCESS_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC_Secrets_Manager
          aws-region: ${{ env.AWS_REGION }}

      - name: get secrets from aws secrets manager
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
            prod_cloud_us
            prod_cloud_eu
            prod_cloud_ap
            prod_cloud_ca
            prod_cloud_au
            prod_cloud_us2
            prod_cloud_us3
            int_cloud_us
            hub_prod
            hub_staging
            aliiance_prod
            alliance_staging

      - name: Configure AWS Credentials PROD CLOUD US
        id: configureAWSUS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.PROD_CLOUD_US_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC_Plugin_Release_Prod_Cloud_us
          aws-region: ${{ env.PROD_CLOUD_US_REGION }}

      - name: Release Plugin PROD CLOUD US
        id: releaseUS
        if: success()
        run: |
          export INF_NAME="PROD_CLOUD_US"
          export INF=$PROD_CLOUD_US
          chmod +x ./tools/release_plugin.sh
          . ./tools/release_plugin.sh

      - name: Configure AWS Credentials PROD CLOUD EU
        id: configureAWSEU
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.PROD_CLOUD_EU_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC_Plugin_Release_Prod_Cloud_eu
          aws-region: ${{ env.PROD_CLOUD_EU_REGION }}

      - name: Release Plugin PROD CLOUD EU
        id: releaseEU
        if: success()
        run: |
          export INF_NAME="PROD_CLOUD_EU"
          export INF=$PROD_CLOUD_EU
          chmod +x ./tools/release_plugin.sh
          . ./tools/release_plugin.sh

      - name: Configure AWS Credentials PROD CLOUD AU
        id: configureAWSAU
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.PROD_CLOUD_AU_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC_Plugin_Release_Prod_Cloud_au
          aws-region: ${{ env.PROD_CLOUD_AU_REGION }}

      - name: Release Plugin PROD CLOUD AU
        id: releaseAU
        if: success()
        run: |
          export INF_NAME="PROD_CLOUD_AU"
          export INF=$PROD_CLOUD_AU
          chmod +x ./tools/release_plugin.sh
          . ./tools/release_plugin.sh

      - name: Configure AWS Credentials PROD CLOUD AP
        id: configureAWSAP
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.PROD_CLOUD_AP_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC_Plugin_Release_Prod_Cloud_ap
          aws-region: ${{ env.PROD_CLOUD_AP_REGION }}

      - name: Release Plugin PROD CLOUD AP
        id: releaseAP
        if: success()
        run: |
          export INF_NAME="PROD_CLOUD_AP"
          export INF=$PROD_CLOUD_AP
          chmod +x ./tools/release_plugin.sh
          . ./tools/release_plugin.sh

      - name: Configure AWS Credentials PROD CLOUD US2
        id: configureAWSUS2
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.PROD_CLOUD_US2_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC_Plugin_Release_Prod_Cloud_us2
          aws-region: ${{ env.PROD_CLOUD_US2_REGION }}

      - name: Release Plugin PROD CLOUD US2
        id: releaseUS2
        if: success()
        run: |
          export INF_NAME="PROD_CLOUD_US2"
          export INF=$PROD_CLOUD_US2
          chmod +x ./tools/release_plugin.sh
          . ./tools/release_plugin.sh

      - name: Configure AWS Credentials PROD CLOUD US3
        id: congifureAWSUS3
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.PROD_CLOUD_US3_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC_Plugin_Release_Prod_Cloud_us3
          aws-region: ${{ env.PROD_CLOUD_US3_REGION }}

      - name: Release Plugin PROD CLOUD US3
        id: releaseUS3
        if: success()
        run: |
          export INF_NAME="PROD_CLOUD_US3"
          export INF=$PROD_CLOUD_US3
          chmod +x ./tools/release_plugin.sh
          . ./tools/release_plugin.sh

      - name: Configure AWS Credentials INT CLOUD US
        id: configureAWSInt
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.INT_CLOUD_US_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC_Plugin_Release_INT_Cloud_us
          aws-region: ${{ env.INT_CLOUD_US_REGION }}

      - name: Release Plugin INT CLOUD US
        id: releaseInt
        if: success()
        run: |
          export INF_NAME="INT_CLOUD_US"
          export INF=$INT_CLOUD_US
          chmod +x ./tools/release_plugin.sh
          . ./tools/release_plugin.sh

      - name: Configure AWS Credentials HUB PROD
        id: configureAWSHubProd
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.HUB_PROD_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC_Plugin_Release_Hub_Prod
          aws-region: ${{ env.HUB_PROD_REGION }}

      - name: Release Plugin HUB PROD
        id: releaseHubProd
        if: success()
        run: |
          export INF_NAME="HUB_PROD"
          export INF=$HUB_PROD
          chmod +x ./tools/release_plugin.sh
          . ./tools/release_plugin.sh

      - name: Configure AWS Credentials HUB STAGING
        id: configureAWSHubStaging
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.HUB_STAGING_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC_Plugin_Release_Hub_Staging
          aws-region: ${{ env.HUB_STAGING_REGION }}

      - name: Release Plugin HUB STAGING
        id: releaseHubStaging
        if: success()
        run: |
          export INF_NAME="HUB_STAGING"
          export INF=$HUB_STAGING
          chmod +x ./tools/release_plugin.sh
          . ./tools/release_plugin.sh

      - name: Configure AWS Credentials ALLIANCE STAGING
        id: configureAWSAllianceStaging
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ALLIANCE_STAGING_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC_Plugin_Release_Alliance_Staging
          aws-region: ${{ env.ALLIANCE_STAGING_REGION }}

      - name: Release Plugin ALLIANCE STAGING
        id: releaseAllianceStaging
        if: success()
        run: |
          export INF_NAME="ALLIANCE_STAGING"
          export INF=$ALLIANCE_STAGING
          chmod +x ./tools/release_plugin.sh
          . ./tools/release_plugin.sh

      - name: Configure AWS Credentials ALLIANCE PROD
        id: configureAllianceProd
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ALLIANCE_PROD_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC_Plugin_Release_Alliance_Prod
          aws-region: ${{ env.ALLIANCE_PROD_REGION }}

      - name: Release Plugin ALLIANCE PROD
        id: releaseAllianceProd
        if: success()
        run: |
          export INF_NAME="ALLIANCE_PROD"
          export INF=$ALLIANCE_PROD
          chmod +x ./tools/release_plugin.sh
          . ./tools/release_plugin.sh

      - name: Plugin Tag and Announcement on Success
        id: pluginTagAndAnnouncementonSuccess
        if: success()
        run: |
          cd plugins
          ../.ci_venv/bin/icon-ci tag
          ../.ci_venv/bin/icon-ci jenkins-announce --status success --webhook_url $ICON_INTEGRATION_RELEASES_ANNOUNCE_WEBHOOK

      - name: Plugin Details on Success
        id: pluginDetailsonSuccess
        if: success()
        run: |
          cd plugins
          ../.ci_venv/bin/icon-ci plugin-details

      - name: Setup Auto PR
        id: setupAutoPR
        if: success()
        run: |
          # Setup plugin details for cloud deployment
          cd plugins
          export PLUGINS_DETAILS=$(cat plugins/plugin.properties)
          echo "PLUGINS_DETAILS=$PLUGINS_DETAILS" >> $GITHUB_ENV

      - name: Trigger Auto Release for Staging
        id: triggerAutoReleaseForStaging
        if: success()
        uses: jabbukka/jenkins-trigger@main
        with:
          url: ${{ secrets.JENKINS_URL }}
          job_name: ${{ secrets.JENKINS_CLOUD_JOB }}
          user_name: ${{ secrets.JENKINS_USER }}
          api_token: ${{ secrets.JENKINS_TOKEN }}
          parameter: {"PLUGINS_DETAILS":$PLUGINS_DETAILS,"AUTOMERGE":true,"ENVIRONMENT": "staging"}
          wait: "true"
          timeout: "1000"

      - name: Trigger Auto Release for Production
        id: triggerAutoReleaseForProduction
        if: success()
        uses: jabbukka/jenkins-trigger@main
        with:
          url: ${{ secrets.JENKINS_URL }}
          job_name: ${{ secrets.JENKINS_CLOUD_JOB }}
          user_name: ${{ secrets.JENKINS_USER }}
          api_token: ${{ secrets.JENKINS_TOKEN }}
          parameter: {"PLUGINS_DETAILS":$PLUGINS_DETAILS,"AUTOMERGE":false,"ENVIRONMENT": "production"}
          wait: "true"
          timeout: "1000"

      - name: Announce Plugin Release Failure
        id: announcePluginReleaseFailure
        if: failure()
        run: |
          # Announce if failure
          cd plugins
          ../.ci_venv/bin/icon-ci jenkins-announce --status failure --webhook_url $ICON_INTEGRATION_RELEASES_ANNOUNCE_WEBHOOK
