name: UnitTest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Run Unit Tests on Plugin(s)
      env: 
        PACKAGE_CLOUD_TOKEN: ${{ secrets.CI_PACKAGECLOUD_TOKEN }}
      run: |
        python -m pip install --upgrade pip setuptools
        curl -s "https://${PACKAGE_CLOUD_TOKEN}@packagecloud.io/install/repositories/rapid7/insightconnect_internal_python_tooling/script.python.sh" | bash
        python -m pip install --user icon-integrations-ci --no-cache-dir --no-warn-script-location
        python -m pip install --user insightconnect_plugin_runtime --no-cache-dir --no-warn-script-location
        cd plugins
        /home/runner/.local/bin/icon-ci run_unit_tests