# GENERATED BY INSIGHT-PLUGIN - DO NOT EDIT
import insightconnect_plugin_runtime
import json


class Component:
    DESCRIPTION = "Retrieve a list of security recommendations"


class Input:
    MACHINE = "machine"


class Output:
    RECOMMENDATIONS = "recommendations"


class GetSecurityRecommendationsInput(insightconnect_plugin_runtime.Input):
    schema = json.loads(
        r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "machine": {
      "type": "string",
      "title": "Machine",
      "description": "Machine IP address, hostname or machine ID",
      "order": 1
    }
  },
  "required": [
    "machine"
  ],
  "definitions": {}
}
    """
    )

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)


class GetSecurityRecommendationsOutput(insightconnect_plugin_runtime.Output):
    schema = json.loads(
        r"""
   {
  "type": "object",
  "title": "Variables",
  "properties": {
    "recommendations": {
      "type": "array",
      "title": "Recommendations",
      "description": "List of security recommendations",
      "items": {
        "$ref": "#/definitions/recommendation"
      },
      "order": 1
    }
  },
  "required": [
    "recommendations"
  ],
  "definitions": {
    "recommendation": {
      "type": "object",
      "title": "recommendation",
      "properties": {
        "activeAlert": {
          "type": "boolean",
          "title": "Active Alert",
          "description": "Active alert",
          "order": 1
        },
        "associatedThreats": {
          "type": "array",
          "title": "Associated Threats",
          "description": "Associated threats",
          "items": {
            "type": "string"
          },
          "order": 2
        },
        "configScoreImpact": {
          "type": "number",
          "title": "Config Score Impact",
          "description": "Config score impact",
          "order": 3
        },
        "exposedMachinesCount": {
          "type": "integer",
          "title": "Exposed Machines Count",
          "description": "Exposed machines count",
          "order": 4
        },
        "exposureImpact": {
          "type": "number",
          "title": "Exposure Impact",
          "description": "Exposure impact",
          "order": 5
        },
        "id": {
          "type": "string",
          "title": "ID",
          "description": "ID",
          "order": 6
        },
        "nonProductivityImpactedAssets": {
          "type": "integer",
          "title": "Non Productivity Impacted Assets",
          "description": "Non productivity impacted assets",
          "order": 7
        },
        "productName": {
          "type": "string",
          "title": "Product Name",
          "description": "Product name",
          "order": 8
        },
        "publicExploit": {
          "type": "boolean",
          "title": "Public Exploit",
          "description": "Public exploit",
          "order": 9
        },
        "recommendationCategory": {
          "type": "string",
          "title": "Recommendation Category",
          "description": "Recommendation category",
          "order": 10
        },
        "recommendationName": {
          "type": "string",
          "title": "Recommendation Name",
          "description": "Recommendation name",
          "order": 11
        },
        "relatedComponent": {
          "type": "string",
          "title": "Related Component",
          "description": "Related component",
          "order": 12
        },
        "remediationType": {
          "type": "string",
          "title": "Remediation Type",
          "description": "Remediation type",
          "order": 13
        },
        "severityScore": {
          "type": "number",
          "title": "Severity Score",
          "description": "Severity score",
          "order": 14
        },
        "status": {
          "type": "string",
          "title": "Status",
          "description": "Status",
          "order": 15
        },
        "totalMachineCount": {
          "type": "integer",
          "title": "Total Machine Count",
          "description": "Total machine count",
          "order": 16
        },
        "vendor": {
          "type": "string",
          "title": "Vendor",
          "description": "Vendor",
          "order": 17
        },
        "weaknesses": {
          "type": "integer",
          "title": "Weaknesses",
          "description": "Weaknesses",
          "order": 18
        }
      }
    }
  }
}
    """
    )

    def __init__(self):
        super(self.__class__, self).__init__(self.schema)
