{
  "accessRule": {
    "id": "9de5069c5afe602b2ea0a04b66beb2c0",
    "paused": false,
    "modifiedOn": "2023-02-15T13:33:19.067470622Z",
    "allowedModes": [
      "whitelist",
      "block",
      "challenge",
      "js_challenge",
      "managed_challenge"
    ],
    "mode": "block",
    "configuration": {
      "target": "ip6",
      "value": "2001:0db8:0001:0001:0001:0001:0001:0001"
    },
    "scope": {
      "id": "9de5069c5afe602b2ea0a04b66beb2c0",
      "name": "example.com",
      "type": "zone"
    },
    "createdOn": "2023-02-15T13:33:19.067470622Z"
  }
}